import type { EjercicioBanco } from '../../types';

const SETUP = `
CREATE TABLE empleados (id INTEGER PRIMARY KEY, nombre TEXT, departamento TEXT, salario REAL, fecha_contrato TEXT);
INSERT INTO empleados VALUES (1,'María','Ventas',45000,'2020-03-15');
INSERT INTO empleados VALUES (2,'Carlos','Tecnología',65000,'2019-06-01');
INSERT INTO empleados VALUES (3,'Ana','RRHH',48000,'2021-01-10');
INSERT INTO empleados VALUES (4,'Pedro','Ventas',42000,'2022-08-20');
INSERT INTO empleados VALUES (5,'Laura','Tecnología',70000,'2018-11-05');
INSERT INTO empleados VALUES (6,'Miguel','Tecnología',60000,'2020-07-15');
INSERT INTO empleados VALUES (7,'Sofía','Marketing',52000,'2021-04-01');
INSERT INTO empleados VALUES (8,'Javier','Ventas',44000,'2022-02-14');
INSERT INTO empleados VALUES (9,'Elena','RRHH',50000,'2020-09-30');
INSERT INTO empleados VALUES (10,'Andrés','Marketing',55000,'2019-12-01');
CREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL, stock INTEGER);
INSERT INTO productos VALUES (1,'Laptop Pro','Electrónica',1299.99,20);
INSERT INTO productos VALUES (2,'Mouse','Periféricos',29.99,150);
INSERT INTO productos VALUES (3,'Teclado','Periféricos',89.99,80);
INSERT INTO productos VALUES (4,'Monitor','Electrónica',499.99,15);
INSERT INTO productos VALUES (5,'Webcam','Periféricos',79.99,100);
INSERT INTO productos VALUES (6,'Tablet','Electrónica',399.99,25);
CREATE TABLE ventas (id INTEGER PRIMARY KEY, empleado_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT, monto REAL);
INSERT INTO ventas VALUES (1,1,2,5,'2024-01-10',149.95);
INSERT INTO ventas VALUES (2,2,1,2,'2024-01-15',2599.98);
INSERT INTO ventas VALUES (3,1,3,3,'2024-01-20',269.97);
INSERT INTO ventas VALUES (4,3,4,1,'2024-02-05',499.99);
INSERT INTO ventas VALUES (5,2,6,4,'2024-02-10',1599.96);
INSERT INTO ventas VALUES (6,5,1,1,'2024-02-20',1299.99);
INSERT INTO ventas VALUES (7,1,2,10,'2024-03-01',299.90);
INSERT INTO ventas VALUES (8,4,5,2,'2024-03-10',159.98);
`;

export const ejerciciosIntermedio: EjercicioBanco[] = [
  {
    id: 'in-b-001',
    nivel: 'intermedio',
    titulo: 'Empleados con salario sobre el promedio',
    descripcion: 'Muestra nombre y salario de empleados que ganan más que el salario promedio de toda la empresa.',
    objetivo: 'Usar subconsulta para calcular el promedio y comparar.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['nombre','salario'],
      filas: [['Carlos',65000],['Laura',70000],['Miguel',60000],['Andrés',55000],['Sofía',52000]],
    },
    solucionOficial: 'SELECT nombre, salario FROM empleados WHERE salario > (SELECT AVG(salario) FROM empleados) ORDER BY salario DESC;',
    solucionesAlternativas: [],
    explicacion: 'La subconsulta calcula el promedio (53100). La exterior devuelve los que ganan más.',
    pistas: ['Usa una subconsulta: WHERE salario > (SELECT AVG(salario) FROM empleados)'],
    retroalimentacionError: 'WHERE salario > (SELECT AVG(salario) FROM empleados)',
  },
  {
    id: 'in-b-002',
    nivel: 'intermedio',
    titulo: 'Clasificar productos por precio con CASE',
    descripcion: 'Muestra nombre, precio y una columna "rango" que clasifique: Barato (<100), Medio (100-500), Caro (>500).',
    objetivo: 'Usar CASE WHEN para categorización.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['nombre','precio','rango'],
      filas: [
        ['Laptop Pro',1299.99,'Caro'],['Mouse',29.99,'Barato'],
        ['Teclado',89.99,'Barato'],['Monitor',499.99,'Medio'],
        ['Webcam',79.99,'Barato'],['Tablet',399.99,'Medio'],
      ],
    },
    solucionOficial: "SELECT nombre, precio, CASE WHEN precio < 100 THEN 'Barato' WHEN precio <= 500 THEN 'Medio' ELSE 'Caro' END AS rango FROM productos;",
    solucionesAlternativas: [],
    explicacion: 'CASE evalúa de arriba hacia abajo. Monitor (499.99) cumple <= 500 pero no < 100, entonces es Medio.',
    pistas: ["CASE WHEN precio < 100 THEN 'Barato' WHEN precio <= 500 THEN 'Medio' ELSE 'Caro' END"],
    retroalimentacionError: 'Usa CASE WHEN precio < 100 ... WHEN precio <= 500 ... ELSE ...',
  },
  {
    id: 'in-b-003',
    nivel: 'intermedio',
    titulo: 'Unir listas con UNION ALL',
    descripcion: 'Combina en una lista los nombres de empleados de Ventas y los de RRHH, indicando su departamento.',
    objetivo: 'Usar UNION ALL para combinar resultados.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['nombre','departamento'],
      filas: [
        ['María','Ventas'],['Pedro','Ventas'],['Javier','Ventas'],
        ['Ana','RRHH'],['Elena','RRHH'],
      ],
    },
    solucionOficial: "SELECT nombre, departamento FROM empleados WHERE departamento = 'Ventas' UNION ALL SELECT nombre, departamento FROM empleados WHERE departamento = 'RRHH' ORDER BY departamento, nombre;",
    solucionesAlternativas: ["SELECT nombre, departamento FROM empleados WHERE departamento IN ('Ventas','RRHH') ORDER BY departamento, nombre;"],
    explicacion: 'UNION ALL combina los resultados de ambas SELECT sin eliminar duplicados.',
    pistas: ['Usa UNION ALL para combinar', 'O simplemente WHERE IN como alternativa'],
    retroalimentacionError: "WHERE departamento = 'Ventas' UNION ALL WHERE departamento = 'RRHH'",
  },
  {
    id: 'in-b-004',
    nivel: 'intermedio',
    titulo: 'Función UPPER en nombres',
    descripcion: 'Muestra los nombres de todos los empleados en MAYÚSCULAS.',
    objetivo: 'Usar la función de texto UPPER.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['nombre_mayusculas'],
      filas: [['MARÍA'],['CARLOS'],['ANA'],['PEDRO'],['LAURA'],['MIGUEL'],['SOFÍA'],['JAVIER'],['ELENA'],['ANDRÉS']],
    },
    solucionOficial: 'SELECT UPPER(nombre) AS nombre_mayusculas FROM empleados;',
    solucionesAlternativas: [],
    explicacion: 'UPPER() convierte todo el texto a mayúsculas.',
    pistas: ['Usa UPPER(nombre)'],
    retroalimentacionError: 'SELECT UPPER(nombre) AS nombre_mayusculas FROM empleados',
  },
  {
    id: 'in-b-005',
    nivel: 'intermedio',
    titulo: 'Precio con IVA usando ROUND',
    descripcion: 'Muestra nombre, precio original y precio con 21% de IVA, redondeado a 2 decimales.',
    objetivo: 'Usar funciones numéricas ROUND y operaciones aritméticas.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['nombre','precio','precio_iva'],
      filas: [
        ['Laptop Pro',1299.99,1572.99],['Mouse',29.99,36.29],
        ['Teclado',89.99,108.88],['Monitor',499.99,604.99],
        ['Webcam',79.99,96.79],['Tablet',399.99,483.99],
      ],
    },
    solucionOficial: 'SELECT nombre, precio, ROUND(precio * 1.21, 2) AS precio_iva FROM productos;',
    solucionesAlternativas: [],
    explicacion: 'precio * 1.21 suma el 21%. ROUND(..., 2) redondea a 2 decimales.',
    pistas: ['ROUND(precio * 1.21, 2) para precio con IVA'],
    retroalimentacionError: 'SELECT nombre, precio, ROUND(precio * 1.21, 2) AS precio_iva FROM productos',
  },
  {
    id: 'in-b-006',
    nivel: 'intermedio',
    titulo: 'Ventas por mes con STRFTIME',
    descripcion: 'Muestra el mes (YYYY-MM) y el total de ventas de ese mes.',
    objetivo: 'Usar STRFTIME para extraer partes de fecha con GROUP BY.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['mes','total_ventas'],
      filas: [['2024-01',3019.90],['2024-02',3359.94],['2024-03',459.88]],
    },
    solucionOficial: "SELECT STRFTIME('%Y-%m', fecha) AS mes, ROUND(SUM(monto), 2) AS total_ventas FROM ventas GROUP BY STRFTIME('%Y-%m', fecha) ORDER BY mes;",
    solucionesAlternativas: [],
    explicacion: "STRFTIME('%Y-%m', fecha) extrae año y mes. GROUP BY agrupa por mes. SUM suma los montos.",
    pistas: ["STRFTIME('%Y-%m', fecha) para año-mes", 'GROUP BY el mismo STRFTIME'],
    retroalimentacionError: "GROUP BY STRFTIME('%Y-%m', fecha)",
  },
  {
    id: 'in-b-007',
    nivel: 'intermedio',
    titulo: 'CTE para empleados destacados',
    descripcion: 'Usa una CTE para encontrar empleados con salario mayor a $55,000, luego muestra sus datos ordenados.',
    objetivo: 'Usar WITH/CTE para simplificar una consulta.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['nombre','departamento','salario'],
      filas: [['Laura','Tecnología',70000],['Carlos','Tecnología',65000],['Miguel','Tecnología',60000],['Andrés','Marketing',55000]],
    },
    solucionOficial: 'WITH destacados AS (SELECT nombre, departamento, salario FROM empleados WHERE salario > 55000)\nSELECT * FROM destacados ORDER BY salario DESC;',
    solucionesAlternativas: [],
    explicacion: 'La CTE "destacados" filtra los empleados con alto salario. La consulta final los ordena.',
    pistas: ['WITH destacados AS (SELECT ... WHERE salario > 55000)', 'Luego SELECT * FROM destacados'],
    retroalimentacionError: 'WITH nombre_cte AS (SELECT ...) SELECT ... FROM nombre_cte',
  },
  {
    id: 'in-b-008',
    nivel: 'intermedio',
    titulo: 'INSERT y verificar',
    descripcion: 'Inserta un nuevo empleado llamado "Rosa Flores" en Ventas con salario 47000, contratada el 2024-01-01. Luego muestra todos los empleados de Ventas.',
    objetivo: 'Usar INSERT INTO para agregar datos.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['nombre','departamento','salario'],
      filas: [
        ['María','Ventas',45000],['Pedro','Ventas',42000],
        ['Javier','Ventas',44000],['Rosa Flores','Ventas',47000],
      ],
    },
    solucionOficial: "INSERT INTO empleados (nombre, departamento, salario, fecha_contrato) VALUES ('Rosa Flores', 'Ventas', 47000, '2024-01-01');\nSELECT nombre, departamento, salario FROM empleados WHERE departamento = 'Ventas' ORDER BY id;",
    solucionesAlternativas: [],
    explicacion: 'INSERT agrega la fila. SELECT verifica que se insertó correctamente.',
    pistas: ["INSERT INTO empleados (nombre, departamento, salario, fecha_contrato) VALUES ('Rosa Flores', ...)"],
    retroalimentacionError: "INSERT INTO empleados (nombre, departamento, salario, fecha_contrato) VALUES ('Rosa Flores', 'Ventas', 47000, '2024-01-01')",
  },
  {
    id: 'in-b-009',
    nivel: 'intermedio',
    titulo: 'UPDATE de salarios',
    descripcion: 'Aumenta un 5% el salario de todos los empleados de Marketing, luego muéstralos.',
    objetivo: 'Usar UPDATE con SET calculado.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['nombre','salario'],
      filas: [['Sofía',54600],['Andrés',57750]],
    },
    solucionOficial: "UPDATE empleados SET salario = ROUND(salario * 1.05, 0) WHERE departamento = 'Marketing';\nSELECT nombre, salario FROM empleados WHERE departamento = 'Marketing' ORDER BY nombre;",
    solucionesAlternativas: [],
    explicacion: "SET salario = ROUND(salario * 1.05, 0) aumenta 5% y redondea. WHERE limita a Marketing.",
    pistas: ["UPDATE empleados SET salario = ROUND(salario * 1.05, 0) WHERE departamento = 'Marketing'"],
    retroalimentacionError: "UPDATE empleados SET salario = ROUND(salario * 1.05, 0) WHERE departamento = 'Marketing'",
  },
  {
    id: 'in-b-010',
    nivel: 'intermedio',
    titulo: 'DELETE de registros viejos',
    descripcion: 'Elimina las ventas anteriores a 2024-02-01, luego muestra las ventas restantes.',
    objetivo: 'Usar DELETE con condición de fecha.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['id','empleado_id','monto','fecha'],
      filas: [[4,3,499.99,'2024-02-05'],[5,2,1599.96,'2024-02-10'],[6,5,1299.99,'2024-02-20'],[7,1,299.90,'2024-03-01'],[8,4,159.98,'2024-03-10']],
    },
    solucionOficial: "DELETE FROM ventas WHERE fecha < '2024-02-01';\nSELECT id, empleado_id, monto, fecha FROM ventas ORDER BY fecha;",
    solucionesAlternativas: [],
    explicacion: "DELETE elimina las ventas de enero. El SELECT confirma que solo quedan las de febrero y marzo.",
    pistas: ["DELETE FROM ventas WHERE fecha < '2024-02-01'"],
    retroalimentacionError: "DELETE FROM ventas WHERE fecha < '2024-02-01'",
  },
  // ── Ejercicios 11-050: temas variados ───────────────────────────
  {
    id: 'in-b-011',
    nivel: 'intermedio',
    titulo: 'LENGTH con WHERE',
    descripcion: 'Muestra los productos cuyo nombre tiene más de 6 caracteres, con su longitud.',
    objetivo: 'Usar LENGTH para filtrar y mostrar la longitud de texto.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['nombre','longitud'],
      filas: [['Laptop Pro',10],['Monitor',7],['Teclado',7]],
    },
    solucionOficial: 'SELECT nombre, LENGTH(nombre) AS longitud FROM productos WHERE LENGTH(nombre) > 6 ORDER BY longitud DESC, nombre;',
    solucionesAlternativas: [],
    explicacion: 'LENGTH(nombre) devuelve el número de caracteres. WHERE filtra los que tienen más de 6. Mouse(5), Tablet(6) y Webcam(6) quedan excluidos.',
    pistas: ['WHERE LENGTH(nombre) > 6', 'SELECT nombre, LENGTH(nombre) AS longitud', 'ORDER BY longitud DESC, nombre'],
    retroalimentacionError: 'WHERE LENGTH(nombre) > 6 — usa LENGTH tanto en SELECT como en WHERE',
  },
  {
    id: 'in-b-012',
    nivel: 'intermedio',
    titulo: 'UPPER filtrado',
    descripcion: 'Muestra los nombres de los empleados de Tecnología en MAYÚSCULAS.',
    objetivo: 'Combinar UPPER con un filtro WHERE.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['nombre_may'],
      filas: [['CARLOS'],['LAURA'],['MIGUEL']],
    },
    solucionOficial: "SELECT UPPER(nombre) AS nombre_may FROM empleados WHERE departamento = 'Tecnología' ORDER BY nombre;",
    solucionesAlternativas: [],
    explicacion: 'UPPER() convierte el texto a mayúsculas. La conversión solo afecta al resultado; el filtro WHERE opera sobre el valor original.',
    pistas: ["WHERE departamento = 'Tecnología'", 'SELECT UPPER(nombre) AS nombre_may', 'ORDER BY nombre (el original, no el transformado)'],
    retroalimentacionError: "UPPER(nombre) AS nombre_may + WHERE departamento = 'Tecnología'",
  },
  {
    id: 'in-b-013',
    nivel: 'intermedio',
    titulo: 'SUBSTR para iniciales',
    descripcion: 'Muestra el nombre de cada empleado y su inicial (primera letra del nombre). Ordena por id.',
    objetivo: 'Usar SUBSTR para extraer parte de un texto.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['nombre','inicial'],
      filas: [['María','M'],['Carlos','C'],['Ana','A'],['Pedro','P'],['Laura','L'],['Miguel','M'],['Sofía','S'],['Javier','J'],['Elena','E'],['Andrés','A']],
    },
    solucionOficial: 'SELECT nombre, SUBSTR(nombre, 1, 1) AS inicial FROM empleados ORDER BY id;',
    solucionesAlternativas: [],
    explicacion: 'SUBSTR(texto, posición_inicio, longitud): extrae desde la posición 1 con longitud 1, devolviendo solo el primer carácter.',
    pistas: ['SUBSTR(nombre, 1, 1) extrae el primer carácter', 'Alias AS inicial', 'ORDER BY id para mantener el orden de inserción'],
    retroalimentacionError: 'SUBSTR(nombre, 1, 1) AS inicial — los parámetros son: texto, inicio, longitud',
  },
  {
    id: 'in-b-014',
    nivel: 'intermedio',
    titulo: 'SUBSTR para extraer el año',
    descripcion: 'Muestra cada empleado y el año en que fue contratado, extraído de la columna fecha_contrato.',
    objetivo: 'Usar SUBSTR para extraer partes de una cadena de fecha.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['nombre','anio_contrato'],
      filas: [['Laura','2018'],['Carlos','2019'],['Andrés','2019'],['María','2020'],['Miguel','2020'],['Elena','2020'],['Ana','2021'],['Sofía','2021'],['Javier','2022'],['Pedro','2022']],
    },
    solucionOficial: 'SELECT nombre, SUBSTR(fecha_contrato, 1, 4) AS anio_contrato FROM empleados ORDER BY anio_contrato, id;',
    solucionesAlternativas: ["SELECT nombre, STRFTIME('%Y', fecha_contrato) AS anio_contrato FROM empleados ORDER BY anio_contrato, id;"],
    explicacion: 'Las fechas en formato ISO (YYYY-MM-DD) permiten extraer el año con SUBSTR(fecha, 1, 4) o con STRFTIME. Ambos enfoques funcionan.',
    pistas: ['SUBSTR(fecha_contrato, 1, 4) extrae los primeros 4 caracteres (el año)', 'ORDER BY anio_contrato, id para ordenar por año y luego por orden de contratación'],
    retroalimentacionError: 'SUBSTR(fecha_contrato, 1, 4) AS anio_contrato — los 4 primeros chars de la fecha son el año',
  },
  {
    id: 'in-b-015',
    nivel: 'intermedio',
    titulo: 'Valor del inventario',
    descripcion: 'Calcula el valor total del inventario de cada producto (precio × stock), redondeado a 2 decimales. Ordena de mayor a menor.',
    objetivo: 'Usar operaciones aritméticas y ROUND para calcular valores derivados.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['nombre','valor_inventario'],
      filas: [['Laptop Pro',25999.8],['Tablet',9999.75],['Webcam',7999.0],['Monitor',7499.85],['Teclado',7199.2],['Mouse',4498.5]],
    },
    solucionOficial: 'SELECT nombre, ROUND(precio * stock, 2) AS valor_inventario FROM productos ORDER BY valor_inventario DESC;',
    solucionesAlternativas: [],
    explicacion: 'precio * stock calcula el valor. ROUND(..., 2) lo redondea a 2 decimales. ORDER BY valor_inventario DESC ordena de mayor a menor.',
    pistas: ['precio * stock para el valor total', 'ROUND(precio * stock, 2) para redondear', 'ORDER BY valor_inventario DESC'],
    retroalimentacionError: 'ROUND(precio * stock, 2) AS valor_inventario + ORDER BY valor_inventario DESC',
  },
  {
    id: 'in-b-016',
    nivel: 'intermedio',
    titulo: 'Antigüedad con STRFTIME',
    descripcion: 'Muestra cada empleado y los años que lleva en la empresa (diferencia de año entre 2024-12-31 y su fecha de contrato). Ordena por antigüedad descendente.',
    objetivo: 'Calcular diferencias entre fechas usando STRFTIME.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['nombre','anios_empresa'],
      filas: [['Laura',6],['Andrés',5],['Carlos',5],['Elena',4],['María',4],['Miguel',4],['Ana',3],['Sofía',3],['Javier',2],['Pedro',2]],
    },
    solucionOficial: "SELECT nombre, (STRFTIME('%Y', '2024-12-31') - STRFTIME('%Y', fecha_contrato)) AS anios_empresa FROM empleados ORDER BY anios_empresa DESC, nombre;",
    solucionesAlternativas: [],
    explicacion: "STRFTIME('%Y', fecha) extrae solo el año. La resta entre años da la antigüedad aproximada. Esta técnica ignora el mes exacto — es un cálculo simplificado.",
    pistas: ["STRFTIME('%Y', '2024-12-31') da el año de referencia: '2024'", "STRFTIME('%Y', fecha_contrato) da el año de contratación", 'La resta de ambos da los años en la empresa'],
    retroalimentacionError: "STRFTIME('%Y','2024-12-31') - STRFTIME('%Y', fecha_contrato) AS anios_empresa",
  },
  {
    id: 'in-b-017',
    nivel: 'intermedio',
    titulo: 'Contrataciones por año',
    descripcion: 'Muestra cuántos empleados fueron contratados en cada año.',
    objetivo: 'Combinar STRFTIME con GROUP BY para análisis temporal.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['anio','contratados'],
      filas: [['2018',1],['2019',2],['2020',3],['2021',2],['2022',2]],
    },
    solucionOficial: "SELECT STRFTIME('%Y', fecha_contrato) AS anio, COUNT(*) AS contratados FROM empleados GROUP BY anio ORDER BY anio;",
    solucionesAlternativas: [],
    explicacion: "STRFTIME('%Y', fecha_contrato) extrae el año. GROUP BY anio agrupa por año. COUNT(*) cuenta los empleados de cada año.",
    pistas: ["STRFTIME('%Y', fecha_contrato) AS anio", 'GROUP BY anio', 'COUNT(*) AS contratados + ORDER BY anio'],
    retroalimentacionError: "GROUP BY STRFTIME('%Y', fecha_contrato)",
  },
  {
    id: 'in-b-018',
    nivel: 'intermedio',
    titulo: 'Ventas por empleado y mes',
    descripcion: 'Muestra el nombre del empleado, el mes (YYYY-MM) y el total de ventas de ese mes, para los empleados que han vendido. Ordena por mes y total descendente.',
    objetivo: 'Combinar JOIN con STRFTIME y GROUP BY para análisis mensual.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['empleado','mes','total'],
      filas: [['Carlos','2024-01',2599.98],['María','2024-01',419.92],['Carlos','2024-02',1599.96],['Laura','2024-02',1299.99],['Ana','2024-02',499.99],['María','2024-03',299.9],['Pedro','2024-03',159.98]],
    },
    solucionOficial: "SELECT e.nombre AS empleado, STRFTIME('%Y-%m', v.fecha) AS mes, ROUND(SUM(v.monto), 2) AS total FROM empleados e INNER JOIN ventas v ON e.id = v.empleado_id GROUP BY e.id, e.nombre, mes ORDER BY mes, total DESC;",
    solucionesAlternativas: [],
    explicacion: "STRFTIME('%Y-%m', v.fecha) extrae año-mes. GROUP BY incluye el empleado y el mes. SUM acumula las ventas de cada combinación empleado-mes.",
    pistas: ["STRFTIME('%Y-%m', v.fecha) AS mes", 'GROUP BY e.id, e.nombre, mes', 'SUM(v.monto) + ORDER BY mes, total DESC'],
    retroalimentacionError: "INNER JOIN + GROUP BY e.id, e.nombre, STRFTIME('%Y-%m', v.fecha)",
  },
  {
    id: 'in-b-019',
    nivel: 'intermedio',
    titulo: 'Categoría salarial con CASE',
    descripcion: 'Clasifica cada empleado como "Junior" (< 50000), "Senior" (50000-64999) o "Principal" (65000+), y ordena de mayor a menor salario.',
    objetivo: 'Usar CASE WHEN para clasificar registros en categorías.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['nombre','salario','categoria'],
      filas: [['Laura',70000,'Principal'],['Carlos',65000,'Principal'],['Miguel',60000,'Senior'],['Andrés',55000,'Senior'],['Sofía',52000,'Senior'],['Elena',50000,'Senior'],['Ana',48000,'Junior'],['María',45000,'Junior'],['Javier',44000,'Junior'],['Pedro',42000,'Junior']],
    },
    solucionOficial: "SELECT nombre, salario, CASE WHEN salario < 50000 THEN 'Junior' WHEN salario < 65000 THEN 'Senior' ELSE 'Principal' END AS categoria FROM empleados ORDER BY salario DESC;",
    solucionesAlternativas: [],
    explicacion: 'CASE evalúa de arriba hacia abajo. El primer WHEN que se cumple define el resultado. Carlos (65000) no cumple ni < 50000 ni < 65000 (es igual, no menor), así que cae en ELSE = Principal.',
    pistas: ["CASE WHEN salario < 50000 THEN 'Junior'", "WHEN salario < 65000 THEN 'Senior'", "ELSE 'Principal' END AS categoria"],
    retroalimentacionError: 'CASE evalúa las condiciones en orden — el primer WHEN verdadero gana',
  },
  {
    id: 'in-b-020',
    nivel: 'intermedio',
    titulo: 'Bono por departamento con CASE',
    descripcion: 'Calcula el bono de cada empleado: Ventas 10%, Tecnología 8%, otros 5%. Muestra nombre, departamento, salario y bono (redondeado).',
    objetivo: 'Usar CASE con valores de columna para aplicar reglas diferentes por grupo.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['nombre','departamento','salario','bono'],
      filas: [['María','Ventas',45000,4500],['Carlos','Tecnología',65000,5200],['Ana','RRHH',48000,2400],['Pedro','Ventas',42000,4200],['Laura','Tecnología',70000,5600],['Miguel','Tecnología',60000,4800],['Sofía','Marketing',52000,2600],['Javier','Ventas',44000,4400],['Elena','RRHH',50000,2500],['Andrés','Marketing',55000,2750]],
    },
    solucionOficial: "SELECT nombre, departamento, salario, ROUND(CASE departamento WHEN 'Ventas' THEN salario * 0.10 WHEN 'Tecnología' THEN salario * 0.08 ELSE salario * 0.05 END) AS bono FROM empleados ORDER BY id;",
    solucionesAlternativas: [],
    explicacion: "CASE departamento WHEN 'Ventas' evalúa si departamento = 'Ventas'. Esta sintaxis simplificada es equivalente a CASE WHEN departamento = 'Ventas'. ROUND redondea al entero más cercano.",
    pistas: ["CASE departamento WHEN 'Ventas' THEN salario * 0.10", "WHEN 'Tecnología' THEN salario * 0.08", 'ELSE salario * 0.05 END — envuelto en ROUND()'],
    retroalimentacionError: "CASE departamento WHEN 'Ventas' THEN ... — el CASE compara la columna con cada WHEN",
  },
  {
    id: 'in-b-021',
    nivel: 'intermedio',
    titulo: 'Pivot manual con CASE',
    descripcion: 'Cuenta cuántos empleados hay en cada rango salarial: Bajo (< 50000), Medio (50000–65000), Alto (> 65000). Todo en una sola fila.',
    objetivo: 'Usar SUM + CASE para crear un pivot: contar por categoría en columnas.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['bajo','medio','alto'],
      filas: [[4,5,1]],
    },
    solucionOficial: 'SELECT SUM(CASE WHEN salario < 50000 THEN 1 ELSE 0 END) AS bajo, SUM(CASE WHEN salario BETWEEN 50000 AND 65000 THEN 1 ELSE 0 END) AS medio, SUM(CASE WHEN salario > 65000 THEN 1 ELSE 0 END) AS alto FROM empleados;',
    solucionesAlternativas: [],
    explicacion: 'Cada SUM(CASE...) cuenta los empleados que cumplen una condición. Este patrón "SUM + CASE" transforma filas en columnas (pivot manual).',
    pistas: ['SUM(CASE WHEN salario < 50000 THEN 1 ELSE 0 END) AS bajo', 'Repite el patrón para cada rango con BETWEEN', 'Todo en un solo SELECT sin GROUP BY'],
    retroalimentacionError: 'SUM(CASE WHEN condición THEN 1 ELSE 0 END) — el CASE dentro del SUM actúa como contador condicional',
  },
  {
    id: 'in-b-022',
    nivel: 'intermedio',
    titulo: 'Subconsulta correlacionada',
    descripcion: 'Muestra los empleados que ganan MÁS que el promedio de su propio departamento.',
    objetivo: 'Usar una subconsulta correlacionada que referencia la consulta externa.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['nombre','departamento','salario'],
      filas: [['Elena','RRHH',50000],['Andrés','Marketing',55000],['Laura','Tecnología',70000],['María','Ventas',45000],['Javier','Ventas',44000]],
    },
    solucionOficial: 'SELECT e1.nombre, e1.departamento, e1.salario FROM empleados e1 WHERE e1.salario > (SELECT AVG(e2.salario) FROM empleados e2 WHERE e2.departamento = e1.departamento) ORDER BY e1.departamento, e1.salario DESC;',
    solucionesAlternativas: [],
    explicacion: 'La subconsulta usa e1.departamento (de la fila actual de la consulta externa) para calcular el promedio solo de ese departamento. Por eso se llama "correlacionada": depende de la fila externa.',
    pistas: ['WHERE e1.salario > (SELECT AVG(e2.salario) FROM empleados e2 WHERE e2.departamento = e1.departamento)', 'La subconsulta referencia e1.departamento — por eso se re-ejecuta para cada fila', 'Alias distintos: e1 para externa, e2 para interna'],
    retroalimentacionError: 'La subconsulta debe usar e2.departamento = e1.departamento para correlacionarla con la fila externa',
  },
  {
    id: 'in-b-023',
    nivel: 'intermedio',
    titulo: 'Subconsulta en SELECT',
    descripcion: 'Para cada empleado, muestra su nombre, salario y la diferencia con el salario máximo de toda la empresa.',
    objetivo: 'Usar una subconsulta escalar dentro del SELECT para calcular una columna derivada.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['nombre','salario','diferencia_con_maximo'],
      filas: [['Laura',70000,0],['Carlos',65000,5000],['Miguel',60000,10000],['Andrés',55000,15000],['Sofía',52000,18000],['Elena',50000,20000],['Ana',48000,22000],['María',45000,25000],['Javier',44000,26000],['Pedro',42000,28000]],
    },
    solucionOficial: 'SELECT nombre, salario, (SELECT MAX(salario) FROM empleados) - salario AS diferencia_con_maximo FROM empleados ORDER BY diferencia_con_maximo;',
    solucionesAlternativas: [],
    explicacion: 'La subconsulta (SELECT MAX(salario) FROM empleados) devuelve 70000. Ese valor se resta del salario de cada fila. Laura tiene diferencia 0 porque ella ES el máximo.',
    pistas: ['La subconsulta escalar va dentro del SELECT: (SELECT MAX(salario) FROM empleados)', 'Resta la subconsulta del salario de la fila actual', 'ORDER BY diferencia_con_maximo para ver el ranking'],
    retroalimentacionError: '(SELECT MAX(salario) FROM empleados) - salario AS diferencia_con_maximo — la subconsulta va entre paréntesis en el SELECT',
  },
  {
    id: 'in-b-024',
    nivel: 'intermedio',
    titulo: 'NOT IN: empleados sin ventas',
    descripcion: 'Muestra los empleados que no han realizado ninguna venta.',
    objetivo: 'Usar NOT IN con subconsulta para encontrar registros sin presencia en otra tabla.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['nombre'],
      filas: [['Andrés'],['Elena'],['Javier'],['Miguel'],['Sofía']],
    },
    solucionOficial: 'SELECT nombre FROM empleados WHERE id NOT IN (SELECT DISTINCT empleado_id FROM ventas) ORDER BY nombre;',
    solucionesAlternativas: ['SELECT e.nombre FROM empleados e LEFT JOIN ventas v ON e.id = v.empleado_id WHERE v.id IS NULL ORDER BY e.nombre;'],
    explicacion: 'La subconsulta devuelve los IDs de empleados que SÍ tienen ventas. NOT IN excluye esos IDs, devolviendo solo los que nunca vendieron.',
    pistas: ['SELECT DISTINCT empleado_id FROM ventas — los que SÍ han vendido', 'WHERE id NOT IN (...) — excluye los que están en la lista', 'ORDER BY nombre'],
    retroalimentacionError: 'WHERE id NOT IN (SELECT DISTINCT empleado_id FROM ventas)',
  },
  {
    id: 'in-b-025',
    nivel: 'intermedio',
    titulo: 'UNION con etiqueta de tipo',
    descripcion: 'Combina en una sola lista los departamentos de empleados y las categorías de productos, etiquetando cada fila con su tipo. Sin duplicados, ordenado.',
    objetivo: 'Usar UNION para combinar resultados de dos tablas distintas.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['nombre','tipo'],
      filas: [['Electrónica','Categoría'],['Periféricos','Categoría'],['Marketing','Departamento'],['RRHH','Departamento'],['Tecnología','Departamento'],['Ventas','Departamento']],
    },
    solucionOficial: "SELECT DISTINCT departamento AS nombre, 'Departamento' AS tipo FROM empleados UNION SELECT DISTINCT categoria, 'Categoría' AS tipo FROM productos ORDER BY tipo, nombre;",
    solucionesAlternativas: [],
    explicacion: "UNION combina dos SELECT con la misma estructura de columnas. Elimina duplicados automáticamente. Las cadenas literales 'Departamento' y 'Categoría' añaden una etiqueta a cada fila.",
    pistas: ["Primera SELECT: SELECT DISTINCT departamento AS nombre, 'Departamento' AS tipo", "Segunda SELECT: SELECT DISTINCT categoria, 'Categoría' AS tipo", 'UNION (sin ALL) para eliminar duplicados + ORDER BY tipo, nombre'],
    retroalimentacionError: "UNION requiere el mismo número de columnas en ambos SELECT — añade la etiqueta literal 'Departamento' y 'Categoría'",
  },
  {
    id: 'in-b-026',
    nivel: 'intermedio',
    titulo: 'UNION: departamentos en ambos extremos',
    descripcion: 'Muestra los departamentos que tienen empleados con salario < 50000 O empleados con salario > 60000, sin repetir departamentos.',
    objetivo: 'Usar UNION para reunir dos conjuntos y eliminar duplicados.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['departamento'],
      filas: [['RRHH'],['Tecnología'],['Ventas']],
    },
    solucionOficial: 'SELECT departamento FROM empleados WHERE salario < 50000 UNION SELECT departamento FROM empleados WHERE salario > 60000 ORDER BY departamento;',
    solucionesAlternativas: [],
    explicacion: 'Primera SELECT: RRHH (Ana 48000), Ventas (María, Pedro, Javier). Segunda SELECT: Tecnología (Carlos, Laura, Miguel). UNION elimina duplicados y combina: RRHH, Tecnología, Ventas.',
    pistas: ['Primera SELECT: WHERE salario < 50000', 'Segunda SELECT: WHERE salario > 60000', 'UNION (sin ALL) elimina duplicados automáticamente'],
    retroalimentacionError: 'UNION (sin ALL) para unir y deduplicar — UNION ALL mantendría los repetidos',
  },
  {
    id: 'in-b-027',
    nivel: 'intermedio',
    titulo: 'CTE para productos más vendidos',
    descripcion: 'Usa una CTE para calcular el total vendido por producto. Luego muestra solo los productos con más de 500 en ventas.',
    objetivo: 'Usar WITH para pre-calcular un agregado y filtrarlo después.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['nombre','total'],
      filas: [['Laptop Pro',3899.97],['Tablet',1599.96]],
    },
    solucionOficial: 'WITH ventas_prod AS (SELECT producto_id, SUM(monto) AS total FROM ventas GROUP BY producto_id)\nSELECT p.nombre, vp.total FROM ventas_prod vp INNER JOIN productos p ON vp.producto_id = p.id WHERE vp.total > 500 ORDER BY vp.total DESC;',
    solucionesAlternativas: [],
    explicacion: 'La CTE agrupa las ventas por producto. La consulta final une con productos para obtener el nombre y filtra los que superan 500. Mouse (449.85) queda fuera.',
    pistas: ['WITH ventas_prod AS (SELECT producto_id, SUM(monto) AS total FROM ventas GROUP BY producto_id)', 'INNER JOIN productos p ON vp.producto_id = p.id', 'WHERE vp.total > 500 + ORDER BY vp.total DESC'],
    retroalimentacionError: 'WITH ventas_prod AS (...) luego JOIN con productos y WHERE vp.total > 500',
  },
  {
    id: 'in-b-028',
    nivel: 'intermedio',
    titulo: 'CTE + JOIN con promedio de departamento',
    descripcion: 'Usa una CTE para calcular el salario promedio por departamento. Luego únela con empleados para mostrar cada empleado y el promedio de su departamento.',
    objetivo: 'Usar una CTE como tabla temporal que se une con otra tabla.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['nombre','departamento','salario','prom_depto'],
      filas: [['Elena','RRHH',50000,49000],['Ana','RRHH',48000,49000],['Andrés','Marketing',55000,53500],['Sofía','Marketing',52000,53500],['Laura','Tecnología',70000,65000],['Carlos','Tecnología',65000,65000],['Miguel','Tecnología',60000,65000],['María','Ventas',45000,43666.67],['Javier','Ventas',44000,43666.67],['Pedro','Ventas',42000,43666.67]],
    },
    solucionOficial: 'WITH prom_depto AS (SELECT departamento, ROUND(AVG(salario), 2) AS promedio FROM empleados GROUP BY departamento)\nSELECT e.nombre, e.departamento, e.salario, pd.promedio AS prom_depto FROM empleados e INNER JOIN prom_depto pd ON e.departamento = pd.departamento ORDER BY e.departamento, e.salario DESC;',
    solucionesAlternativas: [],
    explicacion: 'La CTE calcula un promedio por departamento. La consulta externa hace JOIN usando el campo departamento (texto) como clave. ROUND(AVG(45000+42000+44000)/3, 2) = 43666.67 para Ventas.',
    pistas: ['WITH prom_depto AS (SELECT departamento, ROUND(AVG(salario),2) AS promedio FROM empleados GROUP BY departamento)', 'INNER JOIN prom_depto pd ON e.departamento = pd.departamento', 'ORDER BY e.departamento, e.salario DESC'],
    retroalimentacionError: 'CTE calcula promedios por departamento. Luego JOIN usando departamento como clave de unión',
  },
  {
    id: 'in-b-029',
    nivel: 'intermedio',
    titulo: 'Múltiples CTEs',
    descripcion: 'Define dos CTEs: "altos" (empleados con salario > 55000) y "vendedores_grandes" (empleados con ventas individuales > 500). Muestra los que aparecen en ambas.',
    objetivo: 'Encadenar múltiples CTEs en una sola cláusula WITH.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['nombre'],
      filas: [['Carlos'],['Laura']],
    },
    solucionOficial: 'WITH altos AS (SELECT id, nombre FROM empleados WHERE salario > 55000), vendedores_grandes AS (SELECT DISTINCT empleado_id FROM ventas WHERE monto > 500)\nSELECT a.nombre FROM altos a INNER JOIN vendedores_grandes vg ON a.id = vg.empleado_id ORDER BY a.nombre;',
    solucionesAlternativas: [],
    explicacion: 'Las dos CTEs se separan con coma dentro del mismo WITH. "altos": Carlos, Laura, Miguel. "vendedores_grandes": Carlos, Laura (ventas > 500). La intersección: Carlos y Laura.',
    pistas: ['WITH cte1 AS (...), cte2 AS (...) — ambas en el mismo WITH separadas por coma', 'altos: WHERE salario > 55000', 'vendedores_grandes: WHERE monto > 500 — luego INNER JOIN entre ambas'],
    retroalimentacionError: 'WITH cte1 AS (...), cte2 AS (...) — múltiples CTEs separadas por coma en el mismo WITH',
  },
  {
    id: 'in-b-030',
    nivel: 'intermedio',
    titulo: 'CTE + CASE para clasificar vendedores',
    descripcion: 'Usa una CTE que cuenta las ventas por empleado (incluyendo los sin ventas). Luego clasifica: "Activo" (> 1 venta), "Básico" (1 venta), "Sin ventas" (0).',
    objetivo: 'Combinar CTE con LEFT JOIN, COUNT y CASE WHEN.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['nombre','num_ventas','tipo'],
      filas: [['María',3,'Activo'],['Carlos',2,'Activo'],['Ana',1,'Básico'],['Laura',1,'Básico'],['Pedro',1,'Básico'],['Andrés',0,'Sin ventas'],['Elena',0,'Sin ventas'],['Javier',0,'Sin ventas'],['Miguel',0,'Sin ventas'],['Sofía',0,'Sin ventas']],
    },
    solucionOficial: "WITH conteo AS (SELECT e.id, e.nombre, COUNT(v.id) AS num_ventas FROM empleados e LEFT JOIN ventas v ON e.id = v.empleado_id GROUP BY e.id, e.nombre)\nSELECT nombre, num_ventas, CASE WHEN num_ventas > 1 THEN 'Activo' WHEN num_ventas = 1 THEN 'Básico' ELSE 'Sin ventas' END AS tipo FROM conteo ORDER BY num_ventas DESC, nombre;",
    solucionesAlternativas: [],
    explicacion: 'La CTE usa LEFT JOIN para incluir todos los empleados y COUNT(v.id) para contar 0 cuando no hay ventas. El CASE en la consulta final clasifica según el conteo.',
    pistas: ['CTE con LEFT JOIN para incluir empleados sin ventas', 'COUNT(v.id) en vez de COUNT(*) para contar 0 cuando no hay ventas', "CASE WHEN num_ventas > 1 THEN 'Activo' WHEN num_ventas = 1 THEN 'Básico' ELSE 'Sin ventas' END"],
    retroalimentacionError: 'LEFT JOIN + COUNT(v.id) para 0 cuando no hay ventas, luego CASE sobre num_ventas',
  },
  {
    id: 'in-b-031',
    nivel: 'intermedio',
    titulo: 'INSERT con SELECT',
    descripcion: 'Crea una tabla resumen_dept y llénala con el total de empleados y el salario promedio de cada departamento usando INSERT … SELECT. Luego muestra su contenido.',
    objetivo: 'Usar INSERT INTO … SELECT para poblar una tabla con datos calculados.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['departamento','total_empleados','salario_promedio'],
      filas: [['Marketing',2,53500],['RRHH',2,49000],['Tecnología',3,65000],['Ventas',3,43666.67]],
    },
    solucionOficial: 'CREATE TABLE resumen_dept (departamento TEXT, total_empleados INTEGER, salario_promedio REAL);\nINSERT INTO resumen_dept SELECT departamento, COUNT(*), ROUND(AVG(salario), 2) FROM empleados GROUP BY departamento;\nSELECT * FROM resumen_dept ORDER BY departamento;',
    solucionesAlternativas: [],
    explicacion: 'INSERT INTO tabla SELECT … es equivalente a INSERT con VALUES pero usando el resultado de una consulta. Se pueden insertar muchas filas de una vez.',
    pistas: ['CREATE TABLE resumen_dept (departamento TEXT, total_empleados INTEGER, salario_promedio REAL)', 'INSERT INTO resumen_dept SELECT departamento, COUNT(*), ROUND(AVG(salario),2) FROM empleados GROUP BY departamento', 'SELECT * FROM resumen_dept ORDER BY departamento'],
    retroalimentacionError: 'INSERT INTO tabla SELECT ... — sin VALUES, directamente el resultado de la consulta',
  },
  {
    id: 'in-b-032',
    nivel: 'intermedio',
    titulo: 'UPDATE con WHERE',
    descripcion: 'Aumenta en 3000 el salario de todos los empleados de RRHH. Luego muestra los empleados de ese departamento.',
    objetivo: 'Usar UPDATE con SET calculado y WHERE para limitar el efecto.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['nombre','salario'],
      filas: [['Ana',51000],['Elena',53000]],
    },
    solucionOficial: "UPDATE empleados SET salario = salario + 3000 WHERE departamento = 'RRHH';\nSELECT nombre, salario FROM empleados WHERE departamento = 'RRHH' ORDER BY nombre;",
    solucionesAlternativas: [],
    explicacion: "SET salario = salario + 3000 calcula el nuevo valor usando el actual. WHERE departamento = 'RRHH' limita la actualización solo a Ana (48000→51000) y Elena (50000→53000).",
    pistas: ["UPDATE empleados SET salario = salario + 3000 WHERE departamento = 'RRHH'", 'Luego SELECT para verificar el resultado', 'ORDER BY nombre'],
    retroalimentacionError: "UPDATE empleados SET salario = salario + 3000 WHERE departamento = 'RRHH'",
  },
  {
    id: 'in-b-033',
    nivel: 'intermedio',
    titulo: 'UPDATE calculado por categoría',
    descripcion: 'Aplica el IVA del 21% al precio de todos los productos de la categoría "Periféricos" (redondear a 2 decimales). Luego muéstralos.',
    objetivo: 'Usar UPDATE con un cálculo aritmético en SET.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['nombre','precio'],
      filas: [['Mouse',36.29],['Teclado',108.88],['Webcam',96.79]],
    },
    solucionOficial: "UPDATE productos SET precio = ROUND(precio * 1.21, 2) WHERE categoria = 'Periféricos';\nSELECT nombre, precio FROM productos WHERE categoria = 'Periféricos' ORDER BY nombre;",
    solucionesAlternativas: [],
    explicacion: "Mouse: ROUND(29.99 * 1.21, 2) = 36.29. Teclado: ROUND(89.99 * 1.21, 2) = 108.88. Webcam: ROUND(79.99 * 1.21, 2) = 96.79. WHERE limita a Periféricos.",
    pistas: ["UPDATE productos SET precio = ROUND(precio * 1.21, 2) WHERE categoria = 'Periféricos'", 'precio * 1.21 suma el 21%', "SELECT WHERE categoria = 'Periféricos' ORDER BY nombre para verificar"],
    retroalimentacionError: "UPDATE productos SET precio = ROUND(precio * 1.21, 2) WHERE categoria = 'Periféricos'",
  },
  {
    id: 'in-b-034',
    nivel: 'intermedio',
    titulo: 'DELETE con subconsulta',
    descripcion: 'Elimina las ventas realizadas por empleados de Tecnología. Luego muestra cuántas ventas quedan.',
    objetivo: 'Usar DELETE con una subconsulta en WHERE para filtrar indirectamente.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['ventas_restantes'],
      filas: [[5]],
    },
    solucionOficial: "DELETE FROM ventas WHERE empleado_id IN (SELECT id FROM empleados WHERE departamento = 'Tecnología');\nSELECT COUNT(*) AS ventas_restantes FROM ventas;",
    solucionesAlternativas: [],
    explicacion: "La subconsulta devuelve los IDs de empleados de Tecnología (Carlos=2, Laura=5). DELETE elimina las ventas con esos empleado_id: ventas 2, 5, 6. Quedan 8 - 3 = 5 ventas.",
    pistas: ["DELETE FROM ventas WHERE empleado_id IN (SELECT id FROM empleados WHERE departamento = 'Tecnología')", 'La subconsulta identifica los empleados cuyas ventas borrar', 'SELECT COUNT(*) AS ventas_restantes para verificar'],
    retroalimentacionError: "DELETE ... WHERE empleado_id IN (SELECT id FROM empleados WHERE departamento = 'Tecnología')",
  },
  {
    id: 'in-b-035',
    nivel: 'intermedio',
    titulo: 'Salario mensual y bono',
    descripcion: 'Para cada empleado, muestra su salario anual, salario mensual (redondeado a 2 decimales) y el bono de rendimiento (5% del salario anual, redondeado). Ordena por salario descendente.',
    objetivo: 'Combinar varias operaciones aritméticas y ROUND en un SELECT.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['nombre','salario','mensual','bono'],
      filas: [['Laura',70000,5833.33,3500],['Carlos',65000,5416.67,3250],['Miguel',60000,5000,3000],['Andrés',55000,4583.33,2750],['Sofía',52000,4333.33,2600],['Elena',50000,4166.67,2500],['Ana',48000,4000,2400],['María',45000,3750,2250],['Javier',44000,3666.67,2200],['Pedro',42000,3500,2100]],
    },
    solucionOficial: 'SELECT nombre, salario, ROUND(salario / 12.0, 2) AS mensual, ROUND(salario * 0.05) AS bono FROM empleados ORDER BY salario DESC;',
    solucionesAlternativas: [],
    explicacion: 'salario / 12.0 (no 12) asegura división decimal. ROUND(..., 2) redondea a 2 decimales. ROUND(salario * 0.05) redondea al entero más cercano.',
    pistas: ['salario / 12.0 para el mensual (usa 12.0 no 12 para evitar división entera)', 'ROUND(salario / 12.0, 2) AS mensual', 'ROUND(salario * 0.05) AS bono'],
    retroalimentacionError: 'Usa 12.0 no 12 para que la división sea decimal. ROUND(..., 2) para mensual, ROUND(...) para bono',
  },
  {
    id: 'in-b-036',
    nivel: 'intermedio',
    titulo: 'Antigüedad categorizada con CASE + STRFTIME',
    descripcion: 'Clasifica a cada empleado como "Veterano" (antes de 2020), "Establecido" (2020-2021) o "Nuevo" (2022+), usando STRFTIME y CASE. Ordena por categoría y fecha.',
    objetivo: 'Combinar STRFTIME para extraer año con CASE WHEN para categorizar.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['nombre','fecha_contrato','categoria'],
      filas: [['María','2020-03-15','Establecido'],['Miguel','2020-07-15','Establecido'],['Elena','2020-09-30','Establecido'],['Ana','2021-01-10','Establecido'],['Sofía','2021-04-01','Establecido'],['Javier','2022-02-14','Nuevo'],['Pedro','2022-08-20','Nuevo'],['Laura','2018-11-05','Veterano'],['Carlos','2019-06-01','Veterano'],['Andrés','2019-12-01','Veterano']],
    },
    solucionOficial: "SELECT nombre, fecha_contrato, CASE WHEN STRFTIME('%Y', fecha_contrato) < '2020' THEN 'Veterano' WHEN STRFTIME('%Y', fecha_contrato) <= '2021' THEN 'Establecido' ELSE 'Nuevo' END AS categoria FROM empleados ORDER BY categoria, fecha_contrato;",
    solucionesAlternativas: [],
    explicacion: "STRFTIME('%Y', fecha_contrato) devuelve el año como texto (p.ej. '2018'). Las comparaciones de texto funcionan correctamente para años en formato YYYY.",
    pistas: ["STRFTIME('%Y', fecha_contrato) extrae el año como texto", "CASE WHEN ... < '2020' THEN 'Veterano' WHEN ... <= '2021' THEN 'Establecido' ELSE 'Nuevo' END", 'ORDER BY categoria, fecha_contrato'],
    retroalimentacionError: "CASE WHEN STRFTIME('%Y', fecha_contrato) < '2020' ... — compara strings de año",
  },
  {
    id: 'in-b-037',
    nivel: 'intermedio',
    titulo: 'Formato de fecha personalizado',
    descripcion: 'Muestra las ventas con la fecha en formato DD/MM/YYYY.',
    objetivo: "Usar STRFTIME con un formato personalizado para presentar fechas.",
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['id','fecha_formato','monto'],
      filas: [[1,'10/01/2024',149.95],[2,'15/01/2024',2599.98],[3,'20/01/2024',269.97],[4,'05/02/2024',499.99],[5,'10/02/2024',1599.96],[6,'20/02/2024',1299.99],[7,'01/03/2024',299.9],[8,'10/03/2024',159.98]],
    },
    solucionOficial: "SELECT id, STRFTIME('%d/%m/%Y', fecha) AS fecha_formato, monto FROM ventas ORDER BY fecha;",
    solucionesAlternativas: [],
    explicacion: "STRFTIME permite cualquier formato de salida. '%d/%m/%Y' da día/mes/año en lugar del ISO YYYY-MM-DD. El almacenamiento no cambia, solo la presentación.",
    pistas: ["STRFTIME('%d/%m/%Y', fecha) AS fecha_formato", 'ORDER BY fecha (el original, no el formateado)', 'La función no cambia cómo se almacena la fecha'],
    retroalimentacionError: "STRFTIME('%d/%m/%Y', fecha) — los especificadores: %d día, %m mes, %Y año de 4 dígitos",
  },
  {
    id: 'in-b-038',
    nivel: 'intermedio',
    titulo: 'COALESCE para NULLs',
    descripcion: 'Para cada empleado, muestra su nombre y el total de ventas que ha realizado. Para los sin ventas, muestra 0 en lugar de NULL.',
    objetivo: 'Usar COALESCE para reemplazar NULL por un valor por defecto.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['nombre','total_ventas'],
      filas: [['Carlos',4199.94],['Laura',1299.99],['María',719.82],['Ana',499.99],['Pedro',159.98],['Andrés',0],['Elena',0],['Javier',0],['Miguel',0],['Sofía',0]],
    },
    solucionOficial: 'SELECT e.nombre, COALESCE(SUM(v.monto), 0) AS total_ventas FROM empleados e LEFT JOIN ventas v ON e.id = v.empleado_id GROUP BY e.id, e.nombre ORDER BY total_ventas DESC, e.nombre;',
    solucionesAlternativas: [],
    explicacion: 'LEFT JOIN incluye todos los empleados. Para los sin ventas, SUM(v.monto) devuelve NULL. COALESCE(NULL, 0) lo reemplaza por 0.',
    pistas: ['LEFT JOIN para incluir a todos', 'SUM(v.monto) devuelve NULL cuando no hay ventas', 'COALESCE(SUM(v.monto), 0) convierte NULL en 0'],
    retroalimentacionError: 'COALESCE(SUM(v.monto), 0) — COALESCE devuelve el primer valor no NULL de su lista',
  },
  {
    id: 'in-b-039',
    nivel: 'intermedio',
    titulo: 'Subconsulta en FROM',
    descripcion: 'Calcula el promedio de los totales de venta por empleado (primero agrega por empleado, luego promedia esos totales).',
    objetivo: 'Usar una subconsulta en FROM como tabla derivada.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['promedio_por_empleado'],
      filas: [[1375.944]],
    },
    solucionOficial: 'SELECT ROUND(AVG(total), 3) AS promedio_por_empleado FROM (SELECT empleado_id, SUM(monto) AS total FROM ventas GROUP BY empleado_id);',
    solucionesAlternativas: [],
    explicacion: 'La subconsulta en FROM (tabla derivada) calcula el total por empleado: Carlos(4199.94), María(719.82), Ana(499.99), Pedro(159.98), Laura(1299.99). El SELECT externo promedia esos 5 totales.',
    pistas: ['La subconsulta dentro de FROM: (SELECT empleado_id, SUM(monto) AS total FROM ventas GROUP BY empleado_id)', 'El SELECT externo hace AVG sobre esa tabla derivada', 'No necesitas alias para la subconsulta en este caso'],
    retroalimentacionError: 'SELECT AVG(total) FROM (SELECT empleado_id, SUM(monto) AS total FROM ventas GROUP BY empleado_id)',
  },
  {
    id: 'in-b-040',
    nivel: 'intermedio',
    titulo: 'UNION + ORDER BY',
    descripcion: 'Crea una lista combinada: nombres de empleados de Ventas y nombres de productos de Electrónica, con su tipo. Ordena alfabéticamente.',
    objetivo: 'Combinar UNION con ORDER BY al final para ordenar el resultado completo.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['nombre','tipo'],
      filas: [['Javier','Empleado'],['Laptop Pro','Producto'],['María','Empleado'],['Monitor','Producto'],['Pedro','Empleado'],['Tablet','Producto']],
    },
    solucionOficial: "SELECT nombre, 'Empleado' AS tipo FROM empleados WHERE departamento = 'Ventas' UNION SELECT nombre, 'Producto' AS tipo FROM productos WHERE categoria = 'Electrónica' ORDER BY nombre;",
    solucionesAlternativas: [],
    explicacion: "ORDER BY al final de un UNION ordena el resultado completo combinado. No se puede poner ORDER BY dentro de cada SELECT individual cuando se usa UNION.",
    pistas: ["Primera SELECT: WHERE departamento = 'Ventas'", "Segunda SELECT: WHERE categoria = 'Electrónica'", 'ORDER BY nombre al final (después del UNION, no dentro de los SELECT)'],
    retroalimentacionError: 'El ORDER BY va al final de todo el UNION, no dentro de cada SELECT',
  },
  {
    id: 'in-b-041',
    nivel: 'intermedio',
    titulo: 'CTE + CASE para clasificar rendimiento',
    descripcion: 'Usa una CTE con el total de ventas por empleado (incluyendo 0). Clasifica como "Alto" (> 1000), "Medio" (500-1000) o "Bajo" (< 500). Ordena por total descendente.',
    objetivo: 'Combinar CTE, COALESCE y CASE WHEN en un análisis completo.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['nombre','total','rendimiento'],
      filas: [['Carlos',4199.94,'Alto'],['Laura',1299.99,'Alto'],['María',719.82,'Medio'],['Ana',499.99,'Bajo'],['Pedro',159.98,'Bajo'],['Andrés',0,'Bajo'],['Elena',0,'Bajo'],['Javier',0,'Bajo'],['Miguel',0,'Bajo'],['Sofía',0,'Bajo']],
    },
    solucionOficial: "WITH totales AS (SELECT e.nombre, COALESCE(SUM(v.monto), 0) AS total FROM empleados e LEFT JOIN ventas v ON e.id = v.empleado_id GROUP BY e.id, e.nombre)\nSELECT nombre, total, CASE WHEN total > 1000 THEN 'Alto' WHEN total >= 500 THEN 'Medio' ELSE 'Bajo' END AS rendimiento FROM totales ORDER BY total DESC;",
    solucionesAlternativas: [],
    explicacion: 'La CTE usa LEFT JOIN + COALESCE para obtener el total de cada empleado (0 para los sin ventas). El CASE en la consulta final clasifica según ese total.',
    pistas: ['CTE con LEFT JOIN + COALESCE(SUM(v.monto), 0) AS total', "CASE WHEN total > 1000 THEN 'Alto' WHEN total >= 500 THEN 'Medio' ELSE 'Bajo' END AS rendimiento", 'ORDER BY total DESC'],
    retroalimentacionError: 'CTE con LEFT JOIN y COALESCE, luego CASE sobre el total en la consulta principal',
  },
  {
    id: 'in-b-042',
    nivel: 'intermedio',
    titulo: 'Código de producto con funciones texto',
    descripcion: 'Para cada producto, genera un código: las 3 primeras letras del nombre en mayúsculas, seguidas de la longitud del nombre. Ordena por longitud descendente.',
    objetivo: 'Combinar UPPER, SUBSTR y LENGTH en un mismo SELECT.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['nombre','codigo','longitud'],
      filas: [['Laptop Pro','LAP10',10],['Monitor','MON7',7],['Teclado','TEC7',7],['Tablet','TAB6',6],['Webcam','WEB6',6],['Mouse','MOU5',5]],
    },
    solucionOficial: "SELECT nombre, UPPER(SUBSTR(nombre, 1, 3)) || LENGTH(nombre) AS codigo, LENGTH(nombre) AS longitud FROM productos ORDER BY longitud DESC, nombre;",
    solucionesAlternativas: [],
    explicacion: "SUBSTR(nombre, 1, 3) extrae los primeros 3 chars. UPPER los convierte a mayúsculas. || es el operador de concatenación en SQLite. LENGTH(nombre) añade el número al final.",
    pistas: ["UPPER(SUBSTR(nombre, 1, 3)) para las 3 primeras letras en mayúsculas", "|| LENGTH(nombre) para concatenar la longitud al final", "|| es el operador de concatenación en SQLite (no +)"],
    retroalimentacionError: "UPPER(SUBSTR(nombre, 1, 3)) || LENGTH(nombre) — usa || para concatenar en SQLite",
  },
  {
    id: 'in-b-043',
    nivel: 'intermedio',
    titulo: 'WHERE complejo con paréntesis',
    descripcion: 'Muestra los empleados que (trabajan en Tecnología o Marketing Y tienen salario > 55000) OR (trabajan en Ventas Y tienen salario < 44000).',
    objetivo: 'Usar paréntesis para controlar la precedencia de AND/OR en WHERE.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['nombre','departamento','salario'],
      filas: [['Miguel','Tecnología',60000],['Carlos','Tecnología',65000],['Laura','Tecnología',70000],['Pedro','Ventas',42000]],
    },
    solucionOficial: "SELECT nombre, departamento, salario FROM empleados WHERE (departamento IN ('Tecnología', 'Marketing') AND salario > 55000) OR (departamento = 'Ventas' AND salario < 44000) ORDER BY departamento, salario;",
    solucionesAlternativas: [],
    explicacion: "Los paréntesis son esenciales: sin ellos, AND tiene precedencia sobre OR y la lógica cambia. Sofía y Andrés de Marketing no pasan (52000 y 55000 no son > 55000). Solo Pedro de Ventas tiene < 44000.",
    pistas: ["Usa paréntesis para cada condición compuesta: (...) OR (...)", "departamento IN ('Tecnología', 'Marketing') AND salario > 55000", "OR departamento = 'Ventas' AND salario < 44000"],
    retroalimentacionError: "Los paréntesis controlan la precedencia: (condicion1 AND condicion2) OR (condicion3 AND condicion4)",
  },
  {
    id: 'in-b-044',
    nivel: 'intermedio',
    titulo: 'ABS para diferencias salariales',
    descripcion: 'Para cada empleado, muestra la diferencia absoluta entre su salario y el salario promedio de la empresa. Ordena de menor a mayor diferencia.',
    objetivo: 'Usar ABS para obtener la distancia al promedio sin importar si es superior o inferior.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['nombre','salario','diferencia_abs'],
      filas: [['Sofía',52000,1100],['Andrés',55000,1900],['Elena',50000,3100],['Ana',48000,5100],['Miguel',60000,6900],['María',45000,8100],['Javier',44000,9100],['Pedro',42000,11100],['Carlos',65000,11900],['Laura',70000,16900]],
    },
    solucionOficial: 'SELECT nombre, salario, ABS(salario - (SELECT AVG(salario) FROM empleados)) AS diferencia_abs FROM empleados ORDER BY diferencia_abs;',
    solucionesAlternativas: [],
    explicacion: 'AVG de todos los empleados = 53100. ABS convierte diferencias negativas (empleados con menos del promedio) en positivas. Sofía (52000) está más cerca del promedio.',
    pistas: ['(SELECT AVG(salario) FROM empleados) = 53100', 'ABS(salario - 53100) da la distancia al promedio', 'ORDER BY diferencia_abs para ver quién está más cerca'],
    retroalimentacionError: 'ABS(salario - (SELECT AVG(salario) FROM empleados)) AS diferencia_abs',
  },
  {
    id: 'in-b-045',
    nivel: 'intermedio',
    titulo: 'Subconsulta en FROM con pre-filtro',
    descripcion: 'Muestra los meses donde el total de ventas supera 1000, usando una subconsulta en FROM para pre-calcular los totales por mes.',
    objetivo: 'Usar una tabla derivada (subconsulta en FROM) como paso intermedio.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['mes','total_mes'],
      filas: [['2024-01',3019.9],['2024-02',3399.94]],
    },
    solucionOficial: "SELECT mes, total_mes FROM (SELECT STRFTIME('%Y-%m', fecha) AS mes, ROUND(SUM(monto), 2) AS total_mes FROM ventas GROUP BY mes) WHERE total_mes > 1000 ORDER BY mes;",
    solucionesAlternativas: [],
    explicacion: 'La subconsulta interna calcula el total por mes. La consulta externa filtra los meses > 1000. Marzo (459.88) queda excluido. Esta estructura es alternativa a usar una CTE.',
    pistas: ['Subconsulta en FROM: (SELECT STRFTIME(…) AS mes, SUM(monto) AS total_mes FROM ventas GROUP BY mes)', 'La consulta externa hace WHERE total_mes > 1000 sobre esa tabla derivada', 'Compara con la versión CTE del mismo resultado'],
    retroalimentacionError: 'SELECT ... FROM (subconsulta que pre-agrega) WHERE total_mes > 1000',
  },
  {
    id: 'in-b-046',
    nivel: 'intermedio',
    titulo: 'REPLACE para estandarizar texto',
    descripcion: 'Muestra los departamentos de empleados reemplazando "Tecnología" por "Tech" y "Marketing" por "Mkt". Ordena por el nuevo nombre y empleado.',
    objetivo: 'Usar REPLACE para transformar valores de texto en los resultados.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['nombre','dept_abr'],
      filas: [['Ana','RRHH'],['Elena','RRHH'],['Sofía','Mkt'],['Andrés','Mkt'],['Carlos','Tech'],['Laura','Tech'],['Miguel','Tech'],['María','Ventas'],['Pedro','Ventas'],['Javier','Ventas']],
    },
    solucionOficial: "SELECT nombre, REPLACE(REPLACE(departamento, 'Tecnología', 'Tech'), 'Marketing', 'Mkt') AS dept_abr FROM empleados ORDER BY dept_abr, nombre;",
    solucionesAlternativas: [],
    explicacion: 'REPLACE(texto, de, a) reemplaza todas las ocurrencias. Se pueden anidar: el resultado del primer REPLACE se pasa al segundo. El almacenamiento original no cambia.',
    pistas: ["REPLACE(departamento, 'Tecnología', 'Tech') para la primera sustitución", "REPLACE(..., 'Marketing', 'Mkt') para anidar la segunda", 'ORDER BY dept_abr, nombre'],
    retroalimentacionError: "REPLACE(REPLACE(departamento, 'Tecnología', 'Tech'), 'Marketing', 'Mkt') — anida los REPLACE",
  },
  {
    id: 'in-b-047',
    nivel: 'intermedio',
    titulo: 'CTE + HAVING',
    descripcion: 'Usa una CTE para contar las ventas por producto. Muestra solo los productos que aparecen en más de una venta.',
    objetivo: 'Usar HAVING dentro de una CTE y unir el resultado con otra tabla.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['nombre','num_ventas','total'],
      filas: [['Laptop Pro',2,3899.97],['Mouse',2,449.85]],
    },
    solucionOficial: 'WITH ventas_prod AS (SELECT producto_id, COUNT(*) AS num_ventas, ROUND(SUM(monto), 2) AS total FROM ventas GROUP BY producto_id HAVING COUNT(*) > 1)\nSELECT p.nombre, vp.num_ventas, vp.total FROM ventas_prod vp INNER JOIN productos p ON vp.producto_id = p.id ORDER BY vp.num_ventas DESC, p.nombre;',
    solucionesAlternativas: [],
    explicacion: 'HAVING COUNT(*) > 1 dentro de la CTE filtra en el momento de la agregación. Laptop Pro (ventas 2 y 6) y Mouse (ventas 1 y 7) tienen 2 ventas cada uno.',
    pistas: ['HAVING COUNT(*) > 1 dentro de la definición de la CTE, después del GROUP BY', 'INNER JOIN productos para obtener el nombre', 'ORDER BY num_ventas DESC, nombre'],
    retroalimentacionError: 'HAVING va dentro de la CTE, después del GROUP BY: GROUP BY producto_id HAVING COUNT(*) > 1',
  },
  {
    id: 'in-b-048',
    nivel: 'intermedio',
    titulo: 'Integrador: CTE + JOIN + agregación + CASE',
    descripcion: 'Reporte de departamentos: número de empleados, salario promedio redondeado y clasificación ("Alto Costo" si promedio > 60000, "Normal" si no). Ordena por promedio descendente.',
    objetivo: 'Integrar CTE, agregación, CASE y ORDER BY en un único reporte.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['departamento','empleados','promedio','clasificacion'],
      filas: [['Tecnología',3,65000,'Alto Costo'],['Marketing',2,53500,'Normal'],['RRHH',2,49000,'Normal'],['Ventas',3,43667,'Normal']],
    },
    solucionOficial: "WITH stats AS (SELECT departamento, COUNT(*) AS empleados, ROUND(AVG(salario)) AS promedio FROM empleados GROUP BY departamento)\nSELECT departamento, empleados, promedio, CASE WHEN promedio > 60000 THEN 'Alto Costo' ELSE 'Normal' END AS clasificacion FROM stats ORDER BY promedio DESC;",
    solucionesAlternativas: [],
    explicacion: 'La CTE pre-calcula las estadísticas por departamento. La consulta final aplica CASE sobre el promedio calculado. Solo Tecnología (65000) supera el umbral de 60000.',
    pistas: ['CTE con COUNT(*) AS empleados y ROUND(AVG(salario)) AS promedio GROUP BY departamento', "CASE WHEN promedio > 60000 THEN 'Alto Costo' ELSE 'Normal' END AS clasificacion", 'ORDER BY promedio DESC'],
    retroalimentacionError: 'CTE calcula stats, consulta principal aplica CASE sobre ellas',
  },
  {
    id: 'in-b-049',
    nivel: 'intermedio',
    titulo: 'Integrador: texto + fecha + subconsulta',
    descripcion: 'Muestra, para empleados contratados desde 2020: nombre en mayúsculas, año de contratación, salario y si está "Por encima" o "Por debajo" del promedio general.',
    objetivo: 'Combinar UPPER, SUBSTR, WHERE con fecha y subconsulta escalar en un único SELECT.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['nombre_may','anio','salario','vs_promedio'],
      filas: [['MIGUEL','2020',60000,'Por encima'],['ELENA','2020',50000,'Por debajo'],['MARÍA','2020',45000,'Por debajo'],['SOFÍA','2021',52000,'Por debajo'],['ANA','2021',48000,'Por debajo'],['JAVIER','2022',44000,'Por debajo'],['PEDRO','2022',42000,'Por debajo']],
    },
    solucionOficial: "SELECT UPPER(nombre) AS nombre_may, SUBSTR(fecha_contrato, 1, 4) AS anio, salario, CASE WHEN salario > (SELECT AVG(salario) FROM empleados) THEN 'Por encima' ELSE 'Por debajo' END AS vs_promedio FROM empleados WHERE fecha_contrato >= '2020-01-01' ORDER BY anio, salario DESC;",
    solucionesAlternativas: [],
    explicacion: "AVG global = 53100. Solo Miguel (60000 > 53100) está por encima entre los contratados desde 2020. UPPER y SUBSTR transforman la presentación. WHERE filtra por fecha.",
    pistas: ["WHERE fecha_contrato >= '2020-01-01' para filtrar desde 2020", 'UPPER(nombre) AS nombre_may y SUBSTR(fecha_contrato, 1, 4) AS anio', "CASE WHEN salario > (SELECT AVG(salario) FROM empleados) THEN 'Por encima' ELSE 'Por debajo' END"],
    retroalimentacionError: "WHERE fecha_contrato >= '2020-01-01' + UPPER + SUBSTR + subconsulta escalar en CASE",
  },
  {
    id: 'in-b-050',
    nivel: 'intermedio',
    titulo: 'Integrador final intermedio',
    descripcion: 'Reporte completo: para cada empleado con ventas, muestra nombre, departamento, total vendido, el mes de su venta más reciente y si el total supera el promedio de todos los vendedores.',
    objetivo: 'Integrar CTE múltiple, JOIN, subconsulta, STRFTIME y CASE en un único análisis.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['nombre','departamento','total_ventas','ultimo_mes','vs_promedio'],
      filas: [['Carlos','Tecnología',4199.94,'2024-02','Por encima'],['Laura','Tecnología',1299.99,'2024-02','Por encima'],['María','Ventas',719.82,'2024-03','Por debajo'],['Ana','RRHH',499.99,'2024-02','Por debajo'],['Pedro','Ventas',159.98,'2024-03','Por debajo']],
    },
    solucionOficial: "WITH totales AS (SELECT e.id, e.nombre, e.departamento, ROUND(SUM(v.monto), 2) AS total_ventas, STRFTIME('%Y-%m', MAX(v.fecha)) AS ultimo_mes FROM empleados e INNER JOIN ventas v ON e.id = v.empleado_id GROUP BY e.id, e.nombre, e.departamento)\nSELECT nombre, departamento, total_ventas, ultimo_mes, CASE WHEN total_ventas > (SELECT AVG(total_ventas) FROM totales) THEN 'Por encima' ELSE 'Por debajo' END AS vs_promedio FROM totales ORDER BY total_ventas DESC;",
    solucionesAlternativas: [],
    explicacion: "La CTE calcula el total y el mes del MAX(fecha) por empleado. La consulta final compara cada total con el promedio de la CTE. Promedio de vendedores = (4199.94+1299.99+719.82+499.99+159.98)/5 = 1375.94.",
    pistas: ['CTE: INNER JOIN + SUM(monto) + STRFTIME(MAX(fecha)) GROUP BY empleado', "CASE WHEN total_ventas > (SELECT AVG(total_ventas) FROM totales) — subconsulta sobre la propia CTE", 'ORDER BY total_ventas DESC'],
    retroalimentacionError: 'CTE con totales, luego CASE comparando con AVG de la misma CTE mediante subconsulta',
  },
];
