import type { EjercicioBanco } from '../../types';

const SETUP_TECNOMART = `
CREATE TABLE empleados (id INTEGER PRIMARY KEY, nombre TEXT, apellido TEXT, departamento TEXT, salario REAL, fecha_contrato TEXT, email TEXT, activo INTEGER);
INSERT INTO empleados VALUES (1,'María','González','Ventas',45000,'2020-03-15','maria@tecnomart.com',1);
INSERT INTO empleados VALUES (2,'Carlos','López','Tecnología',65000,'2019-06-01','carlos@tecnomart.com',1);
INSERT INTO empleados VALUES (3,'Ana','Martínez','RRHH',48000,'2021-01-10','ana@tecnomart.com',1);
INSERT INTO empleados VALUES (4,'Pedro','Sánchez','Ventas',42000,'2022-08-20','pedro@tecnomart.com',1);
INSERT INTO empleados VALUES (5,'Laura','Torres','Tecnología',70000,'2018-11-05','laura@tecnomart.com',1);
INSERT INTO empleados VALUES (6,'Miguel','Ramos','Tecnología',60000,'2020-07-15','miguel@tecnomart.com',1);
INSERT INTO empleados VALUES (7,'Sofía','Ruiz','Marketing',52000,'2021-04-01','sofia@tecnomart.com',1);
INSERT INTO empleados VALUES (8,'Javier','García','Ventas',44000,'2022-02-14','javier@tecnomart.com',1);
INSERT INTO empleados VALUES (9,'Elena','Moreno','RRHH',50000,'2020-09-30','elena@tecnomart.com',1);
INSERT INTO empleados VALUES (10,'Andrés','Jiménez','Marketing',55000,'2019-12-01','andres@tecnomart.com',0);
CREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL, stock INTEGER);
INSERT INTO productos VALUES (1,'Laptop Pro 15','Electrónica',1299.99,20);
INSERT INTO productos VALUES (2,'Mouse Inalámbrico','Periféricos',29.99,150);
INSERT INTO productos VALUES (3,'Teclado Mecánico','Periféricos',89.99,80);
INSERT INTO productos VALUES (4,'Monitor 27 4K','Electrónica',499.99,15);
INSERT INTO productos VALUES (5,'Webcam HD','Periféricos',79.99,100);
INSERT INTO productos VALUES (6,'Auriculares Bluetooth','Periféricos',149.99,60);
INSERT INTO productos VALUES (7,'Tablet Pro','Electrónica',399.99,25);
INSERT INTO productos VALUES (8,'Silla Ergonómica','Mobiliario',349.99,10);
INSERT INTO productos VALUES (9,'Escritorio Ajustable','Mobiliario',599.99,5);
INSERT INTO productos VALUES (10,'Impresora Laser','Oficina',299.99,30);
CREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, apellido TEXT, ciudad TEXT, pais TEXT, email TEXT);
INSERT INTO clientes VALUES (1,'Ana','García','Madrid','España','ana@gmail.com');
INSERT INTO clientes VALUES (2,'Bob','Smith','Nueva York','USA','bob@hotmail.com');
INSERT INTO clientes VALUES (3,'Carlos','Ruiz','Ciudad de México','México','carlos@gmail.com');
INSERT INTO clientes VALUES (4,'Diana','Lee','Tokio','Japón','diana@yahoo.com');
INSERT INTO clientes VALUES (5,'Eva','Müller','Berlín','Alemania','eva@gmail.com');
INSERT INTO clientes VALUES (6,'Frank','Brown','Londres','UK','frank@outlook.com');
INSERT INTO clientes VALUES (7,'Gabi','López','Buenos Aires','Argentina','gabi@gmail.com');
INSERT INTO clientes VALUES (8,'Hiro','Tanaka','Tokio','Japón','hiro@mail.jp');
INSERT INTO clientes VALUES (9,'Isabel','Pérez','Madrid','España','isabel@gmail.com');
INSERT INTO clientes VALUES (10,'Jack','Davis','Los Ángeles','USA','jack@gmail.com');
`;

export const ejerciciosMuyNovato: EjercicioBanco[] = [
  // ── SELECT básico ─────────────────────────────────────────────────
  {
    id: 'mn-b-001',
    nivel: 'muy-novato',
    titulo: 'Todos los empleados',
    descripcion: 'Muestra todos los datos de todos los empleados.',
    objetivo: 'Usar SELECT * para obtener todos los datos de una tabla.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['id','nombre','apellido','departamento','salario','fecha_contrato','email','activo'],
      filas: [
        [1,'María','González','Ventas',45000,'2020-03-15','maria@tecnomart.com',1],
        [2,'Carlos','López','Tecnología',65000,'2019-06-01','carlos@tecnomart.com',1],
        [3,'Ana','Martínez','RRHH',48000,'2021-01-10','ana@tecnomart.com',1],
        [4,'Pedro','Sánchez','Ventas',42000,'2022-08-20','pedro@tecnomart.com',1],
        [5,'Laura','Torres','Tecnología',70000,'2018-11-05','laura@tecnomart.com',1],
        [6,'Miguel','Ramos','Tecnología',60000,'2020-07-15','miguel@tecnomart.com',1],
        [7,'Sofía','Ruiz','Marketing',52000,'2021-04-01','sofia@tecnomart.com',1],
        [8,'Javier','García','Ventas',44000,'2022-02-14','javier@tecnomart.com',1],
        [9,'Elena','Moreno','RRHH',50000,'2020-09-30','elena@tecnomart.com',1],
        [10,'Andrés','Jiménez','Marketing',55000,'2019-12-01','andres@tecnomart.com',0],
      ],
    },
    solucionOficial: 'SELECT * FROM empleados;',
    solucionesAlternativas: ['SELECT id,nombre,apellido,departamento,salario,fecha_contrato,email,activo FROM empleados;'],
    explicacion: 'SELECT * FROM empleados selecciona todas las columnas y todas las filas de la tabla empleados.',
    pistas: ['Usa SELECT * para seleccionar todas las columnas', 'Usa FROM seguido del nombre de la tabla'],
    retroalimentacionError: 'Recuerda la sintaxis: SELECT * FROM nombre_tabla',
  },
  {
    id: 'mn-b-002',
    nivel: 'muy-novato',
    titulo: 'Todos los productos',
    descripcion: 'Muestra todos los datos de la tabla productos.',
    objetivo: 'Practicar SELECT * en otra tabla.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['id','nombre','categoria','precio','stock'],
      filas: [
        [1,'Laptop Pro 15','Electrónica',1299.99,20],
        [2,'Mouse Inalámbrico','Periféricos',29.99,150],
        [3,'Teclado Mecánico','Periféricos',89.99,80],
        [4,'Monitor 27 4K','Electrónica',499.99,15],
        [5,'Webcam HD','Periféricos',79.99,100],
        [6,'Auriculares Bluetooth','Periféricos',149.99,60],
        [7,'Tablet Pro','Electrónica',399.99,25],
        [8,'Silla Ergonómica','Mobiliario',349.99,10],
        [9,'Escritorio Ajustable','Mobiliario',599.99,5],
        [10,'Impresora Laser','Oficina',299.99,30],
      ],
    },
    solucionOficial: 'SELECT * FROM productos;',
    solucionesAlternativas: [],
    explicacion: 'SELECT * FROM productos devuelve todas las columnas y filas de la tabla productos.',
    pistas: ['La tabla se llama "productos"', 'SELECT * FROM productos'],
    retroalimentacionError: 'Usa SELECT * FROM productos para ver todos los datos.',
  },
  {
    id: 'mn-b-003',
    nivel: 'muy-novato',
    titulo: 'Solo nombre y email de empleados',
    descripcion: 'Muestra únicamente el nombre y email de todos los empleados.',
    objetivo: 'Seleccionar columnas específicas con SELECT.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','email'],
      filas: [
        ['María','maria@tecnomart.com'],['Carlos','carlos@tecnomart.com'],
        ['Ana','ana@tecnomart.com'],['Pedro','pedro@tecnomart.com'],
        ['Laura','laura@tecnomart.com'],['Miguel','miguel@tecnomart.com'],
        ['Sofía','sofia@tecnomart.com'],['Javier','javier@tecnomart.com'],
        ['Elena','elena@tecnomart.com'],['Andrés','andres@tecnomart.com'],
      ],
    },
    solucionOficial: 'SELECT nombre, email FROM empleados;',
    solucionesAlternativas: [],
    explicacion: 'Especificando "nombre, email" en SELECT, solo obtenemos esas dos columnas de la tabla.',
    pistas: ['Escribe SELECT nombre, email', 'Luego FROM empleados'],
    retroalimentacionError: 'Especifica las columnas separadas por comas: SELECT nombre, email FROM empleados',
  },
  {
    id: 'mn-b-004',
    nivel: 'muy-novato',
    titulo: 'Nombre y precio de productos',
    descripcion: 'Muestra el nombre y precio de todos los productos.',
    objetivo: 'Practicar SELECT de columnas específicas.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','precio'],
      filas: [
        ['Laptop Pro 15',1299.99],['Mouse Inalámbrico',29.99],
        ['Teclado Mecánico',89.99],['Monitor 27 4K',499.99],
        ['Webcam HD',79.99],['Auriculares Bluetooth',149.99],
        ['Tablet Pro',399.99],['Silla Ergonómica',349.99],
        ['Escritorio Ajustable',599.99],['Impresora Laser',299.99],
      ],
    },
    solucionOficial: 'SELECT nombre, precio FROM productos;',
    solucionesAlternativas: [],
    explicacion: 'SELECT nombre, precio FROM productos devuelve solo esas dos columnas de todos los productos.',
    pistas: ['Selecciona las columnas: nombre, precio', 'De la tabla productos'],
    retroalimentacionError: 'Usa SELECT nombre, precio FROM productos',
  },
  {
    id: 'mn-b-005',
    nivel: 'muy-novato',
    titulo: 'Empleados de Ventas',
    descripcion: 'Muestra todos los datos de los empleados que trabajan en el departamento de Ventas.',
    objetivo: 'Usar WHERE con condición de texto.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['id','nombre','apellido','departamento','salario','fecha_contrato','email','activo'],
      filas: [
        [1,'María','González','Ventas',45000,'2020-03-15','maria@tecnomart.com',1],
        [4,'Pedro','Sánchez','Ventas',42000,'2022-08-20','pedro@tecnomart.com',1],
        [8,'Javier','García','Ventas',44000,'2022-02-14','javier@tecnomart.com',1],
      ],
    },
    solucionOficial: "SELECT * FROM empleados WHERE departamento = 'Ventas';",
    solucionesAlternativas: [],
    explicacion: "WHERE departamento = 'Ventas' filtra solo los empleados del departamento Ventas.",
    pistas: ["Usa WHERE departamento = 'Ventas'", 'Los textos van entre comillas simples'],
    retroalimentacionError: "Recuerda las comillas simples: WHERE departamento = 'Ventas'",
  },
  {
    id: 'mn-b-006',
    nivel: 'muy-novato',
    titulo: 'Productos de Electrónica',
    descripcion: 'Muestra nombre y precio de los productos de la categoría "Electrónica".',
    objetivo: 'Combinar SELECT de columnas específicas con WHERE.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','precio'],
      filas: [
        ['Laptop Pro 15',1299.99],['Monitor 27 4K',499.99],['Tablet Pro',399.99],
      ],
    },
    solucionOficial: "SELECT nombre, precio FROM productos WHERE categoria = 'Electrónica';",
    solucionesAlternativas: [],
    explicacion: "Combinamos SELECT de columnas específicas con WHERE para filtrar por categoría.",
    pistas: ["Filtra WHERE categoria = 'Electrónica'", 'Selecciona nombre y precio'],
    retroalimentacionError: "SELECT nombre, precio FROM productos WHERE categoria = 'Electrónica'",
  },
  {
    id: 'mn-b-007',
    nivel: 'muy-novato',
    titulo: 'Empleados con salario mayor a $55,000',
    descripcion: 'Muestra nombre y salario de los empleados que ganan más de $55,000.',
    objetivo: 'Usar WHERE con operador > para números.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','salario'],
      filas: [['Carlos',65000],['Laura',70000],['Miguel',60000],['Andrés',55000]],
    },
    solucionOficial: 'SELECT nombre, salario FROM empleados WHERE salario > 55000;',
    solucionesAlternativas: [],
    explicacion: 'WHERE salario > 55000 filtra empleados cuyo salario es mayor a 55000. Los números no necesitan comillas.',
    pistas: ['Usa WHERE salario > 55000', 'Los números no van entre comillas'],
    retroalimentacionError: 'WHERE salario > 55000 (sin comillas para números)',
  },
  {
    id: 'mn-b-008',
    nivel: 'muy-novato',
    titulo: 'Productos con precio menor a $100',
    descripcion: 'Muestra nombre y precio de los productos que cuestan menos de $100.',
    objetivo: 'Usar WHERE con operador < para filtrar números.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','precio'],
      filas: [['Mouse Inalámbrico',29.99],['Teclado Mecánico',89.99],['Webcam HD',79.99]],
    },
    solucionOficial: 'SELECT nombre, precio FROM productos WHERE precio < 100;',
    solucionesAlternativas: [],
    explicacion: 'WHERE precio < 100 filtra productos con precio estrictamente menor a 100.',
    pistas: ['Usa WHERE precio < 100', 'Sin comillas en el número'],
    retroalimentacionError: 'Usa WHERE precio < 100 sin comillas',
  },
  {
    id: 'mn-b-009',
    nivel: 'muy-novato',
    titulo: 'Clientes de España',
    descripcion: 'Muestra nombre y ciudad de los clientes que son de España.',
    objetivo: 'Filtrar por país con WHERE.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','ciudad'],
      filas: [['Ana','Madrid'],['Isabel','Madrid']],
    },
    solucionOficial: "SELECT nombre, ciudad FROM clientes WHERE pais = 'España';",
    solucionesAlternativas: [],
    explicacion: "WHERE pais = 'España' filtra solo los clientes españoles.",
    pistas: ["Filtra WHERE pais = 'España'", 'Con comillas simples para el texto'],
    retroalimentacionError: "SELECT nombre, ciudad FROM clientes WHERE pais = 'España'",
  },
  {
    id: 'mn-b-010',
    nivel: 'muy-novato',
    titulo: 'Empleados activos',
    descripcion: 'Muestra nombre y departamento de los empleados que están activos (activo = 1).',
    objetivo: 'Filtrar con WHERE por valor numérico binario.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','departamento'],
      filas: [
        ['María','Ventas'],['Carlos','Tecnología'],['Ana','RRHH'],
        ['Pedro','Ventas'],['Laura','Tecnología'],['Miguel','Tecnología'],
        ['Sofía','Marketing'],['Javier','Ventas'],['Elena','RRHH'],
      ],
    },
    solucionOficial: 'SELECT nombre, departamento FROM empleados WHERE activo = 1;',
    solucionesAlternativas: [],
    explicacion: 'WHERE activo = 1 filtra solo los empleados activos. Andrés (activo=0) no aparece.',
    pistas: ['Filtra WHERE activo = 1', 'El 1 representa "activo"'],
    retroalimentacionError: 'Usa WHERE activo = 1 para filtrar empleados activos',
  },
  {
    id: 'mn-b-011',
    nivel: 'muy-novato',
    titulo: 'Productos ordenados por precio',
    descripcion: 'Muestra nombre y precio de todos los productos, ordenados de más barato a más caro.',
    objetivo: 'Usar ORDER BY ASC para ordenar resultados.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','precio'],
      filas: [
        ['Mouse Inalámbrico',29.99],['Webcam HD',79.99],['Teclado Mecánico',89.99],
        ['Auriculares Bluetooth',149.99],['Impresora Laser',299.99],['Silla Ergonómica',349.99],
        ['Tablet Pro',399.99],['Monitor 27 4K',499.99],['Escritorio Ajustable',599.99],['Laptop Pro 15',1299.99],
      ],
    },
    solucionOficial: 'SELECT nombre, precio FROM productos ORDER BY precio ASC;',
    solucionesAlternativas: ['SELECT nombre, precio FROM productos ORDER BY precio;'],
    explicacion: 'ORDER BY precio ASC ordena de menor a mayor. ASC es el predeterminado y puede omitirse.',
    pistas: ['Usa ORDER BY precio ASC', 'ASC = ascendente (menor a mayor)'],
    retroalimentacionError: 'Usa ORDER BY precio ASC al final de la consulta',
  },
  {
    id: 'mn-b-012',
    nivel: 'muy-novato',
    titulo: 'Top 3 empleados mejor pagados',
    descripcion: 'Muestra nombre y salario de los 3 empleados con mayor salario.',
    objetivo: 'Combinar ORDER BY DESC con LIMIT.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','salario'],
      filas: [['Laura',70000],['Carlos',65000],['Miguel',60000]],
    },
    solucionOficial: 'SELECT nombre, salario FROM empleados ORDER BY salario DESC LIMIT 3;',
    solucionesAlternativas: [],
    explicacion: 'ORDER BY salario DESC ordena de mayor a menor. LIMIT 3 devuelve solo los 3 primeros.',
    pistas: ['Ordena por salario de mayor a menor: ORDER BY salario DESC', 'Limita con LIMIT 3'],
    retroalimentacionError: 'Usa ORDER BY salario DESC LIMIT 3',
  },
  {
    id: 'mn-b-013',
    nivel: 'muy-novato',
    titulo: 'Productos más caros primero',
    descripcion: 'Muestra todos los productos ordenados de más caro a más barato.',
    objetivo: 'Usar ORDER BY DESC.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','precio'],
      filas: [
        ['Laptop Pro 15',1299.99],['Escritorio Ajustable',599.99],['Monitor 27 4K',499.99],
        ['Tablet Pro',399.99],['Silla Ergonómica',349.99],['Impresora Laser',299.99],
        ['Auriculares Bluetooth',149.99],['Teclado Mecánico',89.99],['Webcam HD',79.99],['Mouse Inalámbrico',29.99],
      ],
    },
    solucionOficial: 'SELECT nombre, precio FROM productos ORDER BY precio DESC;',
    solucionesAlternativas: [],
    explicacion: 'ORDER BY precio DESC ordena de mayor a menor (descendente).',
    pistas: ['ORDER BY precio DESC para orden descendente'],
    retroalimentacionError: 'Usa ORDER BY precio DESC al final',
  },
  {
    id: 'mn-b-014',
    nivel: 'muy-novato',
    titulo: 'Empleados ordenados por nombre',
    descripcion: 'Muestra nombre y departamento de todos los empleados, ordenados alfabéticamente por nombre.',
    objetivo: 'Ordenar texto alfabéticamente con ORDER BY.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','departamento'],
      filas: [
        ['Ana','RRHH'],['Andrés','Marketing'],['Carlos','Tecnología'],
        ['Elena','RRHH'],['Javier','Ventas'],['Laura','Tecnología'],
        ['María','Ventas'],['Miguel','Tecnología'],['Pedro','Ventas'],['Sofía','Marketing'],
      ],
    },
    solucionOficial: 'SELECT nombre, departamento FROM empleados ORDER BY nombre ASC;',
    solucionesAlternativas: ['SELECT nombre, departamento FROM empleados ORDER BY nombre;'],
    explicacion: 'ORDER BY nombre ASC ordena los empleados alfabéticamente de la A a la Z.',
    pistas: ['Usa ORDER BY nombre', 'ASC es de la A a la Z'],
    retroalimentacionError: 'Usa ORDER BY nombre ASC',
  },
  {
    id: 'mn-b-015',
    nivel: 'muy-novato',
    titulo: 'Los 5 primeros clientes',
    descripcion: 'Muestra los primeros 5 clientes ordenados por id.',
    objetivo: 'Usar LIMIT para limitar resultados.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['id','nombre','apellido'],
      filas: [
        [1,'Ana','García'],[2,'Bob','Smith'],
        [3,'Carlos','Ruiz'],[4,'Diana','Lee'],[5,'Eva','Müller'],
      ],
    },
    solucionOficial: 'SELECT id, nombre, apellido FROM clientes ORDER BY id LIMIT 5;',
    solucionesAlternativas: [],
    explicacion: 'ORDER BY id garantiza orden predecible. LIMIT 5 devuelve solo 5 filas.',
    pistas: ['Ordena por id para resultados predecibles', 'Usa LIMIT 5'],
    retroalimentacionError: 'SELECT id, nombre, apellido FROM clientes ORDER BY id LIMIT 5',
  },
  {
    id: 'mn-b-016',
    nivel: 'muy-novato',
    titulo: 'Clientes cuyo nombre empieza con A',
    descripcion: 'Muestra nombre y email de los clientes cuyo nombre empieza con la letra A.',
    objetivo: 'Usar LIKE con patrón de inicio.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','email'],
      filas: [['Ana','ana@gmail.com']],
    },
    solucionOficial: "SELECT nombre, email FROM clientes WHERE nombre LIKE 'A%';",
    solucionesAlternativas: [],
    explicacion: "LIKE 'A%' busca nombres que empiecen exactamente con la letra A mayúscula.",
    pistas: ["Usa LIKE 'A%' para nombres que empiezan con A", "El % representa cualquier cosa después"],
    retroalimentacionError: "WHERE nombre LIKE 'A%'",
  },
  {
    id: 'mn-b-017',
    nivel: 'muy-novato',
    titulo: 'Emails de Gmail',
    descripcion: 'Muestra nombre y email de los clientes que tienen email de Gmail (@gmail.com).',
    objetivo: 'Usar LIKE para buscar dentro de texto.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','email'],
      filas: [
        ['Ana','ana@gmail.com'],['Carlos','carlos@gmail.com'],
        ['Eva','eva@gmail.com'],['Gabi','gabi@gmail.com'],
        ['Isabel','isabel@gmail.com'],['Jack','jack@gmail.com'],
      ],
    },
    solucionOficial: "SELECT nombre, email FROM clientes WHERE email LIKE '%@gmail.com';",
    solucionesAlternativas: [],
    explicacion: "LIKE '%@gmail.com' busca emails que terminen en @gmail.com. El % al inicio indica cualquier cosa antes.",
    pistas: ["Usa LIKE '%@gmail.com' para emails de Gmail", "El % antes significa cualquier texto"],
    retroalimentacionError: "WHERE email LIKE '%@gmail.com'",
  },
  {
    id: 'mn-b-018',
    nivel: 'muy-novato',
    titulo: 'Productos que contienen "Pro"',
    descripcion: 'Muestra nombre y precio de los productos cuyo nombre contiene "Pro".',
    objetivo: 'Usar LIKE con % en ambos lados para buscar en cualquier posición.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','precio'],
      filas: [['Laptop Pro 15',1299.99],['Tablet Pro',399.99]],
    },
    solucionOficial: "SELECT nombre, precio FROM productos WHERE nombre LIKE '%Pro%';",
    solucionesAlternativas: [],
    explicacion: "'%Pro%' busca 'Pro' en cualquier posición del nombre.",
    pistas: ["Usa '%Pro%' para buscar en cualquier parte del texto"],
    retroalimentacionError: "WHERE nombre LIKE '%Pro%'",
  },
  {
    id: 'mn-b-019',
    nivel: 'muy-novato',
    titulo: 'Empleados de Tecnología y Ventas',
    descripcion: 'Muestra nombre y departamento de empleados que sean de Tecnología o Ventas.',
    objetivo: 'Usar OR para combinar condiciones.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','departamento'],
      filas: [
        ['María','Ventas'],['Carlos','Tecnología'],
        ['Pedro','Ventas'],['Laura','Tecnología'],
        ['Miguel','Tecnología'],['Javier','Ventas'],
      ],
    },
    solucionOficial: "SELECT nombre, departamento FROM empleados WHERE departamento = 'Tecnología' OR departamento = 'Ventas';",
    solucionesAlternativas: ["SELECT nombre, departamento FROM empleados WHERE departamento IN ('Tecnología', 'Ventas');"],
    explicacion: "OR devuelve filas donde AL MENOS UNA condición es verdadera. IN es una alternativa más concisa.",
    pistas: ["Usa OR para combinar dos condiciones", "O usa IN ('Tecnología', 'Ventas')"],
    retroalimentacionError: "WHERE departamento = 'Tecnología' OR departamento = 'Ventas'",
  },
  {
    id: 'mn-b-020',
    nivel: 'muy-novato',
    titulo: 'Empleados de Tecnología con salario alto',
    descripcion: 'Muestra nombre y salario de empleados que sean de Tecnología Y ganen más de $60,000.',
    objetivo: 'Usar AND para combinar condiciones.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','salario'],
      filas: [['Carlos',65000],['Laura',70000]],
    },
    solucionOficial: "SELECT nombre, salario FROM empleados WHERE departamento = 'Tecnología' AND salario > 60000;",
    solucionesAlternativas: [],
    explicacion: "AND requiere que AMBAS condiciones sean verdaderas. Miguel gana 60000 (no > 60000), así que no aparece.",
    pistas: ["Usa AND para que se cumplan dos condiciones a la vez"],
    retroalimentacionError: "WHERE departamento = 'Tecnología' AND salario > 60000",
  },
  {
    id: 'mn-b-021',
    nivel: 'muy-novato',
    titulo: 'Clientes de España, México o Argentina',
    descripcion: 'Muestra nombre y país de clientes de España, México o Argentina usando IN.',
    objetivo: 'Usar IN para filtrar múltiples valores.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','pais'],
      filas: [['Ana','España'],['Carlos','México'],['Gabi','Argentina'],['Isabel','España']],
    },
    solucionOficial: "SELECT nombre, pais FROM clientes WHERE pais IN ('España', 'México', 'Argentina');",
    solucionesAlternativas: [],
    explicacion: "IN es más limpio que múltiples OR cuando tienes varios valores posibles.",
    pistas: ["Usa IN ('España', 'México', 'Argentina')", "Los valores van entre paréntesis separados por comas"],
    retroalimentacionError: "WHERE pais IN ('España', 'México', 'Argentina')",
  },
  {
    id: 'mn-b-022',
    nivel: 'muy-novato',
    titulo: 'Productos con precio entre $50 y $300',
    descripcion: 'Muestra nombre y precio de productos con precio entre $50 y $300 (inclusivo).',
    objetivo: 'Usar BETWEEN para filtrar por rango.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','precio'],
      filas: [
        ['Teclado Mecánico',89.99],['Webcam HD',79.99],
        ['Auriculares Bluetooth',149.99],['Impresora Laser',299.99],
      ],
    },
    solucionOficial: 'SELECT nombre, precio FROM productos WHERE precio BETWEEN 50 AND 300;',
    solucionesAlternativas: ['SELECT nombre, precio FROM productos WHERE precio >= 50 AND precio <= 300;'],
    explicacion: 'BETWEEN es inclusivo: incluye los valores 50 y 300. Es equivalente a >= 50 AND <= 300.',
    pistas: ['Usa BETWEEN 50 AND 300', 'BETWEEN es inclusivo en ambos extremos'],
    retroalimentacionError: 'WHERE precio BETWEEN 50 AND 300',
  },
  {
    id: 'mn-b-023',
    nivel: 'muy-novato',
    titulo: 'Empleados contratados entre 2020 y 2021',
    descripcion: 'Muestra nombre y fecha_contrato de empleados contratados entre 2020-01-01 y 2021-12-31.',
    objetivo: 'Usar BETWEEN con fechas.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','fecha_contrato'],
      filas: [
        ['María','2020-03-15'],['Ana','2021-01-10'],
        ['Miguel','2020-07-15'],['Sofía','2021-04-01'],['Elena','2020-09-30'],
      ],
    },
    solucionOficial: "SELECT nombre, fecha_contrato FROM empleados WHERE fecha_contrato BETWEEN '2020-01-01' AND '2021-12-31';",
    solucionesAlternativas: [],
    explicacion: "BETWEEN también funciona con fechas en formato 'YYYY-MM-DD'. Las fechas van entre comillas simples.",
    pistas: ["BETWEEN '2020-01-01' AND '2021-12-31'", 'Las fechas van entre comillas como texto'],
    retroalimentacionError: "WHERE fecha_contrato BETWEEN '2020-01-01' AND '2021-12-31'",
  },
  {
    id: 'mn-b-024',
    nivel: 'muy-novato',
    titulo: 'Empleados con salario entre $44,000 y $65,000',
    descripcion: 'Muestra nombre y salario de empleados con salario en ese rango.',
    objetivo: 'Usar BETWEEN con rangos numéricos.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','salario'],
      filas: [['María',45000],['Ana',48000],['Miguel',60000],['Sofía',52000],['Javier',44000],['Elena',50000],['Andrés',55000]],
    },
    solucionOficial: 'SELECT nombre, salario FROM empleados WHERE salario BETWEEN 44000 AND 65000;',
    solucionesAlternativas: ['SELECT nombre, salario FROM empleados WHERE salario >= 44000 AND salario <= 65000;'],
    explicacion: 'BETWEEN 44000 AND 65000 filtra salarios en ese rango, incluyendo los extremos.',
    pistas: ['BETWEEN 44000 AND 65000', 'Incluye ambos extremos'],
    retroalimentacionError: 'WHERE salario BETWEEN 44000 AND 65000',
  },
  {
    id: 'mn-b-025',
    nivel: 'muy-novato',
    titulo: 'Empleados no activos',
    descripcion: 'Muestra nombre y departamento de empleados que NO están activos (activo = 0).',
    objetivo: 'Filtrar con WHERE por valor 0 o usando NOT.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','departamento'],
      filas: [['Andrés','Marketing']],
    },
    solucionOficial: 'SELECT nombre, departamento FROM empleados WHERE activo = 0;',
    solucionesAlternativas: ['SELECT nombre, departamento FROM empleados WHERE activo != 1;', 'SELECT nombre, departamento FROM empleados WHERE NOT activo = 1;'],
    explicacion: 'WHERE activo = 0 filtra los empleados inactivos. Solo Andrés tiene activo=0.',
    pistas: ['activo = 0 significa inactivo', 'Usa WHERE activo = 0'],
    retroalimentacionError: 'WHERE activo = 0',
  },
  // ── NULL ──────────────────────────────────────────────────────────
  {
    id: 'mn-b-026',
    nivel: 'muy-novato',
    titulo: 'Productos sin descripción',
    descripcion: 'Muestra el nombre de los productos que no tienen descripción (descripcion IS NULL).',
    objetivo: 'Usar IS NULL para filtrar valores nulos.',
    setupSql: `
      CREATE TABLE productos (id INTEGER, nombre TEXT, precio REAL, descripcion TEXT);
      INSERT INTO productos VALUES (1,'Laptop',1299.99,'Laptop de alta gama');
      INSERT INTO productos VALUES (2,'Mouse',29.99,NULL);
      INSERT INTO productos VALUES (3,'Monitor',499.99,'Monitor 4K 27 pulgadas');
      INSERT INTO productos VALUES (4,'Teclado',89.99,NULL);
      INSERT INTO productos VALUES (5,'Webcam',79.99,NULL);
    `,
    resultadoEsperado: {
      columnas: ['nombre'],
      filas: [['Mouse'],['Teclado'],['Webcam']],
    },
    solucionOficial: 'SELECT nombre FROM productos WHERE descripcion IS NULL;',
    solucionesAlternativas: [],
    explicacion: 'IS NULL es la única forma correcta de buscar valores nulos. = NULL nunca funciona.',
    pistas: ['Usa IS NULL (no = NULL)', 'WHERE descripcion IS NULL'],
    retroalimentacionError: 'Usa IS NULL, no = NULL: WHERE descripcion IS NULL',
  },
  {
    id: 'mn-b-027',
    nivel: 'muy-novato',
    titulo: 'Empleados con teléfono registrado',
    descripcion: 'Muestra nombre y teléfono de los empleados que SÍ tienen teléfono (no es NULL).',
    objetivo: 'Usar IS NOT NULL para filtrar valores no nulos.',
    setupSql: `
      CREATE TABLE empleados (id INTEGER, nombre TEXT, telefono TEXT);
      INSERT INTO empleados VALUES (1,'María','555-1234');
      INSERT INTO empleados VALUES (2,'Carlos',NULL);
      INSERT INTO empleados VALUES (3,'Ana','555-5678');
      INSERT INTO empleados VALUES (4,'Pedro',NULL);
      INSERT INTO empleados VALUES (5,'Laura','555-9012');
    `,
    resultadoEsperado: {
      columnas: ['nombre','telefono'],
      filas: [['María','555-1234'],['Ana','555-5678'],['Laura','555-9012']],
    },
    solucionOficial: 'SELECT nombre, telefono FROM empleados WHERE telefono IS NOT NULL;',
    solucionesAlternativas: [],
    explicacion: 'IS NOT NULL devuelve filas donde el valor existe (no es NULL).',
    pistas: ['Usa IS NOT NULL para filtrar registros que tienen valor'],
    retroalimentacionError: 'WHERE telefono IS NOT NULL',
  },
  // ── ALIAS ─────────────────────────────────────────────────────────
  {
    id: 'mn-b-028',
    nivel: 'muy-novato',
    titulo: 'Empleados con alias en columnas',
    descripcion: 'Muestra nombre como "Empleado" y salario como "Sueldo" de todos los empleados.',
    objetivo: 'Usar AS para renombrar columnas en el resultado.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['Empleado','Sueldo'],
      filas: [
        ['María',45000],['Carlos',65000],['Ana',48000],['Pedro',42000],['Laura',70000],
        ['Miguel',60000],['Sofía',52000],['Javier',44000],['Elena',50000],['Andrés',55000],
      ],
    },
    solucionOficial: "SELECT nombre AS 'Empleado', salario AS 'Sueldo' FROM empleados;",
    solucionesAlternativas: ['SELECT nombre AS Empleado, salario AS Sueldo FROM empleados;'],
    explicacion: 'AS renombra la columna solo en el resultado. La tabla original no cambia.',
    pistas: ["Usa AS 'Empleado' después de nombre", "Y AS 'Sueldo' después de salario"],
    retroalimentacionError: "SELECT nombre AS 'Empleado', salario AS 'Sueldo' FROM empleados",
  },
  {
    id: 'mn-b-029',
    nivel: 'muy-novato',
    titulo: 'Clientes de Japón',
    descripcion: 'Muestra nombre y ciudad de los clientes de Japón.',
    objetivo: 'Practicar WHERE con texto.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','ciudad'],
      filas: [['Diana','Tokio'],['Hiro','Tokio']],
    },
    solucionOficial: "SELECT nombre, ciudad FROM clientes WHERE pais = 'Japón';",
    solucionesAlternativas: [],
    explicacion: "Filtramos por pais = 'Japón' para obtener solo clientes japoneses.",
    pistas: ["WHERE pais = 'Japón'"],
    retroalimentacionError: "WHERE pais = 'Japón'",
  },
  {
    id: 'mn-b-030',
    nivel: 'muy-novato',
    titulo: 'Productos de Mobiliario o Oficina',
    descripcion: 'Muestra nombre, categoría y precio de productos de Mobiliario u Oficina.',
    objetivo: 'Usar IN para filtrar categorías.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','categoria','precio'],
      filas: [
        ['Silla Ergonómica','Mobiliario',349.99],
        ['Escritorio Ajustable','Mobiliario',599.99],
        ['Impresora Laser','Oficina',299.99],
      ],
    },
    solucionOficial: "SELECT nombre, categoria, precio FROM productos WHERE categoria IN ('Mobiliario', 'Oficina');",
    solucionesAlternativas: ["SELECT nombre, categoria, precio FROM productos WHERE categoria = 'Mobiliario' OR categoria = 'Oficina';"],
    explicacion: "IN es más legible que múltiples OR cuando tienes varios valores posibles.",
    pistas: ["Usa IN ('Mobiliario', 'Oficina')"],
    retroalimentacionError: "WHERE categoria IN ('Mobiliario', 'Oficina')",
  },
  // ── más ejercicios hasta 100 ───────────────────────────────────────
  {
    id: 'mn-b-031',
    nivel: 'muy-novato',
    titulo: 'Empleados que no son de Ventas',
    descripcion: 'Muestra nombre y departamento de empleados que NO son del departamento de Ventas.',
    objetivo: 'Usar != o NOT IN para exclusión.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','departamento'],
      filas: [
        ['Carlos','Tecnología'],['Ana','RRHH'],['Laura','Tecnología'],
        ['Miguel','Tecnología'],['Sofía','Marketing'],['Elena','RRHH'],['Andrés','Marketing'],
      ],
    },
    solucionOficial: "SELECT nombre, departamento FROM empleados WHERE departamento != 'Ventas';",
    solucionesAlternativas: ["SELECT nombre, departamento FROM empleados WHERE departamento <> 'Ventas';","SELECT nombre, departamento FROM empleados WHERE NOT departamento = 'Ventas';"],
    explicacion: "!= y <> son equivalentes en SQL: ambos significan 'diferente de'.",
    pistas: ["Usa != 'Ventas' o <> 'Ventas'"],
    retroalimentacionError: "WHERE departamento != 'Ventas'",
  },
  {
    id: 'mn-b-032',
    nivel: 'muy-novato',
    titulo: 'Apellidos que empiezan con G',
    descripcion: 'Muestra nombre y apellido de empleados cuyo apellido empiece con la letra G.',
    objetivo: 'Usar LIKE para patrones de texto.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','apellido'],
      filas: [['María','González'],['Javier','García']],
    },
    solucionOficial: "SELECT nombre, apellido FROM empleados WHERE apellido LIKE 'G%';",
    solucionesAlternativas: [],
    explicacion: "'G%' encuentra apellidos que empiezan exactamente con G mayúscula.",
    pistas: ["LIKE 'G%' para apellidos que empiezan con G"],
    retroalimentacionError: "WHERE apellido LIKE 'G%'",
  },
  {
    id: 'mn-b-033',
    nivel: 'muy-novato',
    titulo: 'Productos con stock muy bajo',
    descripcion: 'Muestra nombre y stock de productos con stock menor o igual a 15.',
    objetivo: 'Usar <= en WHERE.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','stock'],
      filas: [['Monitor 27 4K',15],['Silla Ergonómica',10],['Escritorio Ajustable',5]],
    },
    solucionOficial: 'SELECT nombre, stock FROM productos WHERE stock <= 15;',
    solucionesAlternativas: [],
    explicacion: '<= 15 incluye el valor exacto 15 también (menor O igual).',
    pistas: ['Usa <= 15 para incluir el valor 15'],
    retroalimentacionError: 'WHERE stock <= 15',
  },
  {
    id: 'mn-b-034',
    nivel: 'muy-novato',
    titulo: 'Segundo y tercer empleado más antiguo',
    descripcion: 'Muestra nombre y fecha_contrato del 2do y 3er empleado más antiguo (usa LIMIT y OFFSET).',
    objetivo: 'Usar LIMIT y OFFSET para paginación.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','fecha_contrato'],
      filas: [['Andrés','2019-12-01'],['Carlos','2019-06-01']],
    },
    solucionOficial: 'SELECT nombre, fecha_contrato FROM empleados ORDER BY fecha_contrato ASC LIMIT 2 OFFSET 1;',
    solucionesAlternativas: [],
    explicacion: 'ORDER BY fecha_contrato ASC ordena de más antiguo a más reciente. LIMIT 2 OFFSET 1 salta el primero y devuelve los siguientes 2.',
    pistas: ['Ordena por fecha_contrato ASC', 'OFFSET 1 salta el primer resultado', 'LIMIT 2 devuelve 2 resultados'],
    retroalimentacionError: 'ORDER BY fecha_contrato ASC LIMIT 2 OFFSET 1',
  },
  {
    id: 'mn-b-035',
    nivel: 'muy-novato',
    titulo: 'Clientes cuyo apellido termina en "ez"',
    descripcion: 'Muestra nombre y apellido de clientes cuyo apellido termina en "ez".',
    objetivo: 'Usar LIKE con % al inicio para buscar al final del texto.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','apellido'],
      filas: [['Gabi','López'],['Isabel','Pérez']],
    },
    solucionOficial: "SELECT nombre, apellido FROM clientes WHERE apellido LIKE '%ez';",
    solucionesAlternativas: ["SELECT nombre, apellido FROM clientes WHERE apellido LIKE '%EZ';"],
    explicacion: "'%ez' busca apellidos que terminen exactamente en 'ez'. López y Pérez califican; García termina en 'a' y Ruiz en 'iz'.",
    pistas: ["LIKE '%ez' para apellidos que terminan en ez"],
    retroalimentacionError: "WHERE apellido LIKE '%ez'",
  },
  // ── continuación hasta 100 ──────────────────────────────────────────
  {
    id: 'mn-b-036',
    nivel: 'muy-novato',
    titulo: 'Productos con stock suficiente para pedido grande',
    descripcion: 'Muestra nombre y stock de productos con stock mayor o igual a 50.',
    objetivo: 'Usar >= en WHERE.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','stock'],
      filas: [['Mouse Inalámbrico',150],['Teclado Mecánico',80],['Webcam HD',100],['Auriculares Bluetooth',60]],
    },
    solucionOficial: 'SELECT nombre, stock FROM productos WHERE stock >= 50;',
    solucionesAlternativas: [],
    explicacion: '>= 50 devuelve productos con stock de exactamente 50 o más. Impresora (30), Silla (10) y otros no alcanzan el mínimo.',
    pistas: ['Usa >= 50'],
    retroalimentacionError: 'WHERE stock >= 50',
  },
  {
    id: 'mn-b-037',
    nivel: 'muy-novato',
    titulo: 'Nombre completo de empleados',
    descripcion: 'Muestra nombre y apellido de todos los empleados, ordenados por apellido.',
    objetivo: 'Practicar SELECT de múltiples columnas con ORDER BY.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','apellido'],
      filas: [
        ['Javier','García'],['María','González'],['Andrés','Jiménez'],
        ['Carlos','López'],['Ana','Martínez'],['Elena','Moreno'],
        ['Miguel','Ramos'],['Sofía','Ruiz'],['Pedro','Sánchez'],['Laura','Torres'],
      ],
    },
    solucionOficial: 'SELECT nombre, apellido FROM empleados ORDER BY apellido ASC;',
    solucionesAlternativas: [],
    explicacion: 'ORDER BY apellido ASC ordena los apellidos de la A a la Z.',
    pistas: ['Selecciona nombre, apellido', 'Ordena por apellido'],
    retroalimentacionError: 'SELECT nombre, apellido FROM empleados ORDER BY apellido',
  },
  {
    id: 'mn-b-038',
    nivel: 'muy-novato',
    titulo: 'Producto más barato',
    descripcion: 'Muestra el nombre y precio del producto más barato.',
    objetivo: 'Combinar ORDER BY ASC con LIMIT 1.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','precio'],
      filas: [['Mouse Inalámbrico',29.99]],
    },
    solucionOficial: 'SELECT nombre, precio FROM productos ORDER BY precio ASC LIMIT 1;',
    solucionesAlternativas: [],
    explicacion: 'ORDER BY precio ASC ordena de más barato a más caro. LIMIT 1 devuelve solo el primero.',
    pistas: ['Ordena por precio ASC', 'LIMIT 1 para obtener solo uno'],
    retroalimentacionError: 'ORDER BY precio ASC LIMIT 1',
  },
  {
    id: 'mn-b-039',
    nivel: 'muy-novato',
    titulo: 'Clientes que no son de USA',
    descripcion: 'Muestra nombre y país de los clientes que no son de USA.',
    objetivo: 'Usar != para exclusión de texto.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','pais'],
      filas: [
        ['Ana','España'],['Carlos','México'],['Diana','Japón'],
        ['Eva','Alemania'],['Frank','UK'],['Gabi','Argentina'],
        ['Hiro','Japón'],['Isabel','España'],
      ],
    },
    solucionOficial: "SELECT nombre, pais FROM clientes WHERE pais != 'USA';",
    solucionesAlternativas: ["SELECT nombre, pais FROM clientes WHERE pais <> 'USA';"],
    explicacion: "!= 'USA' devuelve todos los clientes que no son de USA.",
    pistas: ["Usa != 'USA'"],
    retroalimentacionError: "WHERE pais != 'USA'",
  },
  {
    id: 'mn-b-040',
    nivel: 'muy-novato',
    titulo: 'Empleados del departamento RRHH con salario alto',
    descripcion: 'Muestra nombre y salario de empleados de RRHH que ganan más de $48,000.',
    objetivo: 'Combinar dos condiciones con AND.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','salario'],
      filas: [['Elena',50000]],
    },
    solucionOficial: "SELECT nombre, salario FROM empleados WHERE departamento = 'RRHH' AND salario > 48000;",
    solucionesAlternativas: [],
    explicacion: "Ana gana exactamente 48000 que no es > 48000. Solo Elena con 50000 cumple.",
    pistas: ["AND requiere ambas condiciones: departamento = 'RRHH' Y salario > 48000"],
    retroalimentacionError: "WHERE departamento = 'RRHH' AND salario > 48000",
  },
  // ── ejercicios 41-100: más práctica variada ────────────────────────
  {
    id: 'mn-b-041',
    nivel: 'muy-novato',
    titulo: 'Empleados de Marketing o RRHH',
    descripcion: 'Muestra nombre y departamento de empleados de Marketing o RRHH usando IN.',
    objetivo: 'Usar IN con múltiples valores de texto.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','departamento'],
      filas: [['Ana','RRHH'],['Sofía','Marketing'],['Elena','RRHH'],['Andrés','Marketing']],
    },
    solucionOficial: "SELECT nombre, departamento FROM empleados WHERE departamento IN ('Marketing', 'RRHH');",
    solucionesAlternativas: [],
    explicacion: "IN ('Marketing', 'RRHH') es más limpio que usar OR con dos condiciones separadas.",
    pistas: ["Usa IN ('Marketing', 'RRHH')"],
    retroalimentacionError: "WHERE departamento IN ('Marketing', 'RRHH')",
  },
  {
    id: 'mn-b-042',
    nivel: 'muy-novato',
    titulo: 'Top 5 productos más caros',
    descripcion: 'Muestra nombre y precio de los 5 productos más caros.',
    objetivo: 'Combinar ORDER BY DESC con LIMIT 5.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','precio'],
      filas: [['Laptop Pro 15',1299.99],['Escritorio Ajustable',599.99],['Monitor 27 4K',499.99],['Tablet Pro',399.99],['Silla Ergonómica',349.99]],
    },
    solucionOficial: 'SELECT nombre, precio FROM productos ORDER BY precio DESC LIMIT 5;',
    solucionesAlternativas: [],
    explicacion: 'ORDER BY precio DESC ordena de más caro a más barato. LIMIT 5 toma los 5 primeros.',
    pistas: ['ORDER BY precio DESC', 'LIMIT 5'],
    retroalimentacionError: 'ORDER BY precio DESC LIMIT 5',
  },
  {
    id: 'mn-b-043',
    nivel: 'muy-novato',
    titulo: 'Clientes cuyo email contiene "gmail"',
    descripcion: 'Muestra nombre y email de clientes que usan Gmail.',
    objetivo: 'Usar LIKE con patrón intermedio.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','email'],
      filas: [['Ana','ana@gmail.com'],['Carlos','carlos@gmail.com'],['Eva','eva@gmail.com'],['Gabi','gabi@gmail.com'],['Isabel','isabel@gmail.com'],['Jack','jack@gmail.com']],
    },
    solucionOficial: "SELECT nombre, email FROM clientes WHERE email LIKE '%gmail%';",
    solucionesAlternativas: [],
    explicacion: "'%gmail%' encuentra 'gmail' en cualquier posición del email.",
    pistas: ["LIKE '%gmail%' busca gmail en cualquier parte"],
    retroalimentacionError: "WHERE email LIKE '%gmail%'",
  },
  {
    id: 'mn-b-044',
    nivel: 'muy-novato',
    titulo: 'Empleado mejor pagado de Ventas',
    descripcion: 'Muestra nombre y salario del empleado de Ventas con mayor salario.',
    objetivo: 'Combinar WHERE con ORDER BY DESC LIMIT 1.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','salario'],
      filas: [['María',45000]],
    },
    solucionOficial: "SELECT nombre, salario FROM empleados WHERE departamento = 'Ventas' ORDER BY salario DESC LIMIT 1;",
    solucionesAlternativas: [],
    explicacion: "Primero filtramos por departamento = 'Ventas', luego ordenamos por salario descendente y tomamos el primero.",
    pistas: ["WHERE departamento = 'Ventas'", 'ORDER BY salario DESC LIMIT 1'],
    retroalimentacionError: "WHERE departamento = 'Ventas' ORDER BY salario DESC LIMIT 1",
  },
  {
    id: 'mn-b-045',
    nivel: 'muy-novato',
    titulo: 'Productos de Electrónica ordenados por precio',
    descripcion: 'Muestra nombre y precio de productos de Electrónica, de más barato a más caro.',
    objetivo: 'Combinar WHERE con ORDER BY ASC.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','precio'],
      filas: [['Tablet Pro',399.99],['Monitor 27 4K',499.99],['Laptop Pro 15',1299.99]],
    },
    solucionOficial: "SELECT nombre, precio FROM productos WHERE categoria = 'Electrónica' ORDER BY precio ASC;",
    solucionesAlternativas: [],
    explicacion: "Filtramos por categoría y luego ordenamos por precio ascendente.",
    pistas: ["WHERE categoria = 'Electrónica'", 'ORDER BY precio ASC'],
    retroalimentacionError: "WHERE categoria = 'Electrónica' ORDER BY precio ASC",
  },
  {
    id: 'mn-b-046',
    nivel: 'muy-novato',
    titulo: 'Empleados cuyo nombre tiene 3 letras',
    descripcion: 'Muestra nombre de empleados cuyo nombre tiene exactamente 3 caracteres.',
    objetivo: 'Usar LIKE con _ (guión bajo) para caracteres individuales.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre'],
      filas: [['Ana'],['Eva']],
    },
    solucionOficial: "SELECT nombre FROM empleados WHERE nombre LIKE '___';",
    solucionesAlternativas: [],
    explicacion: "Cada _ representa un solo carácter. '___' busca nombres de exactamente 3 caracteres. Ana y Eva tienen 3 letras.",
    pistas: ["Usa LIKE '___' (tres guiones bajos) para 3 caracteres"],
    retroalimentacionError: "WHERE nombre LIKE '___'",
  },
  {
    id: 'mn-b-047',
    nivel: 'muy-novato',
    titulo: 'Clientes de USA o UK',
    descripcion: 'Muestra nombre, ciudad y país de clientes de USA o UK.',
    objetivo: 'Usar IN con países.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','ciudad','pais'],
      filas: [['Bob','Nueva York','USA'],['Frank','Londres','UK'],['Jack','Los Ángeles','USA']],
    },
    solucionOficial: "SELECT nombre, ciudad, pais FROM clientes WHERE pais IN ('USA', 'UK');",
    solucionesAlternativas: [],
    explicacion: "IN ('USA', 'UK') filtra clientes de ambos países.",
    pistas: ["WHERE pais IN ('USA', 'UK')"],
    retroalimentacionError: "WHERE pais IN ('USA', 'UK')",
  },
  {
    id: 'mn-b-048',
    nivel: 'muy-novato',
    titulo: 'Productos con stock entre 20 y 100',
    descripcion: 'Muestra nombre y stock de productos con stock entre 20 y 100 (inclusive).',
    objetivo: 'Usar BETWEEN con stock.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','stock'],
      filas: [['Laptop Pro 15',20],['Teclado Mecánico',80],['Webcam HD',100],['Tablet Pro',25],['Impresora Laser',30]],
    },
    solucionOficial: 'SELECT nombre, stock FROM productos WHERE stock BETWEEN 20 AND 100;',
    solucionesAlternativas: [],
    explicacion: 'BETWEEN 20 AND 100 incluye ambos extremos: 20 y 100.',
    pistas: ['WHERE stock BETWEEN 20 AND 100'],
    retroalimentacionError: 'WHERE stock BETWEEN 20 AND 100',
  },
  {
    id: 'mn-b-049',
    nivel: 'muy-novato',
    titulo: 'Empleados cuyo email empieza con "m"',
    descripcion: 'Muestra nombre y email de empleados cuyo email empieza con la letra m (minúscula).',
    objetivo: 'Usar LIKE con patrón de inicio en email.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','email'],
      filas: [['María','maria@tecnomart.com'],['Miguel','miguel@tecnomart.com']],
    },
    solucionOficial: "SELECT nombre, email FROM empleados WHERE email LIKE 'm%';",
    solucionesAlternativas: [],
    explicacion: "'m%' busca emails que empiecen con m minúscula.",
    pistas: ["WHERE email LIKE 'm%'"],
    retroalimentacionError: "WHERE email LIKE 'm%'",
  },
  {
    id: 'mn-b-050',
    nivel: 'muy-novato',
    titulo: 'Último empleado contratado',
    descripcion: 'Muestra nombre y fecha_contrato del empleado contratado más recientemente.',
    objetivo: 'Usar ORDER BY DESC con fechas y LIMIT 1.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','fecha_contrato'],
      filas: [['Javier','2022-02-14']],
    },
    solucionOficial: 'SELECT nombre, fecha_contrato FROM empleados ORDER BY fecha_contrato DESC LIMIT 1;',
    solucionesAlternativas: [],
    explicacion: 'ORDER BY fecha_contrato DESC ordena de más reciente a más antiguo. LIMIT 1 toma el primero.',
    pistas: ['ORDER BY fecha_contrato DESC', 'LIMIT 1'],
    retroalimentacionError: 'ORDER BY fecha_contrato DESC LIMIT 1',
  },
  {
    id: 'mn-b-051',
    nivel: 'muy-novato',
    titulo: 'Productos que NO son de Periféricos',
    descripcion: 'Muestra nombre y categoría de productos que no son de la categoría Periféricos.',
    objetivo: 'Usar != con texto.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','categoria'],
      filas: [['Laptop Pro 15','Electrónica'],['Monitor 27 4K','Electrónica'],['Tablet Pro','Electrónica'],['Silla Ergonómica','Mobiliario'],['Escritorio Ajustable','Mobiliario'],['Impresora Laser','Oficina']],
    },
    solucionOficial: "SELECT nombre, categoria FROM productos WHERE categoria != 'Periféricos';",
    solucionesAlternativas: ["SELECT nombre, categoria FROM productos WHERE categoria <> 'Periféricos';"],
    explicacion: "!= 'Periféricos' excluye todos los productos de esa categoría.",
    pistas: ["WHERE categoria != 'Periféricos'"],
    retroalimentacionError: "WHERE categoria != 'Periféricos'",
  },
  {
    id: 'mn-b-052',
    nivel: 'muy-novato',
    titulo: 'Empleados de Tecnología ordenados por salario',
    descripcion: 'Muestra nombre y salario de empleados de Tecnología, de mayor a menor salario.',
    objetivo: 'Combinar WHERE con ORDER BY DESC.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','salario'],
      filas: [['Laura',70000],['Carlos',65000],['Miguel',60000]],
    },
    solucionOficial: "SELECT nombre, salario FROM empleados WHERE departamento = 'Tecnología' ORDER BY salario DESC;",
    solucionesAlternativas: [],
    explicacion: "Filtramos por Tecnología y ordenamos por salario descendente.",
    pistas: ["WHERE departamento = 'Tecnología'", 'ORDER BY salario DESC'],
    retroalimentacionError: "WHERE departamento = 'Tecnología' ORDER BY salario DESC",
  },
  {
    id: 'mn-b-053',
    nivel: 'muy-novato',
    titulo: 'Clientes cuyo nombre contiene la letra "a"',
    descripcion: 'Muestra nombre de clientes cuya nombre contiene la letra "a" minúscula.',
    objetivo: 'Usar LIKE con % en ambos lados.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre'],
      filas: [['Ana'],['Carlos'],['Diana'],['Eva'],['Frank'],['Gabi'],['Isabel'],['Jack']],
    },
    solucionOficial: "SELECT nombre FROM clientes WHERE nombre LIKE '%a%';",
    solucionesAlternativas: [],
    explicacion: "'%a%' busca la letra 'a' en cualquier posición del nombre.",
    pistas: ["LIKE '%a%' busca 'a' en cualquier parte"],
    retroalimentacionError: "WHERE nombre LIKE '%a%'",
  },
  {
    id: 'mn-b-054',
    nivel: 'muy-novato',
    titulo: 'Productos con precio mayor a $200 y stock menor a 30',
    descripcion: 'Muestra nombre, precio y stock de productos caros con poco stock.',
    objetivo: 'Usar AND con dos condiciones de comparación.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','precio','stock'],
      filas: [['Laptop Pro 15',1299.99,20],['Monitor 27 4K',499.99,15],['Tablet Pro',399.99,25]],
    },
    solucionOficial: 'SELECT nombre, precio, stock FROM productos WHERE precio > 200 AND stock < 30;',
    solucionesAlternativas: [],
    explicacion: 'Ambas condiciones deben cumplirse: precio > 200 Y stock < 30.',
    pistas: ['WHERE precio > 200 AND stock < 30'],
    retroalimentacionError: 'WHERE precio > 200 AND stock < 30',
  },
  {
    id: 'mn-b-055',
    nivel: 'muy-novato',
    titulo: 'Empleados contratados antes de 2020',
    descripcion: 'Muestra nombre y fecha_contrato de empleados contratados antes del 2020-01-01.',
    objetivo: 'Usar < con fechas.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','fecha_contrato'],
      filas: [['Carlos','2019-06-01'],['Laura','2018-11-05'],['Andrés','2019-12-01']],
    },
    solucionOficial: "SELECT nombre, fecha_contrato FROM empleados WHERE fecha_contrato < '2020-01-01';",
    solucionesAlternativas: [],
    explicacion: "Las fechas se comparan como texto en formato YYYY-MM-DD. '<' devuelve fechas anteriores.",
    pistas: ["WHERE fecha_contrato < '2020-01-01'"],
    retroalimentacionError: "WHERE fecha_contrato < '2020-01-01'",
  },
  {
    id: 'mn-b-056',
    nivel: 'muy-novato',
    titulo: 'Productos ordenados por categoría y luego precio',
    descripcion: 'Muestra nombre, categoría y precio de todos los productos, ordenados por categoría y dentro de cada categoría por precio descendente.',
    objetivo: 'Usar ORDER BY con múltiples columnas.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','categoria','precio'],
      filas: [
        ['Laptop Pro 15','Electrónica',1299.99],['Monitor 27 4K','Electrónica',499.99],['Tablet Pro','Electrónica',399.99],
        ['Escritorio Ajustable','Mobiliario',599.99],['Silla Ergonómica','Mobiliario',349.99],
        ['Impresora Laser','Oficina',299.99],
        ['Auriculares Bluetooth','Periféricos',149.99],['Teclado Mecánico','Periféricos',89.99],['Webcam HD','Periféricos',79.99],['Mouse Inalámbrico','Periféricos',29.99],
      ],
    },
    solucionOficial: 'SELECT nombre, categoria, precio FROM productos ORDER BY categoria ASC, precio DESC;',
    solucionesAlternativas: [],
    explicacion: 'Primero ordena por categoría alfabéticamente, luego por precio descendente dentro de cada categoría.',
    pistas: ['ORDER BY categoria ASC, precio DESC'],
    retroalimentacionError: 'ORDER BY categoria ASC, precio DESC',
  },
  {
    id: 'mn-b-057',
    nivel: 'muy-novato',
    titulo: 'Empleados activos de Ventas o Tecnología',
    descripcion: 'Muestra nombre y departamento de empleados activos que trabajan en Ventas o Tecnología.',
    objetivo: 'Combinar AND con IN.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','departamento'],
      filas: [['María','Ventas'],['Carlos','Tecnología'],['Pedro','Ventas'],['Laura','Tecnología'],['Miguel','Tecnología'],['Javier','Ventas']],
    },
    solucionOficial: "SELECT nombre, departamento FROM empleados WHERE activo = 1 AND departamento IN ('Ventas', 'Tecnología');",
    solucionesAlternativas: [],
    explicacion: "activo = 1 filtra activos, e IN filtra los dos departamentos. Ambas condiciones con AND.",
    pistas: ['WHERE activo = 1', "AND departamento IN ('Ventas', 'Tecnología')"],
    retroalimentacionError: "WHERE activo = 1 AND departamento IN ('Ventas', 'Tecnología')",
  },
  {
    id: 'mn-b-058',
    nivel: 'muy-novato',
    titulo: 'Clientes de Alemania o Japón',
    descripcion: 'Muestra nombre y país de clientes de Alemania o Japón.',
    objetivo: 'Usar OR con texto.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','pais'],
      filas: [['Diana','Japón'],['Eva','Alemania'],['Hiro','Japón']],
    },
    solucionOficial: "SELECT nombre, pais FROM clientes WHERE pais = 'Alemania' OR pais = 'Japón';",
    solucionesAlternativas: ["SELECT nombre, pais FROM clientes WHERE pais IN ('Alemania', 'Japón');"],
    explicacion: "OR devuelve filas donde al menos una condición es verdadera.",
    pistas: ["WHERE pais = 'Alemania' OR pais = 'Japón'"],
    retroalimentacionError: "WHERE pais = 'Alemania' OR pais = 'Japón'",
  },
  {
    id: 'mn-b-059',
    nivel: 'muy-novato',
    titulo: 'Salario promedio de Tecnología',
    descripcion: 'Muestra el nombre y salario de empleados de Tecnología que ganan más del promedio. (Pista: el promedio de Tecnología es 65000).',
    objetivo: 'Practicar WHERE con valor numérico específico.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','salario'],
      filas: [['Laura',70000]],
    },
    solucionOficial: "SELECT nombre, salario FROM empleados WHERE departamento = 'Tecnología' AND salario > 65000;",
    solucionesAlternativas: [],
    explicacion: "Solo Laura gana más de 65000 en Tecnología.",
    pistas: ["WHERE departamento = 'Tecnología' AND salario > 65000"],
    retroalimentacionError: "WHERE departamento = 'Tecnología' AND salario > 65000",
  },
  {
    id: 'mn-b-060',
    nivel: 'muy-novato',
    titulo: 'Productos con stock exactamente 100',
    descripcion: 'Muestra nombre y stock de productos con stock igual a 100.',
    objetivo: 'Usar = con números exactos.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','stock'],
      filas: [['Webcam HD',100]],
    },
    solucionOficial: 'SELECT nombre, stock FROM productos WHERE stock = 100;',
    solucionesAlternativas: [],
    explicacion: '= 100 filtra solo productos con stock exactamente 100.',
    pistas: ['WHERE stock = 100'],
    retroalimentacionError: 'WHERE stock = 100',
  },
  {
    id: 'mn-b-061',
    nivel: 'muy-novato',
    titulo: 'Empleados cuyo apellido contiene "ez"',
    descripcion: 'Muestra nombre y apellido de empleados cuyo apellido contiene "ez".',
    objetivo: 'Usar LIKE con patrón intermedio.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','apellido'],
      filas: [['María','González'],['Carlos','López'],['Pedro','Sánchez'],['Javier','García'],['Andrés','Jiménez']],
    },
    solucionOficial: "SELECT nombre, apellido FROM empleados WHERE apellido LIKE '%ez%';",
    solucionesAlternativas: [],
    explicacion: "'%ez%' busca 'ez' en cualquier posición del apellido.",
    pistas: ["LIKE '%ez%'"],
    retroalimentacionError: "WHERE apellido LIKE '%ez%'",
  },
  {
    id: 'mn-b-062',
    nivel: 'muy-novato',
    titulo: 'Top 3 productos más baratos de Periféricos',
    descripcion: 'Muestra nombre y precio de los 3 productos más baratos de la categoría Periféricos.',
    objetivo: 'Combinar WHERE, ORDER BY ASC y LIMIT.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','precio'],
      filas: [['Mouse Inalámbrico',29.99],['Webcam HD',79.99],['Teclado Mecánico',89.99]],
    },
    solucionOficial: "SELECT nombre, precio FROM productos WHERE categoria = 'Periféricos' ORDER BY precio ASC LIMIT 3;",
    solucionesAlternativas: [],
    explicacion: "Filtramos por Periféricos, ordenamos ascendente y tomamos los 3 primeros.",
    pistas: ["WHERE categoria = 'Periféricos'", 'ORDER BY precio ASC LIMIT 3'],
    retroalimentacionError: "WHERE categoria = 'Periféricos' ORDER BY precio ASC LIMIT 3",
  },
  {
    id: 'mn-b-063',
    nivel: 'muy-novato',
    titulo: 'Clientes cuyo email termina en ".com"',
    descripcion: 'Muestra nombre y email de clientes con email .com.',
    objetivo: 'Usar LIKE con patrón de final.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','email'],
      filas: [['Ana','ana@gmail.com'],['Bob','bob@hotmail.com'],['Carlos','carlos@gmail.com'],['Eva','eva@gmail.com'],['Frank','frank@outlook.com'],['Gabi','gabi@gmail.com'],['Isabel','isabel@gmail.com'],['Jack','jack@gmail.com']],
    },
    solucionOficial: "SELECT nombre, email FROM clientes WHERE email LIKE '%.com';",
    solucionesAlternativas: [],
    explicacion: "'%.com' busca emails que terminen en .com. Excluye hiro@mail.jp.",
    pistas: ["LIKE '%.com'"],
    retroalimentacionError: "WHERE email LIKE '%.com'",
  },
  {
    id: 'mn-b-064',
    nivel: 'muy-novato',
    titulo: 'Empleados con salario entre 45000 y 55000',
    descripcion: 'Muestra nombre y salario de empleados con salario en ese rango, ordenados por salario.',
    objetivo: 'Usar BETWEEN con ORDER BY.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','salario'],
      filas: [['María',45000],['Javier',44000],['Ana',48000],['Elena',50000],['Sofía',52000],['Andrés',55000]],
    },
    solucionOficial: 'SELECT nombre, salario FROM empleados WHERE salario BETWEEN 44000 AND 55000 ORDER BY salario ASC;',
    solucionesAlternativas: [],
    explicacion: 'BETWEEN filtra el rango, ORDER BY ordena los resultados.',
    pistas: ['WHERE salario BETWEEN 44000 AND 55000', 'ORDER BY salario ASC'],
    retroalimentacionError: 'WHERE salario BETWEEN 44000 AND 55000 ORDER BY salario ASC',
  },
  {
    id: 'mn-b-065',
    nivel: 'muy-novato',
    titulo: 'Productos de Mobiliario con precio mayor a $400',
    descripcion: 'Muestra nombre y precio de productos de Mobiliario que cuesten más de $400.',
    objetivo: 'Combinar WHERE con AND.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','precio'],
      filas: [['Escritorio Ajustable',599.99]],
    },
    solucionOficial: "SELECT nombre, precio FROM productos WHERE categoria = 'Mobiliario' AND precio > 400;",
    solucionesAlternativas: [],
    explicacion: "Solo el Escritorio Ajustable cumple ambas condiciones.",
    pistas: ["WHERE categoria = 'Mobiliario' AND precio > 400"],
    retroalimentacionError: "WHERE categoria = 'Mobiliario' AND precio > 400",
  },
  {
    id: 'mn-b-066',
    nivel: 'muy-novato',
    titulo: 'Empleados cuyo nombre empieza con M o A',
    descripcion: 'Muestra nombre de empleados cuyo nombre empieza con M o A.',
    objetivo: 'Usar OR con LIKE.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre'],
      filas: [['María'],['Ana'],['Andrés']],
    },
    solucionOficial: "SELECT nombre FROM empleados WHERE nombre LIKE 'M%' OR nombre LIKE 'A%';",
    solucionesAlternativas: [],
    explicacion: "Cada LIKE busca un patrón diferente, OR los combina.",
    pistas: ["WHERE nombre LIKE 'M%' OR nombre LIKE 'A%'"],
    retroalimentacionError: "WHERE nombre LIKE 'M%' OR nombre LIKE 'A%'",
  },
  {
    id: 'mn-b-067',
    nivel: 'muy-novato',
    titulo: 'Clientes ordenados por país y luego nombre',
    descripcion: 'Muestra nombre y país de todos los clientes, ordenados por país y luego por nombre.',
    objetivo: 'ORDER BY múltiple con texto.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','pais'],
      filas: [['Eva','Alemania'],['Gabi','Argentina'],['Ana','España'],['Isabel','España'],['Diana','Japón'],['Hiro','Japón'],['Carlos','México'],['Frank','UK'],['Bob','USA'],['Jack','USA']],
    },
    solucionOficial: 'SELECT nombre, pais FROM clientes ORDER BY pais ASC, nombre ASC;',
    solucionesAlternativas: [],
    explicacion: 'Primero ordena por país, luego por nombre dentro de cada país.',
    pistas: ['ORDER BY pais ASC, nombre ASC'],
    retroalimentacionError: 'ORDER BY pais ASC, nombre ASC',
  },
  {
    id: 'mn-b-068',
    nivel: 'muy-novato',
    titulo: 'Empleados no activos',
    descripcion: 'Muestra nombre, departamento y fecha_contrato de empleados que NO están activos.',
    objetivo: 'Filtrar por activo = 0 con más columnas.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','departamento','fecha_contrato'],
      filas: [['Andrés','Marketing','2019-12-01']],
    },
    solucionOficial: 'SELECT nombre, departamento, fecha_contrato FROM empleados WHERE activo = 0;',
    solucionesAlternativas: [],
    explicacion: 'activo = 0 filtra empleados inactivos.',
    pistas: ['WHERE activo = 0'],
    retroalimentacionError: 'WHERE activo = 0',
  },
  {
    id: 'mn-b-069',
    nivel: 'muy-novato',
    titulo: 'Productos cuyo nombre tiene más de 10 caracteres',
    descripcion: 'Muestra nombre de productos cuyo nombre tiene más de 10 caracteres. (Pista: usa LENGTH).',
    objetivo: 'Usar LENGTH() en WHERE.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre'],
      filas: [['Laptop Pro 15'],['Mouse Inalámbrico'],['Teclado Mecánico'],['Monitor 27 4K'],['Auriculares Bluetooth'],['Silla Ergonómica'],['Escritorio Ajustable'],['Impresora Laser']],
    },
    solucionOficial: 'SELECT nombre FROM productos WHERE LENGTH(nombre) > 10;',
    solucionesAlternativas: [],
    explicacion: 'LENGTH() devuelve la cantidad de caracteres de un texto.',
    pistas: ['WHERE LENGTH(nombre) > 10'],
    retroalimentacionError: 'WHERE LENGTH(nombre) > 10',
  },
  {
    id: 'mn-b-070',
    nivel: 'muy-novato',
    titulo: 'Empleados de RRHH, Marketing o Ventas con salario bajo',
    descripcion: 'Muestra nombre, departamento y salario de empleados de RRHH, Marketing o Ventas que ganen menos de $53,000.',
    objetivo: 'Combinar IN con < y AND.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','departamento','salario'],
      filas: [['Ana','RRHH',48000],['Pedro','Ventas',42000],['Sofía','Marketing',52000],['Javier','Ventas',44000],['Elena','RRHH',50000]],
    },
    solucionOficial: "SELECT nombre, departamento, salario FROM empleados WHERE departamento IN ('RRHH', 'Marketing', 'Ventas') AND salario < 53000;",
    solucionesAlternativas: [],
    explicacion: "IN filtra los departamentos y < filtra el salario.",
    pistas: ["WHERE departamento IN ('RRHH', 'Marketing', 'Ventas')", 'AND salario < 53000'],
    retroalimentacionError: "WHERE departamento IN ('RRHH', 'Marketing', 'Ventas') AND salario < 53000",
  },
  {
    id: 'mn-b-071',
    nivel: 'muy-novato',
    titulo: 'Producto más caro de cada categoría',
    descripcion: 'Muestra el nombre y precio del producto más caro (solo el primero).',
    objetivo: 'ORDER BY DESC LIMIT 1 con precio.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','precio'],
      filas: [['Laptop Pro 15',1299.99]],
    },
    solucionOficial: 'SELECT nombre, precio FROM productos ORDER BY precio DESC LIMIT 1;',
    solucionesAlternativas: [],
    explicacion: 'ORDER BY precio DESC ordena de más caro a más barato, LIMIT 1 toma el primero.',
    pistas: ['ORDER BY precio DESC LIMIT 1'],
    retroalimentacionError: 'ORDER BY precio DESC LIMIT 1',
  },
  {
    id: 'mn-b-072',
    nivel: 'muy-novato',
    titulo: 'Empleados contratados en 2021',
    descripcion: 'Muestra nombre y fecha_contrato de empleados contratados en el año 2021.',
    objetivo: 'Usar BETWEEN con fechas de un año.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','fecha_contrato'],
      filas: [['Ana','2021-01-10'],['Sofía','2021-04-01']],
    },
    solucionOficial: "SELECT nombre, fecha_contrato FROM empleados WHERE fecha_contrato BETWEEN '2021-01-01' AND '2021-12-31';",
    solucionesAlternativas: ["SELECT nombre, fecha_contrato FROM empleados WHERE fecha_contrato LIKE '2021-%';"],
    explicacion: "BETWEEN con fechas del año 2021, o LIKE '2021-%' como alternativa.",
    pistas: ["BETWEEN '2021-01-01' AND '2021-12-31'"],
    retroalimentacionError: "WHERE fecha_contrato BETWEEN '2021-01-01' AND '2021-12-31'",
  },
  {
    id: 'mn-b-073',
    nivel: 'muy-novato',
    titulo: 'Clientes cuyo nombre tiene exactamente 3 letras',
    descripcion: 'Muestra nombre de clientes con nombres de 3 caracteres.',
    objetivo: 'Usar LIKE con tres guiones bajos.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre'],
      filas: [['Ana'],['Eva']],
    },
    solucionOficial: "SELECT nombre FROM clientes WHERE nombre LIKE '___';",
    solucionesAlternativas: [],
    explicacion: "Cada _ representa exactamente un carácter.",
    pistas: ["LIKE '___' (tres guiones bajos)"],
    retroalimentacionError: "WHERE nombre LIKE '___'",
  },
  {
    id: 'mn-b-074',
    nivel: 'muy-novato',
    titulo: 'Empleados con salario mayor a 50000 ordenados por nombre',
    descripcion: 'Muestra nombre y salario de empleados que ganan más de $50,000, ordenados alfabéticamente.',
    objetivo: 'WHERE con > y ORDER BY de texto.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','salario'],
      filas: [['Andrés',55000],['Carlos',65000],['Elena',50000],['Laura',70000],['Miguel',60000],['Sofía',52000]],
    },
    solucionOficial: 'SELECT nombre, salario FROM empleados WHERE salario > 50000 ORDER BY nombre ASC;',
    solucionesAlternativas: [],
    explicacion: 'Filtramos por salario y ordenamos alfabéticamente por nombre.',
    pistas: ['WHERE salario > 50000', 'ORDER BY nombre ASC'],
    retroalimentacionError: 'WHERE salario > 50000 ORDER BY nombre ASC',
  },
  {
    id: 'mn-b-075',
    nivel: 'muy-novato',
    titulo: 'Productos con stock entre 5 y 25',
    descripcion: 'Muestra nombre y stock de productos con stock bajo (5 a 25 inclusive).',
    objetivo: 'BETWEEN con valores pequeños.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','stock'],
      filas: [['Laptop Pro 15',20],['Monitor 27 4K',15],['Tablet Pro',25],['Silla Ergonómica',10],['Escritorio Ajustable',5]],
    },
    solucionOficial: 'SELECT nombre, stock FROM productos WHERE stock BETWEEN 5 AND 25;',
    solucionesAlternativas: [],
    explicacion: 'BETWEEN 5 AND 25 incluye ambos extremos.',
    pistas: ['WHERE stock BETWEEN 5 AND 25'],
    retroalimentacionError: 'WHERE stock BETWEEN 5 AND 25',
  },
  {
    id: 'mn-b-076',
    nivel: 'muy-novato',
    titulo: 'Empleados cuyo email contiene "tecnomart"',
    descripcion: 'Muestra nombre y email de todos los empleados (todos son de tecnomart).',
    objetivo: 'LIKE con dominio de email.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','email'],
      filas: [
        ['María','maria@tecnomart.com'],['Carlos','carlos@tecnomart.com'],['Ana','ana@tecnomart.com'],
        ['Pedro','pedro@tecnomart.com'],['Laura','laura@tecnomart.com'],['Miguel','miguel@tecnomart.com'],
        ['Sofía','sofia@tecnomart.com'],['Javier','javier@tecnomart.com'],['Elena','elena@tecnomart.com'],['Andrés','andres@tecnomart.com'],
      ],
    },
    solucionOficial: "SELECT nombre, email FROM empleados WHERE email LIKE '%@tecnomart.com';",
    solucionesAlternativas: [],
    explicacion: "'%@tecnomart.com' filtra emails del dominio tecnomart.",
    pistas: ["LIKE '%@tecnomart.com'"],
    retroalimentacionError: "WHERE email LIKE '%@tecnomart.com'",
  },
  {
    id: 'mn-b-077',
    nivel: 'muy-novato',
    titulo: 'Empleados de Ventas con salario menor a 45000',
    descripcion: 'Muestra nombre y salario de empleados de Ventas que ganen menos de $45,000.',
    objetivo: 'AND con = y <.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','salario'],
      filas: [['Pedro',42000]],
    },
    solucionOficial: "SELECT nombre, salario FROM empleados WHERE departamento = 'Ventas' AND salario < 45000;",
    solucionesAlternativas: [],
    explicacion: "Pedro es el único de Ventas que gana menos de 45000.",
    pistas: ["WHERE departamento = 'Ventas' AND salario < 45000"],
    retroalimentacionError: "WHERE departamento = 'Ventas' AND salario < 45000",
  },
  {
    id: 'mn-b-078',
    nivel: 'muy-novato',
    titulo: 'Productos ordenados por nombre',
    descripcion: 'Muestra nombre y precio de todos los productos ordenados alfabéticamente por nombre.',
    objetivo: 'ORDER BY ASC con texto.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','precio'],
      filas: [
        ['Auriculares Bluetooth',149.99],['Escritorio Ajustable',599.99],['Impresora Laser',299.99],
        ['Laptop Pro 15',1299.99],['Monitor 27 4K',499.99],['Mouse Inalámbrico',29.99],
        ['Silla Ergonómica',349.99],['Tablet Pro',399.99],['Teclado Mecánico',89.99],['Webcam HD',79.99],
      ],
    },
    solucionOficial: 'SELECT nombre, precio FROM productos ORDER BY nombre ASC;',
    solucionesAlternativas: [],
    explicacion: 'ORDER BY nombre ASC ordena alfabéticamente de la A a la Z.',
    pistas: ['ORDER BY nombre ASC'],
    retroalimentacionError: 'ORDER BY nombre ASC',
  },
  {
    id: 'mn-b-079',
    nivel: 'muy-novato',
    titulo: 'Clientes cuyo apellido empieza con G o P',
    descripcion: 'Muestra nombre y apellido de clientes cuyo apellido empieza con G o P.',
    objetivo: 'OR con LIKE.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','apellido'],
      filas: [['Ana','García'],['Javier','García'],['Gabi','López'],['Isabel','Pérez']],
    },
    solucionOficial: "SELECT nombre, apellido FROM clientes WHERE apellido LIKE 'G%' OR apellido LIKE 'P%';",
    solucionesAlternativas: [],
    explicacion: "Cada LIKE busca un patrón, OR los combina.",
    pistas: ["WHERE apellido LIKE 'G%' OR apellido LIKE 'P%'"],
    retroalimentacionError: "WHERE apellido LIKE 'G%' OR apellido LIKE 'P%'",
  },
  {
    id: 'mn-b-080',
    nivel: 'muy-novato',
    titulo: 'Empleados activos ordenados por fecha_contrato',
    descripcion: 'Muestra nombre y fecha_contrato de empleados activos, del más antiguo al más reciente.',
    objetivo: 'WHERE + ORDER BY ASC con fechas.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','fecha_contrato'],
      filas: [
        ['Laura','2018-11-05'],['Carlos','2019-06-01'],['Andrés','2019-12-01'],
        ['María','2020-03-15'],['Miguel','2020-07-15'],['Elena','2020-09-30'],
        ['Ana','2021-01-10'],['Sofía','2021-04-01'],['Javier','2022-02-14'],
      ],
    },
    solucionOficial: 'SELECT nombre, fecha_contrato FROM empleados WHERE activo = 1 ORDER BY fecha_contrato ASC;',
    solucionesAlternativas: [],
    explicacion: 'WHERE activo = 1 filtra activos, ORDER BY fecha_contrato ASC ordena de antiguo a reciente.',
    pistas: ['WHERE activo = 1', 'ORDER BY fecha_contrato ASC'],
    retroalimentacionError: 'WHERE activo = 1 ORDER BY fecha_contrato ASC',
  },
  {
    id: 'mn-b-081',
    nivel: 'muy-novato',
    titulo: 'Productos de Electrónica o Periféricos con precio < 100',
    descripcion: 'Muestra nombre, categoría y precio de productos baratos de esas categorías.',
    objetivo: 'IN con AND.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','categoria','precio'],
      filas: [['Mouse Inalámbrico','Periféricos',29.99],['Teclado Mecánico','Periféricos',89.99],['Webcam HD','Periféricos',79.99]],
    },
    solucionOficial: "SELECT nombre, categoria, precio FROM productos WHERE categoria IN ('Electrónica', 'Periféricos') AND precio < 100;",
    solucionesAlternativas: [],
    explicacion: "IN filtra categorías, AND precio < 100 filtra por precio.",
    pistas: ["WHERE categoria IN ('Electrónica', 'Periféricos')", 'AND precio < 100'],
    retroalimentacionError: "WHERE categoria IN ('Electrónica', 'Periféricos') AND precio < 100",
  },
  {
    id: 'mn-b-082',
    nivel: 'muy-novato',
    titulo: 'Empleados cuyo nombre termina en "a"',
    descripcion: 'Muestra nombre de empleados cuyo nombre termina con la letra "a".',
    objetivo: 'LIKE con % al final.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre'],
      filas: [['María'],['Ana'],['Laura'],['Sofía'],['Elena']],
    },
    solucionOficial: "SELECT nombre FROM empleados WHERE nombre LIKE '%a';",
    solucionesAlternativas: [],
    explicacion: "'%a' busca nombres que terminen en 'a'.",
    pistas: ["LIKE '%a'"],
    retroalimentacionError: "WHERE nombre LIKE '%a'",
  },
  {
    id: 'mn-b-083',
    nivel: 'muy-novato',
    titulo: 'Top 3 empleados más antiguos',
    descripcion: 'Muestra nombre y fecha_contrato de los 3 empleados contratados primero.',
    objetivo: 'ORDER BY ASC LIMIT 3 con fechas.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','fecha_contrato'],
      filas: [['Laura','2018-11-05'],['Carlos','2019-06-01'],['Andrés','2019-12-01']],
    },
    solucionOficial: 'SELECT nombre, fecha_contrato FROM empleados ORDER BY fecha_contrato ASC LIMIT 3;',
    solucionesAlternativas: [],
    explicacion: 'ORDER BY fecha_contrato ASC ordena de más antiguo a más reciente.',
    pistas: ['ORDER BY fecha_contrato ASC LIMIT 3'],
    retroalimentacionError: 'ORDER BY fecha_contrato ASC LIMIT 3',
  },
  {
    id: 'mn-b-084',
    nivel: 'muy-novato',
    titulo: 'Productos con stock mayor a 50',
    descripcion: 'Muestra nombre y stock de productos con stock mayor a 50.',
    objetivo: 'WHERE con >.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','stock'],
      filas: [['Mouse Inalámbrico',150],['Teclado Mecánico',80],['Webcam HD',100],['Auriculares Bluetooth',60]],
    },
    solucionOficial: 'SELECT nombre, stock FROM productos WHERE stock > 50;',
    solucionesAlternativas: [],
    explicacion: '> 50 filtra productos con stock estrictamente mayor a 50.',
    pistas: ['WHERE stock > 50'],
    retroalimentacionError: 'WHERE stock > 50',
  },
  {
    id: 'mn-b-085',
    nivel: 'muy-novato',
    titulo: 'Clientes de España ordenados por nombre',
    descripcion: 'Muestra nombre y ciudad de clientes de España, ordenados por nombre.',
    objetivo: 'WHERE con ORDER BY.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','ciudad'],
      filas: [['Ana','Madrid'],['Isabel','Madrid']],
    },
    solucionOficial: "SELECT nombre, ciudad FROM clientes WHERE pais = 'España' ORDER BY nombre ASC;",
    solucionesAlternativas: [],
    explicacion: "Filtramos por España y ordenamos alfabéticamente.",
    pistas: ["WHERE pais = 'España'", 'ORDER BY nombre ASC'],
    retroalimentacionError: "WHERE pais = 'España' ORDER BY nombre ASC",
  },
  {
    id: 'mn-b-086',
    nivel: 'muy-novato',
    titulo: 'Empleados de Marketing',
    descripcion: 'Muestra nombre, salario y fecha_contrato de todos los empleados de Marketing.',
    objetivo: 'WHERE con selección de columnas específicas.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','salario','fecha_contrato'],
      filas: [['Sofía',52000,'2021-04-01'],['Andrés',55000,'2019-12-01']],
    },
    solucionOficial: "SELECT nombre, salario, fecha_contrato FROM empleados WHERE departamento = 'Marketing';",
    solucionesAlternativas: [],
    explicacion: "Seleccionamos columnas específicas y filtramos por departamento.",
    pistas: ["WHERE departamento = 'Marketing'"],
    retroalimentacionError: "WHERE departamento = 'Marketing'",
  },
  {
    id: 'mn-b-087',
    nivel: 'muy-novato',
    titulo: 'Productos cuyo nombre contiene "Pro"',
    descripcion: 'Muestra nombre y precio de productos con "Pro" en el nombre, ordenados por precio.',
    objetivo: 'LIKE con ORDER BY.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','precio'],
      filas: [['Tablet Pro',399.99],['Laptop Pro 15',1299.99]],
    },
    solucionOficial: "SELECT nombre, precio FROM productos WHERE nombre LIKE '%Pro%' ORDER BY precio ASC;",
    solucionesAlternativas: [],
    explicacion: "'%Pro%' busca 'Pro' en cualquier posición, luego ordenamos por precio.",
    pistas: ["WHERE nombre LIKE '%Pro%'", 'ORDER BY precio ASC'],
    retroalimentacionError: "WHERE nombre LIKE '%Pro%' ORDER BY precio ASC",
  },
  {
    id: 'mn-b-088',
    nivel: 'muy-novato',
    titulo: 'Empleados con salario entre 60000 y 70000',
    descripcion: 'Muestra nombre y salario de empleados en ese rango salarial.',
    objetivo: 'BETWEEN con salarios altos.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','salario'],
      filas: [['Carlos',65000],['Miguel',60000],['Laura',70000],['Andrés',55000]],
    },
    solucionOficial: 'SELECT nombre, salario FROM empleados WHERE salario BETWEEN 55000 AND 70000 ORDER BY salario DESC;',
    solucionesAlternativas: [],
    explicacion: 'BETWEEN 55000 AND 70000 incluye ambos extremos.',
    pistas: ['WHERE salario BETWEEN 55000 AND 70000'],
    retroalimentacionError: 'WHERE salario BETWEEN 55000 AND 70000',
  },
  {
    id: 'mn-b-089',
    nivel: 'muy-novato',
    titulo: 'Clientes cuyo email usa Outlook',
    descripcion: 'Muestra nombre y email de clientes con email de Outlook.',
    objetivo: 'LIKE con dominio específico.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','email'],
      filas: [['Frank','frank@outlook.com']],
    },
    solucionOficial: "SELECT nombre, email FROM clientes WHERE email LIKE '%@outlook.com';",
    solucionesAlternativas: [],
    explicacion: "'%@outlook.com' filtra emails de Outlook.",
    pistas: ["LIKE '%@outlook.com'"],
    retroalimentacionError: "WHERE email LIKE '%@outlook.com'",
  },
  {
    id: 'mn-b-090',
    nivel: 'muy-novato',
    titulo: 'Empleados de Tecnología o Marketing activos',
    descripcion: 'Muestra nombre y departamento de empleados activos de Tecnología o Marketing.',
    objetivo: 'IN con AND.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','departamento'],
      filas: [['Carlos','Tecnología'],['Laura','Tecnología'],['Miguel','Tecnología'],['Sofía','Marketing']],
    },
    solucionOficial: "SELECT nombre, departamento FROM empleados WHERE activo = 1 AND departamento IN ('Tecnología', 'Marketing');",
    solucionesAlternativas: [],
    explicacion: "activo = 1 AND departamento IN filtra activos de esos departamentos.",
    pistas: ['WHERE activo = 1', "AND departamento IN ('Tecnología', 'Marketing')"],
    retroalimentacionError: "WHERE activo = 1 AND departamento IN ('Tecnología', 'Marketing')",
  },
  {
    id: 'mn-b-091',
    nivel: 'muy-novato',
    titulo: 'Productos con precio entre $100 y $500',
    descripcion: 'Muestra nombre y precio de productos en ese rango de precio, ordenados de más caro a más barato.',
    objetivo: 'BETWEEN con ORDER BY DESC.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','precio'],
      filas: [['Monitor 27 4K',499.99],['Tablet Pro',399.99],['Silla Ergonómica',349.99],['Impresora Laser',299.99],['Auriculares Bluetooth',149.99]],
    },
    solucionOficial: 'SELECT nombre, precio FROM productos WHERE precio BETWEEN 100 AND 500 ORDER BY precio DESC;',
    solucionesAlternativas: [],
    explicacion: 'BETWEEN 100 AND 500 filtra el rango, ORDER BY DESC ordena descendente.',
    pistas: ['WHERE precio BETWEEN 100 AND 500', 'ORDER BY precio DESC'],
    retroalimentacionError: 'WHERE precio BETWEEN 100 AND 500 ORDER BY precio DESC',
  },
  {
    id: 'mn-b-092',
    nivel: 'muy-novato',
    titulo: 'Empleados cuyo apellido tiene exactamente 6 letras',
    descripcion: 'Muestra nombre y apellido de empleados con apellidos de 6 caracteres.',
    objetivo: 'LIKE con 6 guiones bajos.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','apellido'],
      filas: [['Laura','Torres'],['Javier','García'],['Elena','Moreno']],
    },
    solucionOficial: "SELECT nombre, apellido FROM empleados WHERE apellido LIKE '______';",
    solucionesAlternativas: [],
    explicacion: "Seis guiones bajos = exactamente 6 caracteres.",
    pistas: ["LIKE '______' (6 guiones bajos)"],
    retroalimentacionError: "WHERE apellido LIKE '______'",
  },
  {
    id: 'mn-b-093',
    nivel: 'muy-novato',
    titulo: 'Clientes que no son de España ni México',
    descripcion: 'Muestra nombre y país de clientes que no son de España ni México.',
    objetivo: 'NOT IN para exclusión múltiple.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','pais'],
      filas: [['Bob','USA'],['Diana','Japón'],['Eva','Alemania'],['Frank','UK'],['Gabi','Argentina'],['Hiro','Japón'],['Jack','USA']],
    },
    solucionOficial: "SELECT nombre, pais FROM clientes WHERE pais NOT IN ('España', 'México');",
    solucionesAlternativas: [],
    explicacion: "NOT IN excluye los países listados.",
    pistas: ["WHERE pais NOT IN ('España', 'México')"],
    retroalimentacionError: "WHERE pais NOT IN ('España', 'México')",
  },
  {
    id: 'mn-b-094',
    nivel: 'muy-novato',
    titulo: 'Empleado con el salario más bajo',
    descripcion: 'Muestra nombre y salario del empleado que menos gana.',
    objetivo: 'ORDER BY ASC LIMIT 1.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','salario'],
      filas: [['Pedro',42000]],
    },
    solucionOficial: 'SELECT nombre, salario FROM empleados ORDER BY salario ASC LIMIT 1;',
    solucionesAlternativas: [],
    explicacion: 'ORDER BY salario ASC ordena de menor a mayor, LIMIT 1 toma el primero.',
    pistas: ['ORDER BY salario ASC LIMIT 1'],
    retroalimentacionError: 'ORDER BY salario ASC LIMIT 1',
  },
  {
    id: 'mn-b-095',
    nivel: 'muy-novato',
    titulo: 'Productos de Oficina o Mobiliario ordenados por precio',
    descripcion: 'Muestra nombre, categoría y precio de productos de Oficina o Mobiliario, ordenados por precio ascendente.',
    objetivo: 'IN con ORDER BY.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','categoria','precio'],
      filas: [['Impresora Laser','Oficina',299.99],['Silla Ergonómica','Mobiliario',349.99],['Escritorio Ajustable','Mobiliario',599.99]],
    },
    solucionOficial: "SELECT nombre, categoria, precio FROM productos WHERE categoria IN ('Oficina', 'Mobiliario') ORDER BY precio ASC;",
    solucionesAlternativas: [],
    explicacion: "IN filtra las categorías, ORDER BY ordena por precio.",
    pistas: ["WHERE categoria IN ('Oficina', 'Mobiliario')", 'ORDER BY precio ASC'],
    retroalimentacionError: "WHERE categoria IN ('Oficina', 'Mobiliario') ORDER BY precio ASC",
  },
  {
    id: 'mn-b-096',
    nivel: 'muy-novato',
    titulo: 'Empleados cuyo nombre contiene la letra "r"',
    descripcion: 'Muestra nombre de empleados cuyo nombre contiene "r" (minúscula).',
    objetivo: 'LIKE con patrón intermedio.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre'],
      filas: [['Carlos'],['Pedro'],['Laura'],['Andrés']],
    },
    solucionOficial: "SELECT nombre FROM empleados WHERE nombre LIKE '%r%';",
    solucionesAlternativas: [],
    explicacion: "'%r%' busca 'r' en cualquier posición.",
    pistas: ["LIKE '%r%'"],
    retroalimentacionError: "WHERE nombre LIKE '%r%'",
  },
  {
    id: 'mn-b-097',
    nivel: 'muy-novato',
    titulo: 'Productos con stock mayor a 10 y precio menor a $200',
    descripcion: 'Muestra nombre, stock y precio de productos con buen stock y precio accesible.',
    objetivo: 'AND con dos comparaciones numéricas.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','stock','precio'],
      filas: [['Mouse Inalámbrico',150,29.99],['Teclado Mecánico',80,89.99],['Webcam HD',100,79.99],['Auriculares Bluetooth',60,149.99]],
    },
    solucionOficial: 'SELECT nombre, stock, precio FROM productos WHERE stock > 10 AND precio < 200;',
    solucionesAlternativas: [],
    explicacion: 'Ambas condiciones numéricas deben cumplirse.',
    pistas: ['WHERE stock > 10 AND precio < 200'],
    retroalimentacionError: 'WHERE stock > 10 AND precio < 200',
  },
  {
    id: 'mn-b-098',
    nivel: 'muy-novato',
    titulo: 'Clientes de USA ordenados por nombre',
    descripcion: 'Muestra nombre y ciudad de clientes de USA, ordenados alfabéticamente.',
    objetivo: 'WHERE + ORDER BY con texto.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','ciudad'],
      filas: [['Bob','Nueva York'],['Jack','Los Ángeles']],
    },
    solucionOficial: "SELECT nombre, ciudad FROM clientes WHERE pais = 'USA' ORDER BY nombre ASC;",
    solucionesAlternativas: [],
    explicacion: "Filtramos por USA y ordenamos alfabéticamente.",
    pistas: ["WHERE pais = 'USA'", 'ORDER BY nombre ASC'],
    retroalimentacionError: "WHERE pais = 'USA' ORDER BY nombre ASC",
  },
  {
    id: 'mn-b-099',
    nivel: 'muy-novato',
    titulo: 'Empleados de Ventas contratados después de 2021',
    descripcion: 'Muestra nombre y fecha_contrato de empleados de Ventas contratados después del 2021-12-31.',
    objetivo: 'AND con fecha y texto.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['nombre','fecha_contrato'],
      filas: [['Javier','2022-02-14']],
    },
    solucionOficial: "SELECT nombre, fecha_contrato FROM empleados WHERE departamento = 'Ventas' AND fecha_contrato > '2021-12-31';",
    solucionesAlternativas: [],
    explicacion: "Javier es el único de Ventas contratado después de 2021.",
    pistas: ["WHERE departamento = 'Ventas'", "AND fecha_contrato > '2021-12-31'"],
    retroalimentacionError: "WHERE departamento = 'Ventas' AND fecha_contrato > '2021-12-31'",
  },
  {
    id: 'mn-b-100',
    nivel: 'muy-novato',
    titulo: 'Todos los departamentos únicos',
    descripcion: 'Muestra los nombres de todos los departamentos que existen en la empresa, sin repetir.',
    objetivo: 'Usar DISTINCT para valores únicos.',
    setupSql: SETUP_TECNOMART,
    resultadoEsperado: {
      columnas: ['departamento'],
      filas: [['Ventas'],['Tecnología'],['RRHH'],['Marketing']],
    },
    solucionOficial: 'SELECT DISTINCT departamento FROM empleados;',
    solucionesAlternativas: [],
    explicacion: 'DISTINCT elimina valores duplicados y devuelve solo los departamentos únicos.',
    pistas: ['Usa SELECT DISTINCT departamento'],
    retroalimentacionError: 'SELECT DISTINCT departamento FROM empleados',
  },
];
