import type { EjercicioBanco } from '../../types';

const SETUP = `
CREATE TABLE departamentos (id INTEGER PRIMARY KEY, nombre TEXT, presupuesto REAL, ciudad TEXT);
INSERT INTO departamentos VALUES (1,'Ventas',500000,'Madrid');
INSERT INTO departamentos VALUES (2,'Tecnología',800000,'Barcelona');
INSERT INTO departamentos VALUES (3,'RRHH',300000,'Madrid');
INSERT INTO departamentos VALUES (4,'Marketing',400000,'Madrid');
INSERT INTO departamentos VALUES (5,'Finanzas',350000,'Barcelona');
CREATE TABLE empleados (id INTEGER PRIMARY KEY, nombre TEXT, departamento_id INTEGER, salario REAL, fecha_contrato TEXT, activo INTEGER);
INSERT INTO empleados VALUES (1,'María',1,45000,'2020-03-15',1);
INSERT INTO empleados VALUES (2,'Carlos',2,65000,'2019-06-01',1);
INSERT INTO empleados VALUES (3,'Ana',3,48000,'2021-01-10',1);
INSERT INTO empleados VALUES (4,'Pedro',1,42000,'2022-08-20',1);
INSERT INTO empleados VALUES (5,'Laura',2,70000,'2018-11-05',1);
INSERT INTO empleados VALUES (6,'Miguel',2,60000,'2020-07-15',1);
INSERT INTO empleados VALUES (7,'Sofía',4,52000,'2021-04-01',1);
INSERT INTO empleados VALUES (8,'Javier',1,44000,'2022-02-14',1);
INSERT INTO empleados VALUES (9,'Elena',3,50000,'2020-09-30',1);
INSERT INTO empleados VALUES (10,'Andrés',4,55000,'2019-12-01',0);
CREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria_id INTEGER, precio REAL, stock INTEGER);
INSERT INTO productos VALUES (1,'Laptop Pro',1,1299.99,20);
INSERT INTO productos VALUES (2,'Mouse',2,29.99,150);
INSERT INTO productos VALUES (3,'Teclado',2,89.99,80);
INSERT INTO productos VALUES (4,'Monitor',1,499.99,15);
INSERT INTO productos VALUES (5,'Webcam',2,79.99,100);
INSERT INTO productos VALUES (6,'Tablet',1,399.99,25);
CREATE TABLE categorias (id INTEGER PRIMARY KEY, nombre TEXT);
INSERT INTO categorias VALUES (1,'Electrónica');
INSERT INTO categorias VALUES (2,'Periféricos');
CREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, empleado_id INTEGER, total REAL, fecha TEXT, estado TEXT);
INSERT INTO pedidos VALUES (1,1,1,599.99,'2024-01-05','completado');
INSERT INTO pedidos VALUES (2,2,2,1299.99,'2024-01-10','completado');
INSERT INTO pedidos VALUES (3,1,1,89.99,'2024-01-15','pendiente');
INSERT INTO pedidos VALUES (4,3,3,349.99,'2024-01-20','completado');
INSERT INTO pedidos VALUES (5,4,2,799.99,'2024-01-25','enviado');
CREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, pais TEXT, email TEXT);
INSERT INTO clientes VALUES (1,'Ana García','España','ana@mail.com');
INSERT INTO clientes VALUES (2,'Bob Smith','USA','bob@mail.com');
INSERT INTO clientes VALUES (3,'Carlos Ruiz','México','carlos@mail.com');
INSERT INTO clientes VALUES (4,'Diana Lee','Japón','diana@mail.com');
INSERT INTO clientes VALUES (5,'Eva Müller','Alemania','eva@mail.com');
`;

export const ejerciciosNovato: EjercicioBanco[] = [
  {
    id: 'no-b-001',
    nivel: 'novato',
    titulo: 'Total de empleados',
    descripcion: 'Cuenta el número total de empleados.',
    objetivo: 'Usar COUNT(*) para contar todas las filas.',
    setupSql: SETUP,
    resultadoEsperado: { columnas: ['total'], filas: [[10]] },
    solucionOficial: 'SELECT COUNT(*) AS total FROM empleados;',
    solucionesAlternativas: [],
    explicacion: 'COUNT(*) cuenta todas las filas incluyendo las de empleados inactivos.',
    pistas: ['Usa COUNT(*)', 'Alias AS total'],
    retroalimentacionError: 'SELECT COUNT(*) AS total FROM empleados',
  },
  {
    id: 'no-b-002',
    nivel: 'novato',
    titulo: 'Empleados activos',
    descripcion: 'Cuenta solo los empleados con activo = 1.',
    objetivo: 'Combinar COUNT con WHERE.',
    setupSql: SETUP,
    resultadoEsperado: { columnas: ['activos'], filas: [[9]] },
    solucionOficial: 'SELECT COUNT(*) AS activos FROM empleados WHERE activo = 1;',
    solucionesAlternativas: [],
    explicacion: 'WHERE activo = 1 filtra primero, luego COUNT cuenta los filtrados.',
    pistas: ['WHERE activo = 1', 'COUNT(*) AS activos'],
    retroalimentacionError: 'SELECT COUNT(*) AS activos FROM empleados WHERE activo = 1',
  },
  {
    id: 'no-b-003',
    nivel: 'novato',
    titulo: 'Suma total de salarios',
    descripcion: 'Calcula la suma de todos los salarios de los empleados.',
    objetivo: 'Usar SUM para sumar valores.',
    setupSql: SETUP,
    resultadoEsperado: { columnas: ['total_salarios'], filas: [[531000]] },
    solucionOficial: 'SELECT SUM(salario) AS total_salarios FROM empleados;',
    solucionesAlternativas: [],
    explicacion: 'SUM(salario) suma todos los salarios de la tabla.',
    pistas: ['Usa SUM(salario)'],
    retroalimentacionError: 'SELECT SUM(salario) AS total_salarios FROM empleados',
  },
  {
    id: 'no-b-004',
    nivel: 'novato',
    titulo: 'Salario promedio',
    descripcion: 'Calcula el salario promedio de todos los empleados.',
    objetivo: 'Usar AVG para calcular promedios.',
    setupSql: SETUP,
    resultadoEsperado: { columnas: ['salario_promedio'], filas: [[53100]] },
    solucionOficial: 'SELECT AVG(salario) AS salario_promedio FROM empleados;',
    solucionesAlternativas: [],
    explicacion: 'AVG(salario) calcula el promedio: 531000 / 10 = 53100.',
    pistas: ['Usa AVG(salario)'],
    retroalimentacionError: 'SELECT AVG(salario) AS salario_promedio FROM empleados',
  },
  {
    id: 'no-b-005',
    nivel: 'novato',
    titulo: 'Salario máximo y mínimo',
    descripcion: 'Muestra el salario más alto y el más bajo en la misma consulta.',
    objetivo: 'Combinar MAX y MIN en una consulta.',
    setupSql: SETUP,
    resultadoEsperado: { columnas: ['salario_max','salario_min'], filas: [[70000,42000]] },
    solucionOficial: 'SELECT MAX(salario) AS salario_max, MIN(salario) AS salario_min FROM empleados;',
    solucionesAlternativas: [],
    explicacion: 'MAX devuelve 70000 (Laura) y MIN devuelve 42000 (Pedro).',
    pistas: ['Usa MAX(salario) y MIN(salario) en el mismo SELECT'],
    retroalimentacionError: 'SELECT MAX(salario) AS salario_max, MIN(salario) AS salario_min FROM empleados',
  },
  {
    id: 'no-b-006',
    nivel: 'novato',
    titulo: 'Empleados por departamento',
    descripcion: 'Muestra cuántos empleados hay en cada departamento.',
    objetivo: 'Usar GROUP BY con COUNT.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['departamento_id','cantidad'],
      filas: [[1,3],[2,3],[3,2],[4,2]],
    },
    solucionOficial: 'SELECT departamento_id, COUNT(*) AS cantidad FROM empleados GROUP BY departamento_id ORDER BY departamento_id;',
    solucionesAlternativas: [],
    explicacion: 'GROUP BY departamento_id agrupa empleados por departamento y COUNT cuenta cada grupo.',
    pistas: ['GROUP BY departamento_id', 'COUNT(*) AS cantidad'],
    retroalimentacionError: 'SELECT departamento_id, COUNT(*) AS cantidad FROM empleados GROUP BY departamento_id',
  },
  {
    id: 'no-b-007',
    nivel: 'novato',
    titulo: 'Salario promedio por departamento',
    descripcion: 'Calcula el salario promedio para cada departamento.',
    objetivo: 'Combinar AVG con GROUP BY.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['departamento_id','salario_promedio'],
      filas: [[1,43666.666666666664],[2,65000],[3,49000],[4,53500]],
    },
    solucionOficial: 'SELECT departamento_id, AVG(salario) AS salario_promedio FROM empleados GROUP BY departamento_id ORDER BY departamento_id;',
    solucionesAlternativas: [],
    explicacion: 'AVG se calcula independientemente para cada grupo creado por GROUP BY.',
    pistas: ['AVG(salario) con GROUP BY departamento_id'],
    retroalimentacionError: 'SELECT departamento_id, AVG(salario) AS salario_promedio FROM empleados GROUP BY departamento_id',
  },
  {
    id: 'no-b-008',
    nivel: 'novato',
    titulo: 'Departamentos con más de 2 empleados',
    descripcion: 'Muestra los departamentos que tienen más de 2 empleados.',
    objetivo: 'Usar HAVING para filtrar grupos.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['departamento_id','cantidad'],
      filas: [[1,3],[2,3]],
    },
    solucionOficial: 'SELECT departamento_id, COUNT(*) AS cantidad FROM empleados GROUP BY departamento_id HAVING COUNT(*) > 2 ORDER BY departamento_id;',
    solucionesAlternativas: [],
    explicacion: 'HAVING filtra grupos después de que GROUP BY los crea. Solo los grupos con más de 2 empleados pasan.',
    pistas: ['HAVING COUNT(*) > 2 filtra grupos con más de 2'],
    retroalimentacionError: 'GROUP BY departamento_id HAVING COUNT(*) > 2',
  },
  {
    id: 'no-b-009',
    nivel: 'novato',
    titulo: 'Categorías de productos únicas',
    descripcion: 'Muestra los ids de categorías que aparecen en la tabla productos, sin duplicados.',
    objetivo: 'Usar DISTINCT para eliminar duplicados.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['categoria_id'],
      filas: [[1],[2]],
    },
    solucionOficial: 'SELECT DISTINCT categoria_id FROM productos ORDER BY categoria_id;',
    solucionesAlternativas: [],
    explicacion: 'DISTINCT elimina los valores duplicados de categoria_id.',
    pistas: ['Usa DISTINCT para valores únicos'],
    retroalimentacionError: 'SELECT DISTINCT categoria_id FROM productos',
  },
  {
    id: 'no-b-010',
    nivel: 'novato',
    titulo: 'INNER JOIN empleados con departamentos',
    descripcion: 'Muestra nombre del empleado y nombre de su departamento.',
    objetivo: 'Usar INNER JOIN para combinar dos tablas.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['empleado','departamento'],
      filas: [
        ['María','Ventas'],['Carlos','Tecnología'],['Ana','RRHH'],
        ['Pedro','Ventas'],['Laura','Tecnología'],['Miguel','Tecnología'],
        ['Sofía','Marketing'],['Javier','Ventas'],['Elena','RRHH'],['Andrés','Marketing'],
      ],
    },
    solucionOficial: 'SELECT e.nombre AS empleado, d.nombre AS departamento FROM empleados e INNER JOIN departamentos d ON e.departamento_id = d.id ORDER BY e.id;',
    solucionesAlternativas: [],
    explicacion: 'INNER JOIN conecta empleados con departamentos a través de departamento_id = id.',
    pistas: ['INNER JOIN departamentos d ON e.departamento_id = d.id', 'Usa alias e y d para las tablas'],
    retroalimentacionError: 'FROM empleados e INNER JOIN departamentos d ON e.departamento_id = d.id',
  },
  {
    id: 'no-b-011',
    nivel: 'novato',
    titulo: 'Productos con su categoría',
    descripcion: 'Muestra nombre del producto y nombre de su categoría.',
    objetivo: 'Practicar INNER JOIN en otra relación.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['producto','categoria'],
      filas: [
        ['Laptop Pro','Electrónica'],['Mouse','Periféricos'],['Teclado','Periféricos'],
        ['Monitor','Electrónica'],['Webcam','Periféricos'],['Tablet','Electrónica'],
      ],
    },
    solucionOficial: 'SELECT p.nombre AS producto, c.nombre AS categoria FROM productos p INNER JOIN categorias c ON p.categoria_id = c.id ORDER BY p.id;',
    solucionesAlternativas: [],
    explicacion: 'Conectamos productos con categorias a través de categoria_id = id.',
    pistas: ['INNER JOIN categorias c ON p.categoria_id = c.id'],
    retroalimentacionError: 'FROM productos p INNER JOIN categorias c ON p.categoria_id = c.id',
  },
  {
    id: 'no-b-012',
    nivel: 'novato',
    titulo: 'Pedidos con nombre de cliente',
    descripcion: 'Muestra id del pedido, nombre del cliente y total.',
    objetivo: 'JOIN entre pedidos y clientes.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['pedido_id','cliente','total'],
      filas: [
        [1,'Ana García',599.99],[2,'Bob Smith',1299.99],[3,'Ana García',89.99],
        [4,'Carlos Ruiz',349.99],[5,'Diana Lee',799.99],
      ],
    },
    solucionOficial: 'SELECT p.id AS pedido_id, c.nombre AS cliente, p.total FROM pedidos p INNER JOIN clientes c ON p.cliente_id = c.id ORDER BY p.id;',
    solucionesAlternativas: [],
    explicacion: 'JOIN entre pedidos y clientes por cliente_id = id del cliente.',
    pistas: ['INNER JOIN clientes c ON p.cliente_id = c.id'],
    retroalimentacionError: 'FROM pedidos p INNER JOIN clientes c ON p.cliente_id = c.id',
  },
  {
    id: 'no-b-013',
    nivel: 'novato',
    titulo: 'Clientes con o sin pedidos (LEFT JOIN)',
    descripcion: 'Muestra todos los clientes y, si tienen pedidos, el total. Los sin pedidos deben mostrar NULL.',
    objetivo: 'Usar LEFT JOIN para incluir todos los registros de la tabla izquierda.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['cliente','total_pedido'],
      filas: [
        ['Ana García',599.99],['Ana García',89.99],
        ['Bob Smith',1299.99],['Carlos Ruiz',349.99],
        ['Diana Lee',799.99],['Eva Müller',null],
      ],
    },
    solucionOficial: 'SELECT c.nombre AS cliente, p.total AS total_pedido FROM clientes c LEFT JOIN pedidos p ON c.id = p.cliente_id ORDER BY c.nombre, p.total;',
    solucionesAlternativas: [],
    explicacion: 'LEFT JOIN incluye todos los clientes. Eva Müller no tiene pedidos y aparece con NULL.',
    pistas: ['LEFT JOIN muestra todos los clientes aunque no tengan pedidos'],
    retroalimentacionError: 'FROM clientes c LEFT JOIN pedidos p ON c.id = p.cliente_id',
  },
  {
    id: 'no-b-014',
    nivel: 'novato',
    titulo: 'Clientes sin ningún pedido',
    descripcion: 'Muestra los clientes que no tienen ningún pedido registrado.',
    objetivo: 'Usar LEFT JOIN + WHERE IS NULL para encontrar sin coincidencia.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['cliente'],
      filas: [['Eva Müller']],
    },
    solucionOficial: 'SELECT c.nombre AS cliente FROM clientes c LEFT JOIN pedidos p ON c.id = p.cliente_id WHERE p.id IS NULL;',
    solucionesAlternativas: [],
    explicacion: 'LEFT JOIN + WHERE p.id IS NULL encuentra los clientes que no tienen ningún pedido.',
    pistas: ['LEFT JOIN + WHERE p.id IS NULL encuentra los que no tienen pareja'],
    retroalimentacionError: 'LEFT JOIN pedidos p ON c.id = p.cliente_id WHERE p.id IS NULL',
  },
  {
    id: 'no-b-015',
    nivel: 'novato',
    titulo: 'Total de ventas por empleado',
    descripcion: 'Muestra el nombre de cada empleado y el total de sus pedidos.',
    objetivo: 'Combinar JOIN con GROUP BY y SUM.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['empleado','total_ventas'],
      filas: [['María',689.98],['Carlos',2099.98],['Ana',349.99]],
    },
    solucionOficial: 'SELECT e.nombre AS empleado, SUM(p.total) AS total_ventas FROM empleados e INNER JOIN pedidos p ON e.id = p.empleado_id GROUP BY e.id, e.nombre ORDER BY total_ventas DESC;',
    solucionesAlternativas: [],
    explicacion: 'JOIN conecta empleados con pedidos. GROUP BY agrupa por empleado. SUM suma los totales de cada empleado.',
    pistas: ['INNER JOIN pedidos p ON e.id = p.empleado_id', 'GROUP BY e.id, e.nombre', 'SUM(p.total)'],
    retroalimentacionError: 'JOIN + GROUP BY e.id, e.nombre + SUM(p.total)',
  },
  // ── Ejercicios 16-45: temas variados ────────────────────────────
  {
    id: 'no-b-016',
    nivel: 'novato',
    titulo: 'COUNT con DISTINCT',
    descripcion: 'Cuenta cuántos departamentos distintos tienen empleados asignados.',
    objetivo: 'Usar COUNT(DISTINCT columna) para contar valores únicos.',
    setupSql: SETUP,
    resultadoEsperado: { columnas: ['num_departamentos'], filas: [[4]] },
    solucionOficial: 'SELECT COUNT(DISTINCT departamento_id) AS num_departamentos FROM empleados;',
    solucionesAlternativas: ['SELECT COUNT(*) AS num_departamentos FROM (SELECT DISTINCT departamento_id FROM empleados);'],
    explicacion: 'COUNT(DISTINCT departamento_id) cuenta cada valor diferente de departamento_id una sola vez, ignorando repeticiones.',
    pistas: ['Combina COUNT() con DISTINCT dentro del paréntesis', 'La sintaxis es COUNT(DISTINCT columna)', 'Usa el alias num_departamentos'],
    retroalimentacionError: 'Usa COUNT(DISTINCT departamento_id) AS num_departamentos FROM empleados',
  },
  {
    id: 'no-b-017',
    nivel: 'novato',
    titulo: 'DISTINCT + ORDER BY',
    descripcion: 'Lista los países de los clientes sin repetir, ordenados alfabéticamente.',
    objetivo: 'Combinar DISTINCT con ORDER BY para obtener listas únicas ordenadas.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['pais'],
      filas: [['Alemania'],['España'],['Japón'],['México'],['USA']],
    },
    solucionOficial: 'SELECT DISTINCT pais FROM clientes ORDER BY pais;',
    solucionesAlternativas: ['SELECT pais FROM clientes GROUP BY pais ORDER BY pais;'],
    explicacion: 'DISTINCT elimina los valores duplicados de la columna pais. ORDER BY los ordena alfabéticamente.',
    pistas: ['Usa SELECT DISTINCT pais', 'Añade ORDER BY pais al final', 'La tabla es clientes'],
    retroalimentacionError: 'SELECT DISTINCT pais FROM clientes ORDER BY pais',
  },
  {
    id: 'no-b-018',
    nivel: 'novato',
    titulo: 'SUM con WHERE',
    descripcion: 'Calcula la suma total de salarios solo de los empleados activos (activo = 1).',
    objetivo: 'Filtrar con WHERE antes de aplicar SUM.',
    setupSql: SETUP,
    resultadoEsperado: { columnas: ['total_activos'], filas: [[476000]] },
    solucionOficial: 'SELECT SUM(salario) AS total_activos FROM empleados WHERE activo = 1;',
    solucionesAlternativas: [],
    explicacion: 'WHERE activo = 1 filtra las filas antes de que SUM las sume. Andrés (activo = 0) queda excluido.',
    pistas: ['Usa SUM(salario) AS total_activos', 'Añade WHERE activo = 1 antes de agrupar', 'WHERE filtra ANTES de agregar'],
    retroalimentacionError: 'SELECT SUM(salario) AS total_activos FROM empleados WHERE activo = 1',
  },
  {
    id: 'no-b-019',
    nivel: 'novato',
    titulo: 'AVG con WHERE',
    descripcion: 'Calcula el salario promedio únicamente de los empleados del departamento de Tecnología (departamento_id = 2).',
    objetivo: 'Usar AVG con un filtro WHERE para un subconjunto de filas.',
    setupSql: SETUP,
    resultadoEsperado: { columnas: ['promedio'], filas: [[65000]] },
    solucionOficial: 'SELECT AVG(salario) AS promedio FROM empleados WHERE departamento_id = 2;',
    solucionesAlternativas: [],
    explicacion: 'Tecnología tiene 3 empleados: Carlos (65000), Laura (70000) y Miguel (60000). Promedio = 195000 / 3 = 65000.',
    pistas: ['Usa AVG(salario) AS promedio', 'WHERE departamento_id = 2 filtra solo Tecnología', 'La tabla es empleados'],
    retroalimentacionError: 'SELECT AVG(salario) AS promedio FROM empleados WHERE departamento_id = 2',
  },
  {
    id: 'no-b-020',
    nivel: 'novato',
    titulo: 'MIN y MAX con GROUP BY',
    descripcion: 'Muestra el salario mínimo y máximo de cada departamento.',
    objetivo: 'Usar MIN y MAX junto con GROUP BY para obtener extremos por grupo.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['departamento_id', 'salario_min', 'salario_max'],
      filas: [[1,42000,45000],[2,60000,70000],[3,48000,50000],[4,52000,55000]],
    },
    solucionOficial: 'SELECT departamento_id, MIN(salario) AS salario_min, MAX(salario) AS salario_max FROM empleados GROUP BY departamento_id ORDER BY departamento_id;',
    solucionesAlternativas: [],
    explicacion: 'GROUP BY crea un grupo por departamento. MIN y MAX calculan independientemente el mínimo y máximo dentro de cada grupo.',
    pistas: ['SELECT departamento_id, MIN(salario), MAX(salario)', 'Añade GROUP BY departamento_id', 'Ordena por departamento_id'],
    retroalimentacionError: 'GROUP BY departamento_id + MIN(salario) AS salario_min, MAX(salario) AS salario_max',
  },
  {
    id: 'no-b-021',
    nivel: 'novato',
    titulo: 'GROUP BY con dos columnas',
    descripcion: 'Cuenta cuántos empleados hay en cada combinación de departamento y estado (activo/inactivo).',
    objetivo: 'Agrupar por más de una columna con GROUP BY.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['departamento_id', 'activo', 'cantidad'],
      filas: [[1,1,3],[2,1,3],[3,1,2],[4,0,1],[4,1,1]],
    },
    solucionOficial: 'SELECT departamento_id, activo, COUNT(*) AS cantidad FROM empleados GROUP BY departamento_id, activo ORDER BY departamento_id, activo;',
    solucionesAlternativas: [],
    explicacion: 'GROUP BY departamento_id, activo crea un grupo por cada combinación única. El departamento 4 aparece dos veces: una para activo=0 (Andrés) y otra para activo=1 (Sofía).',
    pistas: ['GROUP BY departamento_id, activo — separa las columnas con coma', 'COUNT(*) cuenta las filas de cada grupo', 'ORDER BY departamento_id, activo para ordenar el resultado'],
    retroalimentacionError: 'GROUP BY departamento_id, activo — lista ambas columnas separadas por coma',
  },
  {
    id: 'no-b-022',
    nivel: 'novato',
    titulo: 'HAVING con AND',
    descripcion: 'Muestra los departamentos cuyo salario promedio supera 50000 Y que tienen más de 1 empleado.',
    objetivo: 'Usar HAVING con múltiples condiciones unidas por AND.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['departamento_id', 'empleados', 'promedio'],
      filas: [[2,3,65000],[4,2,53500]],
    },
    solucionOficial: 'SELECT departamento_id, COUNT(*) AS empleados, AVG(salario) AS promedio FROM empleados GROUP BY departamento_id HAVING AVG(salario) > 50000 AND COUNT(*) > 1 ORDER BY departamento_id;',
    solucionesAlternativas: [],
    explicacion: 'HAVING filtra grupos enteros. Con AND, ambas condiciones deben cumplirse. Ventas (avg 43667) y RRHH (avg 49000) no superan 50000, así que quedan fuera.',
    pistas: ['Agrupa con GROUP BY departamento_id', 'En HAVING usa AVG(salario) > 50000 AND COUNT(*) > 1', 'HAVING va después de GROUP BY'],
    retroalimentacionError: 'HAVING AVG(salario) > 50000 AND COUNT(*) > 1 — ambas condiciones en HAVING, no en WHERE',
  },
  {
    id: 'no-b-023',
    nivel: 'novato',
    titulo: 'INNER JOIN con filtro WHERE',
    descripcion: 'Muestra el nombre del empleado y el departamento, pero solo los que pertenecen a departamentos de Barcelona.',
    objetivo: 'Combinar INNER JOIN con un filtro WHERE sobre una columna de la tabla unida.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['empleado', 'departamento'],
      filas: [['Carlos','Tecnología'],['Laura','Tecnología'],['Miguel','Tecnología']],
    },
    solucionOficial: 'SELECT e.nombre AS empleado, d.nombre AS departamento FROM empleados e INNER JOIN departamentos d ON e.departamento_id = d.id WHERE d.ciudad = \'Barcelona\' ORDER BY e.nombre;',
    solucionesAlternativas: [],
    explicacion: 'El JOIN conecta empleados con departamentos. El WHERE filtra solo los departamentos de Barcelona (Tecnología y Finanzas). Como ningún empleado está en Finanzas, solo aparecen los de Tecnología.',
    pistas: ['INNER JOIN departamentos d ON e.departamento_id = d.id', 'WHERE d.ciudad = \'Barcelona\'', 'ORDER BY e.nombre'],
    retroalimentacionError: 'JOIN departamentos + WHERE d.ciudad = \'Barcelona\'',
  },
  {
    id: 'no-b-024',
    nivel: 'novato',
    titulo: 'Top 3 pedidos con LIMIT',
    descripcion: 'Muestra los 3 pedidos con mayor total, indicando el nombre del cliente.',
    objetivo: 'Usar INNER JOIN, ORDER BY DESC y LIMIT para obtener los N primeros registros.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['cliente', 'total'],
      filas: [['Bob Smith',1299.99],['Diana Lee',799.99],['Ana García',599.99]],
    },
    solucionOficial: 'SELECT c.nombre AS cliente, p.total FROM pedidos p INNER JOIN clientes c ON p.cliente_id = c.id ORDER BY p.total DESC LIMIT 3;',
    solucionesAlternativas: [],
    explicacion: 'ORDER BY p.total DESC ordena de mayor a menor. LIMIT 3 devuelve solo las 3 primeras filas del resultado.',
    pistas: ['INNER JOIN clientes c ON p.cliente_id = c.id', 'ORDER BY p.total DESC', 'Añade LIMIT 3 al final'],
    retroalimentacionError: 'JOIN clientes + ORDER BY p.total DESC + LIMIT 3',
  },
  {
    id: 'no-b-025',
    nivel: 'novato',
    titulo: 'LEFT JOIN con COUNT',
    descripcion: 'Muestra cada cliente y cuántos pedidos ha realizado. Incluye también a los clientes sin pedidos.',
    objetivo: 'Usar LEFT JOIN con GROUP BY y COUNT para incluir filas sin coincidencia.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['cliente', 'num_pedidos'],
      filas: [['Ana García',2],['Bob Smith',1],['Carlos Ruiz',1],['Diana Lee',1],['Eva Müller',0]],
    },
    solucionOficial: 'SELECT c.nombre AS cliente, COUNT(p.id) AS num_pedidos FROM clientes c LEFT JOIN pedidos p ON c.id = p.cliente_id GROUP BY c.id, c.nombre ORDER BY num_pedidos DESC, c.nombre;',
    solucionesAlternativas: [],
    explicacion: 'LEFT JOIN incluye todos los clientes. COUNT(p.id) devuelve 0 cuando p.id es NULL (sin pedidos), a diferencia de COUNT(*) que devolvería 1.',
    pistas: ['LEFT JOIN pedidos p ON c.id = p.cliente_id', 'COUNT(p.id) — no COUNT(*) — para que Eva Müller salga con 0', 'GROUP BY c.id, c.nombre'],
    retroalimentacionError: 'LEFT JOIN + COUNT(p.id) — usa COUNT(p.id) no COUNT(*) para contar 0 cuando no hay pedidos',
  },
  {
    id: 'no-b-026',
    nivel: 'novato',
    titulo: 'Anti-JOIN: empleados sin pedidos',
    descripcion: 'Muestra los empleados que no han gestionado ningún pedido.',
    objetivo: 'Usar LEFT JOIN + WHERE IS NULL para encontrar registros sin coincidencia (anti-join).',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['empleado'],
      filas: [['Andrés'],['Elena'],['Javier'],['Laura'],['Miguel'],['Pedro'],['Sofía']],
    },
    solucionOficial: 'SELECT e.nombre AS empleado FROM empleados e LEFT JOIN pedidos p ON e.id = p.empleado_id WHERE p.id IS NULL ORDER BY e.nombre;',
    solucionesAlternativas: ['SELECT nombre AS empleado FROM empleados WHERE id NOT IN (SELECT DISTINCT empleado_id FROM pedidos) ORDER BY nombre;'],
    explicacion: 'LEFT JOIN mantiene todos los empleados. Donde no hay pedido, p.id es NULL. WHERE p.id IS NULL filtra exactamente esos empleados.',
    pistas: ['LEFT JOIN pedidos p ON e.id = p.empleado_id', 'WHERE p.id IS NULL selecciona los que no tienen pareja', 'ORDER BY e.nombre para ordenar'],
    retroalimentacionError: 'LEFT JOIN pedidos + WHERE p.id IS NULL — es IS NULL, no = NULL',
  },
  {
    id: 'no-b-027',
    nivel: 'novato',
    titulo: 'JOIN de 3 tablas',
    descripcion: 'Muestra el nombre del empleado, el nombre de su departamento y el total de cada pedido que gestionó.',
    objetivo: 'Encadenar tres tablas con INNER JOIN.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['empleado', 'departamento', 'total'],
      filas: [
        ['Ana','RRHH',349.99],
        ['Carlos','Tecnología',799.99],
        ['Carlos','Tecnología',1299.99],
        ['María','Ventas',89.99],
        ['María','Ventas',599.99],
      ],
    },
    solucionOficial: 'SELECT e.nombre AS empleado, d.nombre AS departamento, p.total FROM empleados e INNER JOIN departamentos d ON e.departamento_id = d.id INNER JOIN pedidos p ON e.id = p.empleado_id ORDER BY e.nombre, p.total;',
    solucionesAlternativas: [],
    explicacion: 'Se encadenan dos JOINs: primero empleados→departamentos, luego empleados→pedidos. Solo aparecen los empleados que tienen al menos un pedido.',
    pistas: ['Primer JOIN: INNER JOIN departamentos d ON e.departamento_id = d.id', 'Segundo JOIN: INNER JOIN pedidos p ON e.id = p.empleado_id', 'ORDER BY e.nombre, p.total'],
    retroalimentacionError: 'Necesitas dos INNER JOINs encadenados: empleados→departamentos y empleados→pedidos',
  },
  {
    id: 'no-b-028',
    nivel: 'novato',
    titulo: 'JOIN de 3 tablas con agregación',
    descripcion: 'Muestra el nombre del empleado, su departamento, y el total de ventas que ha gestionado. Ordena de mayor a menor total.',
    objetivo: 'Combinar tres tablas con JOIN y agregar con SUM y GROUP BY.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['empleado', 'departamento', 'total_ventas'],
      filas: [['Carlos','Tecnología',2099.98],['María','Ventas',689.98],['Ana','RRHH',349.99]],
    },
    solucionOficial: 'SELECT e.nombre AS empleado, d.nombre AS departamento, SUM(p.total) AS total_ventas FROM empleados e INNER JOIN departamentos d ON e.departamento_id = d.id INNER JOIN pedidos p ON e.id = p.empleado_id GROUP BY e.id, e.nombre, d.nombre ORDER BY total_ventas DESC;',
    solucionesAlternativas: [],
    explicacion: 'Los dos JOINs conectan las tres tablas. GROUP BY agrupa por empleado. SUM suma los totales de pedidos de cada uno.',
    pistas: ['Dos INNER JOINs: empleados→departamentos y empleados→pedidos', 'GROUP BY e.id, e.nombre, d.nombre', 'SUM(p.total) AS total_ventas + ORDER BY total_ventas DESC'],
    retroalimentacionError: 'JOIN triple + GROUP BY e.id, e.nombre, d.nombre + SUM(p.total)',
  },
  {
    id: 'no-b-029',
    nivel: 'novato',
    titulo: 'Self JOIN',
    descripcion: 'Muestra los empleados que tienen al menos un compañero de departamento con un salario más alto. Indica el departamento.',
    objetivo: 'Usar un self JOIN (unir una tabla consigo misma) para comparar filas del mismo conjunto.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['empleado', 'departamento'],
      filas: [
        ['Sofía','Marketing'],['Ana','RRHH'],
        ['Carlos','Tecnología'],['Miguel','Tecnología'],
        ['Javier','Ventas'],['Pedro','Ventas'],
      ],
    },
    solucionOficial: 'SELECT DISTINCT a.nombre AS empleado, d.nombre AS departamento FROM empleados a JOIN empleados b ON a.departamento_id = b.departamento_id AND b.salario > a.salario JOIN departamentos d ON a.departamento_id = d.id ORDER BY departamento, empleado;',
    solucionesAlternativas: [],
    explicacion: 'Se une la tabla empleados consigo misma: "a" es el empleado y "b" es el compañero. La condición b.salario > a.salario busca compañeros que ganen más. DISTINCT evita duplicados.',
    pistas: ['FROM empleados a JOIN empleados b ON a.departamento_id = b.departamento_id', 'Añade AND b.salario > a.salario para filtrar solo los que tienen un compañero con más salario', 'Necesitas DISTINCT para evitar filas repetidas'],
    retroalimentacionError: 'Self JOIN: FROM empleados a JOIN empleados b ON mismo departamento AND b.salario > a.salario',
  },
  {
    id: 'no-b-030',
    nivel: 'novato',
    titulo: 'Subconsulta escalar',
    descripcion: 'Muestra los empleados cuyo salario supera el salario promedio de todos los empleados.',
    objetivo: 'Usar una subconsulta en WHERE para comparar con un valor calculado.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['nombre', 'salario'],
      filas: [['Laura',70000],['Carlos',65000],['Miguel',60000],['Andrés',55000]],
    },
    solucionOficial: 'SELECT nombre, salario FROM empleados WHERE salario > (SELECT AVG(salario) FROM empleados) ORDER BY salario DESC;',
    solucionesAlternativas: [],
    explicacion: 'La subconsulta (SELECT AVG(salario) FROM empleados) devuelve un único valor: 53100. La consulta externa filtra empleados con salario > 53100.',
    pistas: ['La subconsulta va dentro del WHERE: WHERE salario > (SELECT AVG(salario) FROM empleados)', 'La subconsulta devuelve un solo número (escalar)', 'ORDER BY salario DESC'],
    retroalimentacionError: 'WHERE salario > (SELECT AVG(salario) FROM empleados) — la subconsulta va entre paréntesis',
  },
  {
    id: 'no-b-031',
    nivel: 'novato',
    titulo: 'Subconsulta con IN',
    descripcion: 'Muestra los nombres de los clientes que han realizado al menos un pedido.',
    objetivo: 'Usar una subconsulta con IN para filtrar por pertenencia a un conjunto.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['nombre'],
      filas: [['Ana García'],['Bob Smith'],['Carlos Ruiz'],['Diana Lee']],
    },
    solucionOficial: 'SELECT nombre FROM clientes WHERE id IN (SELECT DISTINCT cliente_id FROM pedidos) ORDER BY nombre;',
    solucionesAlternativas: ['SELECT DISTINCT c.nombre FROM clientes c INNER JOIN pedidos p ON c.id = p.cliente_id ORDER BY c.nombre;'],
    explicacion: 'La subconsulta devuelve la lista de cliente_id que aparecen en pedidos. IN comprueba si el id del cliente está en esa lista.',
    pistas: ['WHERE id IN (SELECT DISTINCT cliente_id FROM pedidos)', 'La subconsulta devuelve un conjunto de valores, no un escalar', 'ORDER BY nombre'],
    retroalimentacionError: 'WHERE id IN (SELECT DISTINCT cliente_id FROM pedidos) — la subconsulta va entre paréntesis después de IN',
  },
  {
    id: 'no-b-032',
    nivel: 'novato',
    titulo: 'WHERE + GROUP BY + HAVING',
    descripcion: 'Muestra los departamentos con más de 1 empleado ACTIVO, junto al conteo. Solo considera empleados activos (activo = 1).',
    objetivo: 'Encadenar WHERE (filtro de filas) con GROUP BY + HAVING (filtro de grupos).',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['departamento_id', 'activos'],
      filas: [[1,3],[2,3],[3,2]],
    },
    solucionOficial: 'SELECT departamento_id, COUNT(*) AS activos FROM empleados WHERE activo = 1 GROUP BY departamento_id HAVING COUNT(*) > 1 ORDER BY departamento_id;',
    solucionesAlternativas: [],
    explicacion: 'WHERE activo = 1 elimina a Andrés antes de agrupar. Luego GROUP BY agrupa y HAVING filtra grupos con más de 1 empleado activo. Marketing queda fuera (solo Sofía activa).',
    pistas: ['WHERE activo = 1 va antes de GROUP BY', 'GROUP BY departamento_id agrupa los activos', 'HAVING COUNT(*) > 1 filtra grupos con más de 1'],
    retroalimentacionError: 'Orden correcto: WHERE activo = 1 → GROUP BY departamento_id → HAVING COUNT(*) > 1',
  },
  {
    id: 'no-b-033',
    nivel: 'novato',
    titulo: 'NULL en agregaciones',
    descripcion: 'Para cada cliente, muestra el número de filas (COUNT(*)), el número de pedidos reales (COUNT sobre el id del pedido) y la suma total. Observa cómo se comportan con NULL.',
    objetivo: 'Entender la diferencia entre COUNT(*) y COUNT(columna) cuando hay NULLs.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['cliente', 'count_filas', 'count_pedidos', 'suma_total'],
      filas: [
        ['Ana García',2,2,689.98],
        ['Bob Smith',1,1,1299.99],
        ['Carlos Ruiz',1,1,349.99],
        ['Diana Lee',1,1,799.99],
        ['Eva Müller',1,0,null],
      ],
    },
    solucionOficial: 'SELECT c.nombre AS cliente, COUNT(*) AS count_filas, COUNT(p.id) AS count_pedidos, SUM(p.total) AS suma_total FROM clientes c LEFT JOIN pedidos p ON c.id = p.cliente_id GROUP BY c.id, c.nombre ORDER BY c.nombre;',
    solucionesAlternativas: [],
    explicacion: 'Para Eva Müller: COUNT(*) = 1 porque hay 1 fila en el grupo, COUNT(p.id) = 0 porque p.id es NULL, SUM(p.total) = NULL porque no hay valores. COUNT(*) nunca ignora filas; COUNT(col) sí ignora NULLs.',
    pistas: ['LEFT JOIN para incluir a Eva Müller', 'COUNT(*) cuenta filas, COUNT(p.id) ignora NULLs', 'SUM con NULLs devuelve NULL, no 0'],
    retroalimentacionError: 'LEFT JOIN + COUNT(*) para filas + COUNT(p.id) para pedidos reales (ignora NULL)',
  },
  {
    id: 'no-b-034',
    nivel: 'novato',
    titulo: 'Varias funciones de agregación',
    descripcion: 'Calcula en una sola consulta: total de empleados, suma de salarios, salario promedio, mínimo y máximo.',
    objetivo: 'Usar múltiples funciones de agregación en el mismo SELECT.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['empleados','total_salarios','promedio','minimo','maximo'],
      filas: [[10,531000,53100,42000,70000]],
    },
    solucionOficial: 'SELECT COUNT(*) AS empleados, SUM(salario) AS total_salarios, AVG(salario) AS promedio, MIN(salario) AS minimo, MAX(salario) AS maximo FROM empleados;',
    solucionesAlternativas: [],
    explicacion: 'Puedes usar tantas funciones de agregación como quieras en el mismo SELECT. Todas operan sobre las mismas filas y devuelven un único resultado.',
    pistas: ['COUNT(*) para total de empleados', 'SUM, AVG, MIN, MAX se añaden separados por coma', 'No necesitas GROUP BY porque agregás toda la tabla'],
    retroalimentacionError: 'SELECT COUNT(*), SUM(salario), AVG(salario), MIN(salario), MAX(salario) FROM empleados',
  },
  {
    id: 'no-b-035',
    nivel: 'novato',
    titulo: 'AVG redondeado por departamento',
    descripcion: 'Muestra el salario promedio de cada departamento, redondeado al entero más cercano.',
    objetivo: 'Usar ROUND para presentar resultados de AVG con formato limpio.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['departamento_id', 'promedio_redondeado'],
      filas: [[1,43667],[2,65000],[3,49000],[4,53500]],
    },
    solucionOficial: 'SELECT departamento_id, ROUND(AVG(salario)) AS promedio_redondeado FROM empleados GROUP BY departamento_id ORDER BY departamento_id;',
    solucionesAlternativas: ['SELECT departamento_id, ROUND(AVG(salario), 0) AS promedio_redondeado FROM empleados GROUP BY departamento_id ORDER BY departamento_id;'],
    explicacion: 'Ventas tiene promedio 43666.67 que ROUND convierte en 43667. Para los demás departamentos el promedio ya es un número entero.',
    pistas: ['Envuelve AVG(salario) con ROUND(): ROUND(AVG(salario))', 'GROUP BY departamento_id', 'ORDER BY departamento_id'],
    retroalimentacionError: 'ROUND(AVG(salario)) AS promedio_redondeado con GROUP BY departamento_id',
  },
  {
    id: 'no-b-036',
    nivel: 'novato',
    titulo: 'Ranking por masa salarial',
    descripcion: 'Muestra cada departamento y la suma total de sus salarios (masa salarial), ordenados de mayor a menor.',
    objetivo: 'Combinar SUM con GROUP BY y ORDER BY para crear un ranking.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['departamento_id', 'masa_salarial'],
      filas: [[2,195000],[1,131000],[4,107000],[3,98000]],
    },
    solucionOficial: 'SELECT departamento_id, SUM(salario) AS masa_salarial FROM empleados GROUP BY departamento_id ORDER BY masa_salarial DESC;',
    solucionesAlternativas: [],
    explicacion: 'SUM(salario) suma todos los salarios por departamento. ORDER BY masa_salarial DESC los ordena de mayor a menor, creando un ranking natural.',
    pistas: ['SUM(salario) AS masa_salarial', 'GROUP BY departamento_id', 'ORDER BY masa_salarial DESC (descendente para mayor primero)'],
    retroalimentacionError: 'SELECT departamento_id, SUM(salario) AS masa_salarial FROM empleados GROUP BY departamento_id ORDER BY masa_salarial DESC',
  },
  {
    id: 'no-b-037',
    nivel: 'novato',
    titulo: 'JOIN con filtro de estado',
    descripcion: 'Muestra el nombre del cliente, el nombre del empleado que gestionó el pedido, el total y la fecha, solo para pedidos con estado "completado".',
    objetivo: 'Unir tres tablas con alias y filtrar por un campo de la tabla central.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['cliente', 'empleado', 'total', 'fecha'],
      filas: [
        ['Ana García','María',599.99,'2024-01-05'],
        ['Bob Smith','Carlos',1299.99,'2024-01-10'],
        ['Carlos Ruiz','Ana',349.99,'2024-01-20'],
      ],
    },
    solucionOficial: "SELECT c.nombre AS cliente, e.nombre AS empleado, p.total, p.fecha FROM pedidos p JOIN clientes c ON p.cliente_id = c.id JOIN empleados e ON p.empleado_id = e.id WHERE p.estado = 'completado' ORDER BY p.fecha;",
    solucionesAlternativas: [],
    explicacion: 'Dos JOINs conectan pedidos con clientes y empleados. WHERE p.estado = \'completado\' filtra solo los pedidos completados (excluye el pendiente y el enviado).',
    pistas: ['JOIN clientes c ON p.cliente_id = c.id', 'JOIN empleados e ON p.empleado_id = e.id', "WHERE p.estado = 'completado' ORDER BY p.fecha"],
    retroalimentacionError: "Dos JOINs desde pedidos: hacia clientes y hacia empleados. WHERE p.estado = 'completado'",
  },
  {
    id: 'no-b-038',
    nivel: 'novato',
    titulo: 'LEFT JOIN con tres tablas',
    descripcion: 'Muestra todos los clientes, el total de cada pedido y el nombre del empleado que lo gestionó. Incluye clientes sin pedidos.',
    objetivo: 'Encadenar dos LEFT JOINs para preservar todos los registros de la tabla base.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['cliente', 'total', 'empleado'],
      filas: [
        ['Ana García',89.99,'María'],
        ['Ana García',599.99,'María'],
        ['Bob Smith',1299.99,'Carlos'],
        ['Carlos Ruiz',349.99,'Ana'],
        ['Diana Lee',799.99,'Carlos'],
        ['Eva Müller',null,null],
      ],
    },
    solucionOficial: 'SELECT c.nombre AS cliente, p.total, e.nombre AS empleado FROM clientes c LEFT JOIN pedidos p ON c.id = p.cliente_id LEFT JOIN empleados e ON p.empleado_id = e.id ORDER BY c.nombre, p.total;',
    solucionesAlternativas: [],
    explicacion: 'El primer LEFT JOIN incluye a Eva Müller aunque no tenga pedidos. El segundo LEFT JOIN sobre empleados también será NULL para ella, porque p.empleado_id es NULL.',
    pistas: ['FROM clientes c — clientes es la tabla base', 'LEFT JOIN pedidos p ON c.id = p.cliente_id', 'LEFT JOIN empleados e ON p.empleado_id = e.id — segundo LEFT JOIN'],
    retroalimentacionError: 'Dos LEFT JOINs encadenados: clientes→pedidos→empleados, todos LEFT',
  },
  {
    id: 'no-b-039',
    nivel: 'novato',
    titulo: 'Subconsulta con NOT IN',
    descripcion: 'Muestra los empleados que NO han gestionado ningún pedido con estado "completado".',
    objetivo: 'Usar NOT IN con una subconsulta para excluir registros.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['nombre'],
      filas: [['Andrés'],['Elena'],['Javier'],['Laura'],['Miguel'],['Pedro'],['Sofía']],
    },
    solucionOficial: "SELECT nombre FROM empleados WHERE id NOT IN (SELECT DISTINCT empleado_id FROM pedidos WHERE estado = 'completado') ORDER BY nombre;",
    solucionesAlternativas: [],
    explicacion: "La subconsulta devuelve los IDs de empleados que gestionaron pedidos completados (1=María, 2=Carlos, 3=Ana). NOT IN excluye esos IDs, devolviendo el resto.",
    pistas: ["La subconsulta: SELECT DISTINCT empleado_id FROM pedidos WHERE estado = 'completado'", 'WHERE id NOT IN (...) excluye los que están en la lista', 'ORDER BY nombre'],
    retroalimentacionError: "WHERE id NOT IN (SELECT DISTINCT empleado_id FROM pedidos WHERE estado = 'completado')",
  },
  {
    id: 'no-b-040',
    nivel: 'novato',
    titulo: 'HAVING con SUM',
    descripcion: 'Muestra los departamentos cuya suma de salarios supera 100000, junto al número de empleados y el total. Ordena de mayor a menor.',
    objetivo: 'Filtrar grupos con HAVING usando SUM en la condición.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['departamento_id', 'empleados', 'total_salarios'],
      filas: [[2,3,195000],[1,3,131000],[4,2,107000]],
    },
    solucionOficial: 'SELECT departamento_id, COUNT(*) AS empleados, SUM(salario) AS total_salarios FROM empleados GROUP BY departamento_id HAVING SUM(salario) > 100000 ORDER BY total_salarios DESC;',
    solucionesAlternativas: [],
    explicacion: 'RRHH (98000) queda excluido porque no supera 100000. HAVING puede usar cualquier función de agregación, no solo COUNT.',
    pistas: ['GROUP BY departamento_id', 'HAVING SUM(salario) > 100000 — usa SUM en la condición de HAVING', 'ORDER BY total_salarios DESC'],
    retroalimentacionError: 'HAVING SUM(salario) > 100000 — la condición de HAVING puede ser cualquier agregación',
  },
  {
    id: 'no-b-041',
    nivel: 'novato',
    titulo: 'JOIN + GROUP BY + HAVING integrador',
    descripcion: 'Muestra los departamentos con ventas totales superiores a 500, indicando el nombre del departamento, número de pedidos gestionados y el total. Ordena de mayor a menor.',
    objetivo: 'Integrar JOIN de 3 tablas, GROUP BY, HAVING y ORDER BY en una sola consulta.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['departamento', 'num_pedidos', 'total_ventas'],
      filas: [['Tecnología',2,2099.98],['Ventas',2,689.98]],
    },
    solucionOficial: 'SELECT d.nombre AS departamento, COUNT(p.id) AS num_pedidos, SUM(p.total) AS total_ventas FROM departamentos d INNER JOIN empleados e ON d.id = e.departamento_id INNER JOIN pedidos p ON e.id = p.empleado_id GROUP BY d.id, d.nombre HAVING SUM(p.total) > 500 ORDER BY total_ventas DESC;',
    solucionesAlternativas: [],
    explicacion: 'El camino es departamentos→empleados→pedidos. GROUP BY agrupa por departamento. HAVING filtra solo los que superan 500 en ventas totales.',
    pistas: ['Tres tablas: departamentos→empleados→pedidos (dos INNER JOINs)', 'GROUP BY d.id, d.nombre', 'HAVING SUM(p.total) > 500 + ORDER BY total_ventas DESC'],
    retroalimentacionError: 'JOIN triple departamentos→empleados→pedidos + GROUP BY + HAVING SUM(p.total) > 500',
  },
  {
    id: 'no-b-042',
    nivel: 'novato',
    titulo: 'JOIN con subconsulta en WHERE',
    descripcion: 'Muestra los empleados que trabajan en departamentos con presupuesto superior al presupuesto promedio. Indica el nombre del departamento y su presupuesto.',
    objetivo: 'Combinar JOIN con una subconsulta escalar en el WHERE.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['empleado', 'departamento', 'presupuesto'],
      filas: [
        ['Carlos','Tecnología',800000],['Laura','Tecnología',800000],['Miguel','Tecnología',800000],
        ['Javier','Ventas',500000],['María','Ventas',500000],['Pedro','Ventas',500000],
      ],
    },
    solucionOficial: 'SELECT e.nombre AS empleado, d.nombre AS departamento, d.presupuesto FROM empleados e INNER JOIN departamentos d ON e.departamento_id = d.id WHERE d.presupuesto > (SELECT AVG(presupuesto) FROM departamentos) ORDER BY d.presupuesto DESC, e.nombre;',
    solucionesAlternativas: [],
    explicacion: 'La subconsulta calcula el presupuesto promedio de todos los departamentos: (500000+800000+300000+400000+350000)/5 = 470000. Solo Ventas (500000) y Tecnología (800000) lo superan.',
    pistas: ['INNER JOIN departamentos d ON e.departamento_id = d.id', 'WHERE d.presupuesto > (SELECT AVG(presupuesto) FROM departamentos)', 'ORDER BY d.presupuesto DESC, e.nombre'],
    retroalimentacionError: 'WHERE d.presupuesto > (SELECT AVG(presupuesto) FROM departamentos) — subconsulta escalar en WHERE',
  },
  {
    id: 'no-b-043',
    nivel: 'novato',
    titulo: 'Identificar la clave de JOIN correcta',
    descripcion: 'Muestra el ID del pedido, el nombre del empleado que lo gestionó, el total y el estado. Une correctamente usando las claves foráneas.',
    objetivo: 'Practicar la identificación de la columna correcta para el JOIN (FK → PK).',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['pedido_id', 'empleado', 'total', 'estado'],
      filas: [
        [1,'María',599.99,'completado'],
        [2,'Carlos',1299.99,'completado'],
        [3,'María',89.99,'pendiente'],
        [4,'Ana',349.99,'completado'],
        [5,'Carlos',799.99,'enviado'],
      ],
    },
    solucionOficial: 'SELECT p.id AS pedido_id, e.nombre AS empleado, p.total, p.estado FROM pedidos p INNER JOIN empleados e ON p.empleado_id = e.id ORDER BY p.id;',
    solucionesAlternativas: [],
    explicacion: 'La clave foránea empleado_id en pedidos apunta a la clave primaria id en empleados. La condición ON p.empleado_id = e.id conecta ambas tablas correctamente.',
    pistas: ['La FK es p.empleado_id y la PK es e.id', 'ON p.empleado_id = e.id es la condición correcta', 'SELECT p.id AS pedido_id para renombrar'],
    retroalimentacionError: 'JOIN empleados e ON p.empleado_id = e.id — la FK de pedidos apunta a la PK de empleados',
  },
  {
    id: 'no-b-044',
    nivel: 'novato',
    titulo: 'WHERE y HAVING juntos',
    descripcion: 'Calcula la masa salarial de los empleados ACTIVOS por departamento. Muestra solo los departamentos donde la suma supera 100000.',
    objetivo: 'Demostrar la diferencia entre WHERE (filtra filas) y HAVING (filtra grupos).',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['departamento_id', 'masa_salarial'],
      filas: [[2,195000],[1,131000]],
    },
    solucionOficial: 'SELECT departamento_id, SUM(salario) AS masa_salarial FROM empleados WHERE activo = 1 GROUP BY departamento_id HAVING SUM(salario) > 100000 ORDER BY masa_salarial DESC;',
    solucionesAlternativas: [],
    explicacion: 'WHERE activo = 1 opera antes del agrupamiento (excluye a Andrés). Después se agrupa y HAVING filtra grupos cuya suma activa supera 100000. Marketing queda fuera (solo Sofía activa: 52000).',
    pistas: ['WHERE activo = 1 filtra ANTES de agrupar — va antes de GROUP BY', 'HAVING SUM(salario) > 100000 filtra DESPUÉS de agrupar', 'ORDER BY masa_salarial DESC'],
    retroalimentacionError: 'WHERE activo = 1 (antes de GROUP BY) + HAVING SUM(salario) > 100000 (después de GROUP BY)',
  },
  {
    id: 'no-b-045',
    nivel: 'novato',
    titulo: 'Integrador novato final',
    descripcion: 'Muestra el nombre del cliente, el estado del pedido y el nombre del empleado que lo gestionó. Incluye solo pedidos con estado "completado" o "enviado". Ordena por nombre de cliente y luego por fecha.',
    objetivo: 'Integrar INNER JOIN de tres tablas, WHERE con IN y ORDER BY múltiple.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['cliente', 'estado', 'empleado', 'fecha'],
      filas: [
        ['Ana García','completado','María','2024-01-05'],
        ['Bob Smith','completado','Carlos','2024-01-10'],
        ['Carlos Ruiz','completado','Ana','2024-01-20'],
        ['Diana Lee','enviado','Carlos','2024-01-25'],
      ],
    },
    solucionOficial: "SELECT c.nombre AS cliente, p.estado, e.nombre AS empleado, p.fecha FROM pedidos p INNER JOIN clientes c ON p.cliente_id = c.id INNER JOIN empleados e ON p.empleado_id = e.id WHERE p.estado IN ('completado', 'enviado') ORDER BY c.nombre, p.fecha;",
    solucionesAlternativas: [],
    explicacion: "Tres tablas unidas por dos JOINs. WHERE p.estado IN ('completado', 'enviado') excluye el pedido pendiente. ORDER BY c.nombre, p.fecha ordena primero por cliente y luego cronológicamente.",
    pistas: ['Dos INNER JOINs desde pedidos: hacia clientes y hacia empleados', "WHERE p.estado IN ('completado', 'enviado') — IN para múltiples valores", 'ORDER BY c.nombre, p.fecha — dos columnas de ordenación'],
    retroalimentacionError: "JOIN clientes + JOIN empleados + WHERE p.estado IN ('completado', 'enviado')",
  },
];
