import type { EjercicioBanco } from '../../types';

const SETUP = `
CREATE TABLE departamentos (id INTEGER PRIMARY KEY, nombre TEXT, presupuesto REAL, ciudad TEXT);
INSERT INTO departamentos VALUES (1,'Ventas',500000,'Madrid');
INSERT INTO departamentos VALUES (2,'Tecnología',800000,'Barcelona');
INSERT INTO departamentos VALUES (3,'RRHH',300000,'Madrid');
INSERT INTO departamentos VALUES (4,'Marketing',400000,'Madrid');
INSERT INTO departamentos VALUES (5,'Finanzas',350000,'Barcelona');
CREATE TABLE empleados (id INTEGER PRIMARY KEY, nombre TEXT, departamento_id INTEGER, salario REAL, fecha_contrato TEXT, activo INTEGER);
INSERT INTO empleados VALUES (1,'María',1,45000,'2020-03-15',1);
INSERT INTO empleados VALUES (2,'Carlos',2,65000,'2019-06-01',1);
INSERT INTO empleados VALUES (3,'Ana',3,48000,'2021-01-10',1);
INSERT INTO empleados VALUES (4,'Pedro',1,42000,'2022-08-20',1);
INSERT INTO empleados VALUES (5,'Laura',2,70000,'2018-11-05',1);
INSERT INTO empleados VALUES (6,'Miguel',2,60000,'2020-07-15',1);
INSERT INTO empleados VALUES (7,'Sofía',4,52000,'2021-04-01',1);
INSERT INTO empleados VALUES (8,'Javier',1,44000,'2022-02-14',1);
INSERT INTO empleados VALUES (9,'Elena',3,50000,'2020-09-30',1);
INSERT INTO empleados VALUES (10,'Andrés',4,55000,'2019-12-01',0);
CREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria_id INTEGER, precio REAL, stock INTEGER, proveedor_id INTEGER);
INSERT INTO productos VALUES (1,'Laptop Pro',1,1299.99,20,1);
INSERT INTO productos VALUES (2,'Mouse',2,29.99,150,2);
INSERT INTO productos VALUES (3,'Teclado',2,89.99,80,2);
INSERT INTO productos VALUES (4,'Monitor',1,499.99,15,1);
INSERT INTO productos VALUES (5,'Webcam',2,79.99,100,2);
INSERT INTO productos VALUES (6,'Tablet',1,399.99,25,1);
CREATE TABLE categorias (id INTEGER PRIMARY KEY, nombre TEXT);
INSERT INTO categorias VALUES (1,'Electrónica');
INSERT INTO categorias VALUES (2,'Periféricos');
CREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, empleado_id INTEGER, total REAL, fecha TEXT, estado TEXT);
INSERT INTO pedidos VALUES (1,1,1,599.99,'2024-01-05','completado');
INSERT INTO pedidos VALUES (2,2,2,1299.99,'2024-01-10','completado');
INSERT INTO pedidos VALUES (3,1,1,89.99,'2024-01-15','pendiente');
INSERT INTO pedidos VALUES (4,3,3,349.99,'2024-01-20','completado');
INSERT INTO pedidos VALUES (5,4,2,799.99,'2024-01-25','enviado');
CREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, pais TEXT, email TEXT);
INSERT INTO clientes VALUES (1,'Ana García','España','ana@mail.com');
INSERT INTO clientes VALUES (2,'Bob Smith','USA','bob@mail.com');
INSERT INTO clientes VALUES (3,'Carlos Ruiz','México','carlos@mail.com');
INSERT INTO clientes VALUES (4,'Diana Lee','Japón','diana@mail.com');
INSERT INTO clientes VALUES (5,'Eva Müller','Alemania','eva@mail.com');
CREATE TABLE proveedores (id INTEGER PRIMARY KEY, nombre TEXT, pais TEXT, contacto TEXT);
INSERT INTO proveedores VALUES (1, 'TechCorp', 'China', 'li@techcorp.com');
INSERT INTO proveedores VALUES (2, 'GlobalParts', 'Alemania', 'hans@global.de');
INSERT INTO proveedores VALUES (3, 'ElectroPlus', 'España', 'juan@plus.es');
CREATE TABLE inventario_ajustes (id INTEGER PRIMARY KEY, producto_id INTEGER, cantidad_ajuste INTEGER, motivo TEXT, fecha TEXT);
INSERT INTO inventario_ajustes VALUES (1, 1, -2, 'Dañado', '2024-02-01');
INSERT INTO inventario_ajustes VALUES (2, 2, 50, 'Reabastecimiento', '2024-02-05');
INSERT INTO inventario_ajustes VALUES (3, 4, -1, 'Extraviado', '2024-02-10');
`;

export const ejerciciosNovato: EjercicioBanco[] = [
  {
    id: 'no-b-001',
    nivel: 'novato',
    titulo: 'Total de empleados',
    descripcion: 'Cuenta el número total de empleados.',
    objetivo: 'Usar COUNT(*) para contar todas las filas.',
    setupSql: SETUP,
    resultadoEsperado: { columnas: ['total'], filas: [[10]] },
    solucionOficial: 'SELECT COUNT(*) AS total FROM empleados;',
    solucionesAlternativas: [],
    explicacion: 'COUNT(*) cuenta todas las filas incluyendo las de empleados inactivos.',
    pistas: ['Usa COUNT(*)', 'Alias AS total'],
    retroalimentacionError: 'SELECT COUNT(*) AS total FROM empleados',
  },
  {
    id: 'no-b-002',
    nivel: 'novato',
    titulo: 'Empleados activos',
    descripcion: 'Cuenta solo los empleados con activo = 1.',
    objetivo: 'Combinar COUNT con WHERE.',
    setupSql: SETUP,
    resultadoEsperado: { columnas: ['activos'], filas: [[9]] },
    solucionOficial: 'SELECT COUNT(*) AS activos FROM empleados WHERE activo = 1;',
    solucionesAlternativas: [],
    explicacion: 'WHERE activo = 1 filtra primero, luego COUNT cuenta los filtrados.',
    pistas: ['WHERE activo = 1', 'COUNT(*) AS activos'],
    retroalimentacionError: 'SELECT COUNT(*) AS activos FROM empleados WHERE activo = 1',
  },
  {
    id: 'no-b-003',
    nivel: 'novato',
    titulo: 'Suma total de salarios',
    descripcion: 'Calcula la suma de todos los salarios de los empleados.',
    objetivo: 'Usar SUM para sumar valores.',
    setupSql: SETUP,
    resultadoEsperado: { columnas: ['total_salarios'], filas: [[531000]] },
    solucionOficial: 'SELECT SUM(salario) AS total_salarios FROM empleados;',
    solucionesAlternativas: [],
    explicacion: 'SUM(salario) suma todos los salarios de la tabla.',
    pistas: ['Usa SUM(salario)'],
    retroalimentacionError: 'SELECT SUM(salario) AS total_salarios FROM empleados',
  },
  {
    id: 'no-b-004',
    nivel: 'novato',
    titulo: 'Salario promedio',
    descripcion: 'Calcula el salario promedio de todos los empleados.',
    objetivo: 'Usar AVG para calcular promedios.',
    setupSql: SETUP,
    resultadoEsperado: { columnas: ['salario_promedio'], filas: [[53100]] },
    solucionOficial: 'SELECT AVG(salario) AS salario_promedio FROM empleados;',
    solucionesAlternativas: [],
    explicacion: 'AVG(salario) calcula el promedio: 531000 / 10 = 53100.',
    pistas: ['Usa AVG(salario)'],
    retroalimentacionError: 'SELECT AVG(salario) AS salario_promedio FROM empleados',
  },
  {
    id: 'no-b-005',
    nivel: 'novato',
    titulo: 'Salario máximo y mínimo',
    descripcion: 'Muestra el salario más alto y el más bajo en la misma consulta.',
    objetivo: 'Combinar MAX y MIN en una consulta.',
    setupSql: SETUP,
    resultadoEsperado: { columnas: ['salario_max','salario_min'], filas: [[70000,42000]] },
    solucionOficial: 'SELECT MAX(salario) AS salario_max, MIN(salario) AS salario_min FROM empleados;',
    solucionesAlternativas: [],
    explicacion: 'MAX devuelve 70000 (Laura) y MIN devuelve 42000 (Pedro).',
    pistas: ['Usa MAX(salario) y MIN(salario) en el mismo SELECT'],
    retroalimentacionError: 'SELECT MAX(salario) AS salario_max, MIN(salario) AS salario_min FROM empleados',
  },
  {
    id: 'no-b-006',
    nivel: 'novato',
    titulo: 'Empleados por departamento',
    descripcion: 'Muestra cuántos empleados hay en cada departamento.',
    objetivo: 'Usar GROUP BY con COUNT.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['departamento_id','cantidad'],
      filas: [[1,3],[2,3],[3,2],[4,2]],
    },
    solucionOficial: 'SELECT departamento_id, COUNT(*) AS cantidad FROM empleados GROUP BY departamento_id ORDER BY departamento_id;',
    solucionesAlternativas: [],
    explicacion: 'GROUP BY departamento_id agrupa empleados por departamento y COUNT cuenta cada grupo.',
    pistas: ['GROUP BY departamento_id', 'COUNT(*) AS cantidad'],
    retroalimentacionError: 'SELECT departamento_id, COUNT(*) AS cantidad FROM empleados GROUP BY departamento_id',
  },
  {
    id: 'no-b-007',
    nivel: 'novato',
    titulo: 'Salario promedio por departamento',
    descripcion: 'Calcula el salario promedio (redondeado a 2 decimales) para cada departamento.',
    objetivo: 'Combinar AVG con GROUP BY y ROUND.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['departamento_id','salario_promedio'],
      filas: [[1,43666.67],[2,65000],[3,49000],[4,53500]],
    },
    solucionOficial: 'SELECT departamento_id, ROUND(AVG(salario), 2) AS salario_promedio FROM empleados GROUP BY departamento_id ORDER BY departamento_id;',
    solucionesAlternativas: [],
    explicacion: 'AVG se calcula independientemente para cada grupo. ROUND(..., 2) redondea a 2 decimales para evitar resultados como 43666.666...',
    pistas: ['AVG(salario) con GROUP BY departamento_id', 'Envuelve AVG en ROUND(AVG(salario), 2) para redondear'],
    retroalimentacionError: 'SELECT departamento_id, ROUND(AVG(salario), 2) AS salario_promedio FROM empleados GROUP BY departamento_id',
  },
  {
    id: 'no-b-008',
    nivel: 'novato',
    titulo: 'Departamentos con más de 2 empleados',
    descripcion: 'Muestra los departamentos que tienen más de 2 empleados.',
    objetivo: 'Usar HAVING para filtrar grupos.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['departamento_id','cantidad'],
      filas: [[1,3],[2,3]],
    },
    solucionOficial: 'SELECT departamento_id, COUNT(*) AS cantidad FROM empleados GROUP BY departamento_id HAVING COUNT(*) > 2 ORDER BY departamento_id;',
    solucionesAlternativas: [],
    explicacion: 'HAVING filtra grupos después de que GROUP BY los crea. Solo los grupos con más de 2 empleados pasan.',
    pistas: ['HAVING COUNT(*) > 2 filtra grupos con más de 2'],
    retroalimentacionError: 'GROUP BY departamento_id HAVING COUNT(*) > 2',
  },
  {
    id: 'no-b-009',
    nivel: 'novato',
    titulo: 'Categorías de productos únicas',
    descripcion: 'Muestra los ids de categorías que aparecen en la tabla productos, sin duplicados.',
    objetivo: 'Usar DISTINCT para eliminar duplicados.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['categoria_id'],
      filas: [[1],[2]],
    },
    solucionOficial: 'SELECT DISTINCT categoria_id FROM productos ORDER BY categoria_id;',
    solucionesAlternativas: [],
    explicacion: 'DISTINCT elimina los valores duplicados de categoria_id.',
    pistas: ['Usa DISTINCT para valores únicos'],
    retroalimentacionError: 'SELECT DISTINCT categoria_id FROM productos',
  },
  {
    id: 'no-b-010',
    nivel: 'novato',
    titulo: 'INNER JOIN empleados con departamentos',
    descripcion: 'Muestra nombre del empleado y nombre de su departamento.',
    objetivo: 'Usar INNER JOIN para combinar dos tablas.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['empleado','departamento'],
      filas: [
        ['María','Ventas'],['Carlos','Tecnología'],['Ana','RRHH'],
        ['Pedro','Ventas'],['Laura','Tecnología'],['Miguel','Tecnología'],
        ['Sofía','Marketing'],['Javier','Ventas'],['Elena','RRHH'],['Andrés','Marketing'],
      ],
    },
    solucionOficial: 'SELECT e.nombre AS empleado, d.nombre AS departamento FROM empleados e INNER JOIN departamentos d ON e.departamento_id = d.id ORDER BY e.id;',
    solucionesAlternativas: [],
    explicacion: 'INNER JOIN conecta empleados con departamentos a través de departamento_id = id.',
    pistas: ['INNER JOIN departamentos d ON e.departamento_id = d.id', 'Usa alias e y d para las tablas'],
    retroalimentacionError: 'FROM empleados e INNER JOIN departamentos d ON e.departamento_id = d.id',
  },
  {
    id: 'no-b-011',
    nivel: 'novato',
    titulo: 'Productos con su categoría',
    descripcion: 'Muestra nombre del producto y nombre de su categoría.',
    objetivo: 'Practicar INNER JOIN en otra relación.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['producto','categoria'],
      filas: [
        ['Laptop Pro','Electrónica'],['Mouse','Periféricos'],['Teclado','Periféricos'],
        ['Monitor','Electrónica'],['Webcam','Periféricos'],['Tablet','Electrónica'],
      ],
    },
    solucionOficial: 'SELECT p.nombre AS producto, c.nombre AS categoria FROM productos p INNER JOIN categorias c ON p.categoria_id = c.id ORDER BY p.id;',
    solucionesAlternativas: [],
    explicacion: 'Conectamos productos con categorias a través de categoria_id = id.',
    pistas: ['INNER JOIN categorias c ON p.categoria_id = c.id'],
    retroalimentacionError: 'FROM productos p INNER JOIN categorias c ON p.categoria_id = c.id',
  },
  {
    id: 'no-b-012',
    nivel: 'novato',
    titulo: 'Pedidos con nombre de cliente',
    descripcion: 'Muestra id del pedido, nombre del cliente y total.',
    objetivo: 'JOIN entre pedidos y clientes.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['pedido_id','cliente','total'],
      filas: [
        [1,'Ana García',599.99],[2,'Bob Smith',1299.99],[3,'Ana García',89.99],
        [4,'Carlos Ruiz',349.99],[5,'Diana Lee',799.99],
      ],
    },
    solucionOficial: 'SELECT p.id AS pedido_id, c.nombre AS cliente, p.total FROM pedidos p INNER JOIN clientes c ON p.cliente_id = c.id ORDER BY p.id;',
    solucionesAlternativas: [],
    explicacion: 'JOIN entre pedidos y clientes por cliente_id = id del cliente.',
    pistas: ['INNER JOIN clientes c ON p.cliente_id = c.id'],
    retroalimentacionError: 'FROM pedidos p INNER JOIN clientes c ON p.cliente_id = c.id',
  },
  {
    id: 'no-b-013',
    nivel: 'novato',
    titulo: 'Clientes con o sin pedidos (LEFT JOIN)',
    descripcion: 'Muestra todos los clientes y, si tienen pedidos, el total. Los sin pedidos deben mostrar NULL.',
    objetivo: 'Usar LEFT JOIN para incluir todos los registros de la tabla izquierda.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['cliente','total_pedido'],
      filas: [
        ['Ana García',599.99],['Ana García',89.99],
        ['Bob Smith',1299.99],['Carlos Ruiz',349.99],
        ['Diana Lee',799.99],['Eva Müller',null],
      ],
    },
    solucionOficial: 'SELECT c.nombre AS cliente, p.total AS total_pedido FROM clientes c LEFT JOIN pedidos p ON c.id = p.cliente_id ORDER BY c.nombre, p.total;',
    solucionesAlternativas: [],
    explicacion: 'LEFT JOIN incluye todos los clientes. Eva Müller no tiene pedidos y aparece con NULL.',
    pistas: ['LEFT JOIN muestra todos los clientes aunque no tengan pedidos'],
    retroalimentacionError: 'FROM clientes c LEFT JOIN pedidos p ON c.id = p.cliente_id',
  },
  {
    id: 'no-b-014',
    nivel: 'novato',
    titulo: 'Clientes sin ningún pedido',
    descripcion: 'Muestra los clientes que no tienen ningún pedido registrado.',
    objetivo: 'Usar LEFT JOIN + WHERE IS NULL para encontrar sin coincidencia.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['cliente'],
      filas: [['Eva Müller']],
    },
    solucionOficial: 'SELECT c.nombre AS cliente FROM clientes c LEFT JOIN pedidos p ON c.id = p.cliente_id WHERE p.id IS NULL;',
    solucionesAlternativas: [],
    explicacion: 'LEFT JOIN + WHERE p.id IS NULL encuentra los clientes que no tienen ningún pedido.',
    pistas: ['LEFT JOIN + WHERE p.id IS NULL encuentra los que no tienen pareja'],
    retroalimentacionError: 'LEFT JOIN pedidos p ON c.id = p.cliente_id WHERE p.id IS NULL',
  },
  {
    id: 'no-b-015',
    nivel: 'novato',
    titulo: 'Total de ventas por empleado',
    descripcion: 'Muestra el nombre de cada empleado y el total de sus pedidos.',
    objetivo: 'Combinar JOIN con GROUP BY y SUM.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['empleado','total_ventas'],
      filas: [['María',689.98],['Carlos',2099.98],['Ana',349.99]],
    },
    solucionOficial: 'SELECT e.nombre AS empleado, SUM(p.total) AS total_ventas FROM empleados e INNER JOIN pedidos p ON e.id = p.empleado_id GROUP BY e.id, e.nombre ORDER BY total_ventas DESC;',
    solucionesAlternativas: [],
    explicacion: 'JOIN conecta empleados con pedidos. GROUP BY agrupa por empleado. SUM suma los totales de cada empleado.',
    pistas: ['INNER JOIN pedidos p ON e.id = p.empleado_id', 'GROUP BY e.id, e.nombre', 'SUM(p.total)'],
    retroalimentacionError: 'JOIN + GROUP BY e.id, e.nombre + SUM(p.total)',
  },
  // ── Ejercicios 16-45: temas variados ────────────────────────────
  {
    id: 'no-b-016',
    nivel: 'novato',
    titulo: 'COUNT con DISTINCT',
    descripcion: 'Cuenta cuántos departamentos distintos tienen empleados asignados.',
    objetivo: 'Usar COUNT(DISTINCT columna) para contar valores únicos.',
    setupSql: SETUP,
    resultadoEsperado: { columnas: ['num_departamentos'], filas: [[4]] },
    solucionOficial: 'SELECT COUNT(DISTINCT departamento_id) AS num_departamentos FROM empleados;',
    solucionesAlternativas: ['SELECT COUNT(*) AS num_departamentos FROM (SELECT DISTINCT departamento_id FROM empleados);'],
    explicacion: 'COUNT(DISTINCT departamento_id) cuenta cada valor diferente de departamento_id una sola vez, ignorando repeticiones.',
    pistas: ['Combina COUNT() con DISTINCT dentro del paréntesis', 'La sintaxis es COUNT(DISTINCT columna)', 'Usa el alias num_departamentos'],
    retroalimentacionError: 'Usa COUNT(DISTINCT departamento_id) AS num_departamentos FROM empleados',
  },
  {
    id: 'no-b-017',
    nivel: 'novato',
    titulo: 'DISTINCT + ORDER BY',
    descripcion: 'Lista los países de los clientes sin repetir, ordenados alfabéticamente.',
    objetivo: 'Combinar DISTINCT con ORDER BY para obtener listas únicas ordenadas.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['pais'],
      filas: [['Alemania'],['España'],['Japón'],['México'],['USA']],
    },
    solucionOficial: 'SELECT DISTINCT pais FROM clientes ORDER BY pais;',
    solucionesAlternativas: ['SELECT pais FROM clientes GROUP BY pais ORDER BY pais;'],
    explicacion: 'DISTINCT elimina los valores duplicados de la columna pais. ORDER BY los ordena alfabéticamente.',
    pistas: ['Usa SELECT DISTINCT pais', 'Añade ORDER BY pais al final', 'La tabla es clientes'],
    retroalimentacionError: 'SELECT DISTINCT pais FROM clientes ORDER BY pais',
  },
  {
    id: 'no-b-018',
    nivel: 'novato',
    titulo: 'SUM con WHERE',
    descripcion: 'Calcula la suma total de salarios solo de los empleados activos (activo = 1).',
    objetivo: 'Filtrar con WHERE antes de aplicar SUM.',
    setupSql: SETUP,
    resultadoEsperado: { columnas: ['total_activos'], filas: [[476000]] },
    solucionOficial: 'SELECT SUM(salario) AS total_activos FROM empleados WHERE activo = 1;',
    solucionesAlternativas: [],
    explicacion: 'WHERE activo = 1 filtra las filas antes de que SUM las sume. Andrés (activo = 0) queda excluido.',
    pistas: ['Usa SUM(salario) AS total_activos', 'Añade WHERE activo = 1 antes de agrupar', 'WHERE filtra ANTES de agregar'],
    retroalimentacionError: 'SELECT SUM(salario) AS total_activos FROM empleados WHERE activo = 1',
  },
  {
    id: 'no-b-019',
    nivel: 'novato',
    titulo: 'AVG con WHERE',
    descripcion: 'Calcula el salario promedio únicamente de los empleados del departamento de Tecnología (departamento_id = 2).',
    objetivo: 'Usar AVG con un filtro WHERE para un subconjunto de filas.',
    setupSql: SETUP,
    resultadoEsperado: { columnas: ['promedio'], filas: [[65000]] },
    solucionOficial: 'SELECT AVG(salario) AS promedio FROM empleados WHERE departamento_id = 2;',
    solucionesAlternativas: [],
    explicacion: 'Tecnología tiene 3 empleados: Carlos (65000), Laura (70000) y Miguel (60000). Promedio = 195000 / 3 = 65000.',
    pistas: ['Usa AVG(salario) AS promedio', 'WHERE departamento_id = 2 filtra solo Tecnología', 'La tabla es empleados'],
    retroalimentacionError: 'SELECT AVG(salario) AS promedio FROM empleados WHERE departamento_id = 2',
  },
  {
    id: 'no-b-020',
    nivel: 'novato',
    titulo: 'MIN y MAX con GROUP BY',
    descripcion: 'Muestra el salario mínimo y máximo de cada departamento.',
    objetivo: 'Usar MIN y MAX junto con GROUP BY para obtener extremos por grupo.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['departamento_id', 'salario_min', 'salario_max'],
      filas: [[1,42000,45000],[2,60000,70000],[3,48000,50000],[4,52000,55000]],
    },
    solucionOficial: 'SELECT departamento_id, MIN(salario) AS salario_min, MAX(salario) AS salario_max FROM empleados GROUP BY departamento_id ORDER BY departamento_id;',
    solucionesAlternativas: [],
    explicacion: 'GROUP BY crea un grupo por departamento. MIN y MAX calculan independientemente el mínimo y máximo dentro de cada grupo.',
    pistas: ['SELECT departamento_id, MIN(salario), MAX(salario)', 'Añade GROUP BY departamento_id', 'Ordena por departamento_id'],
    retroalimentacionError: 'GROUP BY departamento_id + MIN(salario) AS salario_min, MAX(salario) AS salario_max',
  },
  {
    id: 'no-b-021',
    nivel: 'novato',
    titulo: 'GROUP BY con dos columnas',
    descripcion: 'Cuenta cuántos empleados hay en cada combinación de departamento y estado (activo/inactivo).',
    objetivo: 'Agrupar por más de una columna con GROUP BY.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['departamento_id', 'activo', 'cantidad'],
      filas: [[1,1,3],[2,1,3],[3,1,2],[4,0,1],[4,1,1]],
    },
    solucionOficial: 'SELECT departamento_id, activo, COUNT(*) AS cantidad FROM empleados GROUP BY departamento_id, activo ORDER BY departamento_id, activo;',
    solucionesAlternativas: [],
    explicacion: 'GROUP BY departamento_id, activo crea un grupo por cada combinación única. El departamento 4 aparece dos veces: una para activo=0 (Andrés) y otra para activo=1 (Sofía).',
    pistas: ['GROUP BY departamento_id, activo — separa las columnas con coma', 'COUNT(*) cuenta las filas de cada grupo', 'ORDER BY departamento_id, activo para ordenar el resultado'],
    retroalimentacionError: 'GROUP BY departamento_id, activo — lista ambas columnas separadas por coma',
  },
  {
    id: 'no-b-022',
    nivel: 'novato',
    titulo: 'HAVING con AND',
    descripcion: 'Muestra los departamentos cuyo salario promedio supera 50000 Y que tienen más de 1 empleado.',
    objetivo: 'Usar HAVING con múltiples condiciones unidas por AND.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['departamento_id', 'empleados', 'promedio'],
      filas: [[2,3,65000],[4,2,53500]],
    },
    solucionOficial: 'SELECT departamento_id, COUNT(*) AS empleados, AVG(salario) AS promedio FROM empleados GROUP BY departamento_id HAVING AVG(salario) > 50000 AND COUNT(*) > 1 ORDER BY departamento_id;',
    solucionesAlternativas: [],
    explicacion: 'HAVING filtra grupos enteros. Con AND, ambas condiciones deben cumplirse. Ventas (avg 43667) y RRHH (avg 49000) no superan 50000, así que quedan fuera.',
    pistas: ['Agrupa con GROUP BY departamento_id', 'En HAVING usa AVG(salario) > 50000 AND COUNT(*) > 1', 'HAVING va después de GROUP BY'],
    retroalimentacionError: 'HAVING AVG(salario) > 50000 AND COUNT(*) > 1 — ambas condiciones en HAVING, no en WHERE',
  },
  {
    id: 'no-b-023',
    nivel: 'novato',
    titulo: 'INNER JOIN con filtro WHERE',
    descripcion: 'Muestra el nombre del empleado y el departamento, pero solo los que pertenecen a departamentos de Barcelona.',
    objetivo: 'Combinar INNER JOIN con un filtro WHERE sobre una columna de la tabla unida.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['empleado', 'departamento'],
      filas: [['Carlos','Tecnología'],['Laura','Tecnología'],['Miguel','Tecnología']],
    },
    solucionOficial: 'SELECT e.nombre AS empleado, d.nombre AS departamento FROM empleados e INNER JOIN departamentos d ON e.departamento_id = d.id WHERE d.ciudad = \'Barcelona\' ORDER BY e.nombre;',
    solucionesAlternativas: [],
    explicacion: 'El JOIN conecta empleados con departamentos. El WHERE filtra solo los departamentos de Barcelona (Tecnología y Finanzas). Como ningún empleado está en Finanzas, solo aparecen los de Tecnología.',
    pistas: ['INNER JOIN departamentos d ON e.departamento_id = d.id', 'WHERE d.ciudad = \'Barcelona\'', 'ORDER BY e.nombre'],
    retroalimentacionError: 'JOIN departamentos + WHERE d.ciudad = \'Barcelona\'',
  },
  {
    id: 'no-b-024',
    nivel: 'novato',
    titulo: 'Top 3 pedidos con LIMIT',
    descripcion: 'Muestra los 3 pedidos con mayor total, indicando el nombre del cliente.',
    objetivo: 'Usar INNER JOIN, ORDER BY DESC y LIMIT para obtener los N primeros registros.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['cliente', 'total'],
      filas: [['Bob Smith',1299.99],['Diana Lee',799.99],['Ana García',599.99]],
    },
    solucionOficial: 'SELECT c.nombre AS cliente, p.total FROM pedidos p INNER JOIN clientes c ON p.cliente_id = c.id ORDER BY p.total DESC LIMIT 3;',
    solucionesAlternativas: [],
    explicacion: 'ORDER BY p.total DESC ordena de mayor a menor. LIMIT 3 devuelve solo las 3 primeras filas del resultado.',
    pistas: ['INNER JOIN clientes c ON p.cliente_id = c.id', 'ORDER BY p.total DESC', 'Añade LIMIT 3 al final'],
    retroalimentacionError: 'JOIN clientes + ORDER BY p.total DESC + LIMIT 3',
  },
  {
    id: 'no-b-025',
    nivel: 'novato',
    titulo: 'LEFT JOIN con COUNT',
    descripcion: 'Muestra cada cliente y cuántos pedidos ha realizado. Incluye también a los clientes sin pedidos.',
    objetivo: 'Usar LEFT JOIN con GROUP BY y COUNT para incluir filas sin coincidencia.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['cliente', 'num_pedidos'],
      filas: [['Ana García',2],['Bob Smith',1],['Carlos Ruiz',1],['Diana Lee',1],['Eva Müller',0]],
    },
    solucionOficial: 'SELECT c.nombre AS cliente, COUNT(p.id) AS num_pedidos FROM clientes c LEFT JOIN pedidos p ON c.id = p.cliente_id GROUP BY c.id, c.nombre ORDER BY num_pedidos DESC, c.nombre;',
    solucionesAlternativas: [],
    explicacion: 'LEFT JOIN incluye todos los clientes. COUNT(p.id) devuelve 0 cuando p.id es NULL (sin pedidos), a diferencia de COUNT(*) que devolvería 1.',
    pistas: ['LEFT JOIN pedidos p ON c.id = p.cliente_id', 'COUNT(p.id) — no COUNT(*) — para que Eva Müller salga con 0', 'GROUP BY c.id, c.nombre'],
    retroalimentacionError: 'LEFT JOIN + COUNT(p.id) — usa COUNT(p.id) no COUNT(*) para contar 0 cuando no hay pedidos',
  },
  {
    id: 'no-b-026',
    nivel: 'novato',
    titulo: 'Anti-JOIN: empleados sin pedidos',
    descripcion: 'Muestra los empleados que no han gestionado ningún pedido.',
    objetivo: 'Usar LEFT JOIN + WHERE IS NULL para encontrar registros sin coincidencia (anti-join).',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['empleado'],
      filas: [['Andrés'],['Elena'],['Javier'],['Laura'],['Miguel'],['Pedro'],['Sofía']],
    },
    solucionOficial: 'SELECT e.nombre AS empleado FROM empleados e LEFT JOIN pedidos p ON e.id = p.empleado_id WHERE p.id IS NULL ORDER BY e.nombre;',
    solucionesAlternativas: ['SELECT nombre AS empleado FROM empleados WHERE id NOT IN (SELECT DISTINCT empleado_id FROM pedidos) ORDER BY nombre;'],
    explicacion: 'LEFT JOIN mantiene todos los empleados. Donde no hay pedido, p.id es NULL. WHERE p.id IS NULL filtra exactamente esos empleados.',
    pistas: ['LEFT JOIN pedidos p ON e.id = p.empleado_id', 'WHERE p.id IS NULL selecciona los que no tienen pareja', 'ORDER BY e.nombre para ordenar'],
    retroalimentacionError: 'LEFT JOIN pedidos + WHERE p.id IS NULL — es IS NULL, no = NULL',
  },
  {
    id: 'no-b-027',
    nivel: 'novato',
    titulo: 'JOIN de 3 tablas',
    descripcion: 'Muestra el nombre del empleado, el nombre de su departamento y el total de cada pedido que gestionó.',
    objetivo: 'Encadenar tres tablas con INNER JOIN.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['empleado', 'departamento', 'total'],
      filas: [
        ['Ana','RRHH',349.99],
        ['Carlos','Tecnología',799.99],
        ['Carlos','Tecnología',1299.99],
        ['María','Ventas',89.99],
        ['María','Ventas',599.99],
      ],
    },
    solucionOficial: 'SELECT e.nombre AS empleado, d.nombre AS departamento, p.total FROM empleados e INNER JOIN departamentos d ON e.departamento_id = d.id INNER JOIN pedidos p ON e.id = p.empleado_id ORDER BY e.nombre, p.total;',
    solucionesAlternativas: [],
    explicacion: 'Se encadenan dos JOINs: primero empleados→departamentos, luego empleados→pedidos. Solo aparecen los empleados que tienen al menos un pedido.',
    pistas: ['Primer JOIN: INNER JOIN departamentos d ON e.departamento_id = d.id', 'Segundo JOIN: INNER JOIN pedidos p ON e.id = p.empleado_id', 'ORDER BY e.nombre, p.total'],
    retroalimentacionError: 'Necesitas dos INNER JOINs encadenados: empleados→departamentos y empleados→pedidos',
  },
  {
    id: 'no-b-028',
    nivel: 'novato',
    titulo: 'JOIN de 3 tablas con agregación',
    descripcion: 'Muestra el nombre del empleado, su departamento, y el total de ventas que ha gestionado. Ordena de mayor a menor total.',
    objetivo: 'Combinar tres tablas con JOIN y agregar con SUM y GROUP BY.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['empleado', 'departamento', 'total_ventas'],
      filas: [['Carlos','Tecnología',2099.98],['María','Ventas',689.98],['Ana','RRHH',349.99]],
    },
    solucionOficial: 'SELECT e.nombre AS empleado, d.nombre AS departamento, SUM(p.total) AS total_ventas FROM empleados e INNER JOIN departamentos d ON e.departamento_id = d.id INNER JOIN pedidos p ON e.id = p.empleado_id GROUP BY e.id, e.nombre, d.nombre ORDER BY total_ventas DESC;',
    solucionesAlternativas: [],
    explicacion: 'Los dos JOINs conectan las tres tablas. GROUP BY agrupa por empleado. SUM suma los totales de pedidos de cada uno.',
    pistas: ['Dos INNER JOINs: empleados→departamentos y empleados→pedidos', 'GROUP BY e.id, e.nombre, d.nombre', 'SUM(p.total) AS total_ventas + ORDER BY total_ventas DESC'],
    retroalimentacionError: 'JOIN triple + GROUP BY e.id, e.nombre, d.nombre + SUM(p.total)',
  },
  {
    id: 'no-b-029',
    nivel: 'novato',
    titulo: 'Self JOIN',
    descripcion: 'Muestra los empleados que tienen al menos un compañero de departamento con un salario más alto. Indica el departamento.',
    objetivo: 'Usar un self JOIN (unir una tabla consigo misma) para comparar filas del mismo conjunto.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['empleado', 'departamento'],
      filas: [
        ['Sofía','Marketing'],['Ana','RRHH'],
        ['Carlos','Tecnología'],['Miguel','Tecnología'],
        ['Javier','Ventas'],['Pedro','Ventas'],
      ],
    },
    solucionOficial: 'SELECT DISTINCT a.nombre AS empleado, d.nombre AS departamento FROM empleados a JOIN empleados b ON a.departamento_id = b.departamento_id AND b.salario > a.salario JOIN departamentos d ON a.departamento_id = d.id ORDER BY departamento, empleado;',
    solucionesAlternativas: [],
    explicacion: 'Se une la tabla empleados consigo misma: "a" es el empleado y "b" es el compañero. La condición b.salario > a.salario busca compañeros que ganen más. DISTINCT evita duplicados.',
    pistas: ['FROM empleados a JOIN empleados b ON a.departamento_id = b.departamento_id', 'Añade AND b.salario > a.salario para filtrar solo los que tienen un compañero con más salario', 'Necesitas DISTINCT para evitar filas repetidas'],
    retroalimentacionError: 'Self JOIN: FROM empleados a JOIN empleados b ON mismo departamento AND b.salario > a.salario',
  },
  {
    id: 'no-b-030',
    nivel: 'novato',
    titulo: 'Subconsulta escalar',
    descripcion: 'Muestra los empleados cuyo salario supera el salario promedio de todos los empleados.',
    objetivo: 'Usar una subconsulta en WHERE para comparar con un valor calculado.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['nombre', 'salario'],
      filas: [['Laura',70000],['Carlos',65000],['Miguel',60000],['Andrés',55000]],
    },
    solucionOficial: 'SELECT nombre, salario FROM empleados WHERE salario > (SELECT AVG(salario) FROM empleados) ORDER BY salario DESC;',
    solucionesAlternativas: [],
    explicacion: 'La subconsulta (SELECT AVG(salario) FROM empleados) devuelve un único valor: 53100. La consulta externa filtra empleados con salario > 53100.',
    pistas: ['La subconsulta va dentro del WHERE: WHERE salario > (SELECT AVG(salario) FROM empleados)', 'La subconsulta devuelve un solo número (escalar)', 'ORDER BY salario DESC'],
    retroalimentacionError: 'WHERE salario > (SELECT AVG(salario) FROM empleados) — la subconsulta va entre paréntesis',
  },
  {
    id: 'no-b-031',
    nivel: 'novato',
    titulo: 'Subconsulta con IN',
    descripcion: 'Muestra los nombres de los clientes que han realizado al menos un pedido.',
    objetivo: 'Usar una subconsulta con IN para filtrar por pertenencia a un conjunto.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['nombre'],
      filas: [['Ana García'],['Bob Smith'],['Carlos Ruiz'],['Diana Lee']],
    },
    solucionOficial: 'SELECT nombre FROM clientes WHERE id IN (SELECT DISTINCT cliente_id FROM pedidos) ORDER BY nombre;',
    solucionesAlternativas: ['SELECT DISTINCT c.nombre FROM clientes c INNER JOIN pedidos p ON c.id = p.cliente_id ORDER BY c.nombre;'],
    explicacion: 'La subconsulta devuelve la lista de cliente_id que aparecen en pedidos. IN comprueba si el id del cliente está en esa lista.',
    pistas: ['WHERE id IN (SELECT DISTINCT cliente_id FROM pedidos)', 'La subconsulta devuelve un conjunto de valores, no un escalar', 'ORDER BY nombre'],
    retroalimentacionError: 'WHERE id IN (SELECT DISTINCT cliente_id FROM pedidos) — la subconsulta va entre paréntesis después de IN',
  },
  {
    id: 'no-b-032',
    nivel: 'novato',
    titulo: 'WHERE + GROUP BY + HAVING',
    descripcion: 'Muestra los departamentos con más de 1 empleado ACTIVO, junto al conteo. Solo considera empleados activos (activo = 1).',
    objetivo: 'Encadenar WHERE (filtro de filas) con GROUP BY + HAVING (filtro de grupos).',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['departamento_id', 'activos'],
      filas: [[1,3],[2,3],[3,2]],
    },
    solucionOficial: 'SELECT departamento_id, COUNT(*) AS activos FROM empleados WHERE activo = 1 GROUP BY departamento_id HAVING COUNT(*) > 1 ORDER BY departamento_id;',
    solucionesAlternativas: [],
    explicacion: 'WHERE activo = 1 elimina a Andrés antes de agrupar. Luego GROUP BY agrupa y HAVING filtra grupos con más de 1 empleado activo. Marketing queda fuera (solo Sofía activa).',
    pistas: ['WHERE activo = 1 va antes de GROUP BY', 'GROUP BY departamento_id agrupa los activos', 'HAVING COUNT(*) > 1 filtra grupos con más de 1'],
    retroalimentacionError: 'Orden correcto: WHERE activo = 1 → GROUP BY departamento_id → HAVING COUNT(*) > 1',
  },
  {
    id: 'no-b-033',
    nivel: 'novato',
    titulo: 'NULL en agregaciones',
    descripcion: 'Para cada cliente, muestra el número de filas (COUNT(*)), el número de pedidos reales (COUNT sobre el id del pedido) y la suma total. Observa cómo se comportan con NULL.',
    objetivo: 'Entender la diferencia entre COUNT(*) y COUNT(columna) cuando hay NULLs.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['cliente', 'count_filas', 'count_pedidos', 'suma_total'],
      filas: [
        ['Ana García',2,2,689.98],
        ['Bob Smith',1,1,1299.99],
        ['Carlos Ruiz',1,1,349.99],
        ['Diana Lee',1,1,799.99],
        ['Eva Müller',1,0,null],
      ],
    },
    solucionOficial: 'SELECT c.nombre AS cliente, COUNT(*) AS count_filas, COUNT(p.id) AS count_pedidos, SUM(p.total) AS suma_total FROM clientes c LEFT JOIN pedidos p ON c.id = p.cliente_id GROUP BY c.id, c.nombre ORDER BY c.nombre;',
    solucionesAlternativas: [],
    explicacion: 'Para Eva Müller: COUNT(*) = 1 porque hay 1 fila en el grupo, COUNT(p.id) = 0 porque p.id es NULL, SUM(p.total) = NULL porque no hay valores. COUNT(*) nunca ignora filas; COUNT(col) sí ignora NULLs.',
    pistas: ['LEFT JOIN para incluir a Eva Müller', 'COUNT(*) cuenta filas, COUNT(p.id) ignora NULLs', 'SUM con NULLs devuelve NULL, no 0'],
    retroalimentacionError: 'LEFT JOIN + COUNT(*) para filas + COUNT(p.id) para pedidos reales (ignora NULL)',
  },
  {
    id: 'no-b-034',
    nivel: 'novato',
    titulo: 'Varias funciones de agregación',
    descripcion: 'Calcula en una sola consulta: total de empleados, suma de salarios, salario promedio, mínimo y máximo.',
    objetivo: 'Usar múltiples funciones de agregación en el mismo SELECT.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['empleados','total_salarios','promedio','minimo','maximo'],
      filas: [[10,531000,53100,42000,70000]],
    },
    solucionOficial: 'SELECT COUNT(*) AS empleados, SUM(salario) AS total_salarios, AVG(salario) AS promedio, MIN(salario) AS minimo, MAX(salario) AS maximo FROM empleados;',
    solucionesAlternativas: [],
    explicacion: 'Puedes usar tantas funciones de agregación como quieras en el mismo SELECT. Todas operan sobre las mismas filas y devuelven un único resultado.',
    pistas: ['COUNT(*) para total de empleados', 'SUM, AVG, MIN, MAX se añaden separados por coma', 'No necesitas GROUP BY porque agregás toda la tabla'],
    retroalimentacionError: 'SELECT COUNT(*), SUM(salario), AVG(salario), MIN(salario), MAX(salario) FROM empleados',
  },
  {
    id: 'no-b-035',
    nivel: 'novato',
    titulo: 'AVG redondeado por departamento',
    descripcion: 'Muestra el salario promedio de cada departamento, redondeado al entero más cercano.',
    objetivo: 'Usar ROUND para presentar resultados de AVG con formato limpio.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['departamento_id', 'promedio_redondeado'],
      filas: [[1,43667],[2,65000],[3,49000],[4,53500]],
    },
    solucionOficial: 'SELECT departamento_id, ROUND(AVG(salario)) AS promedio_redondeado FROM empleados GROUP BY departamento_id ORDER BY departamento_id;',
    solucionesAlternativas: ['SELECT departamento_id, ROUND(AVG(salario), 0) AS promedio_redondeado FROM empleados GROUP BY departamento_id ORDER BY departamento_id;'],
    explicacion: 'Ventas tiene promedio 43666.67 que ROUND convierte en 43667. Para los demás departamentos el promedio ya es un número entero.',
    pistas: ['Envuelve AVG(salario) con ROUND(): ROUND(AVG(salario))', 'GROUP BY departamento_id', 'ORDER BY departamento_id'],
    retroalimentacionError: 'ROUND(AVG(salario)) AS promedio_redondeado con GROUP BY departamento_id',
  },
  {
    id: 'no-b-036',
    nivel: 'novato',
    titulo: 'Ranking por masa salarial',
    descripcion: 'Muestra cada departamento y la suma total de sus salarios (masa salarial), ordenados de mayor a menor.',
    objetivo: 'Combinar SUM con GROUP BY y ORDER BY para crear un ranking.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['departamento_id', 'masa_salarial'],
      filas: [[2,195000],[1,131000],[4,107000],[3,98000]],
    },
    solucionOficial: 'SELECT departamento_id, SUM(salario) AS masa_salarial FROM empleados GROUP BY departamento_id ORDER BY masa_salarial DESC;',
    solucionesAlternativas: [],
    explicacion: 'SUM(salario) suma todos los salarios por departamento. ORDER BY masa_salarial DESC los ordena de mayor a menor, creando un ranking natural.',
    pistas: ['SUM(salario) AS masa_salarial', 'GROUP BY departamento_id', 'ORDER BY masa_salarial DESC (descendente para mayor primero)'],
    retroalimentacionError: 'SELECT departamento_id, SUM(salario) AS masa_salarial FROM empleados GROUP BY departamento_id ORDER BY masa_salarial DESC',
  },
  {
    id: 'no-b-037',
    nivel: 'novato',
    titulo: 'JOIN con filtro de estado',
    descripcion: 'Muestra el nombre del cliente, el nombre del empleado que gestionó el pedido, el total y la fecha, solo para pedidos con estado "completado".',
    objetivo: 'Unir tres tablas con alias y filtrar por un campo de la tabla central.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['cliente', 'empleado', 'total', 'fecha'],
      filas: [
        ['Ana García','María',599.99,'2024-01-05'],
        ['Bob Smith','Carlos',1299.99,'2024-01-10'],
        ['Carlos Ruiz','Ana',349.99,'2024-01-20'],
      ],
    },
    solucionOficial: "SELECT c.nombre AS cliente, e.nombre AS empleado, p.total, p.fecha FROM pedidos p JOIN clientes c ON p.cliente_id = c.id JOIN empleados e ON p.empleado_id = e.id WHERE p.estado = 'completado' ORDER BY p.fecha;",
    solucionesAlternativas: [],
    explicacion: 'Dos JOINs conectan pedidos con clientes y empleados. WHERE p.estado = \'completado\' filtra solo los pedidos completados (excluye el pendiente y el enviado).',
    pistas: ['JOIN clientes c ON p.cliente_id = c.id', 'JOIN empleados e ON p.empleado_id = e.id', "WHERE p.estado = 'completado' ORDER BY p.fecha"],
    retroalimentacionError: "Dos JOINs desde pedidos: hacia clientes y hacia empleados. WHERE p.estado = 'completado'",
  },
  {
    id: 'no-b-038',
    nivel: 'novato',
    titulo: 'LEFT JOIN con tres tablas',
    descripcion: 'Muestra todos los clientes, el total de cada pedido y el nombre del empleado que lo gestionó. Incluye clientes sin pedidos.',
    objetivo: 'Encadenar dos LEFT JOINs para preservar todos los registros de la tabla base.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['cliente', 'total', 'empleado'],
      filas: [
        ['Ana García',89.99,'María'],
        ['Ana García',599.99,'María'],
        ['Bob Smith',1299.99,'Carlos'],
        ['Carlos Ruiz',349.99,'Ana'],
        ['Diana Lee',799.99,'Carlos'],
        ['Eva Müller',null,null],
      ],
    },
    solucionOficial: 'SELECT c.nombre AS cliente, p.total, e.nombre AS empleado FROM clientes c LEFT JOIN pedidos p ON c.id = p.cliente_id LEFT JOIN empleados e ON p.empleado_id = e.id ORDER BY c.nombre, p.total;',
    solucionesAlternativas: [],
    explicacion: 'El primer LEFT JOIN incluye a Eva Müller aunque no tenga pedidos. El segundo LEFT JOIN sobre empleados también será NULL para ella, porque p.empleado_id es NULL.',
    pistas: ['FROM clientes c — clientes es la tabla base', 'LEFT JOIN pedidos p ON c.id = p.cliente_id', 'LEFT JOIN empleados e ON p.empleado_id = e.id — segundo LEFT JOIN'],
    retroalimentacionError: 'Dos LEFT JOINs encadenados: clientes→pedidos→empleados, todos LEFT',
  },
  {
    id: 'no-b-039',
    nivel: 'novato',
    titulo: 'Subconsulta con NOT IN',
    descripcion: 'Muestra los empleados que NO han gestionado ningún pedido con estado "completado".',
    objetivo: 'Usar NOT IN con una subconsulta para excluir registros.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['nombre'],
      filas: [['Andrés'],['Elena'],['Javier'],['Laura'],['Miguel'],['Pedro'],['Sofía']],
    },
    solucionOficial: "SELECT nombre FROM empleados WHERE id NOT IN (SELECT DISTINCT empleado_id FROM pedidos WHERE estado = 'completado') ORDER BY nombre;",
    solucionesAlternativas: [],
    explicacion: "La subconsulta devuelve los IDs de empleados que gestionaron pedidos completados (1=María, 2=Carlos, 3=Ana). NOT IN excluye esos IDs, devolviendo el resto.",
    pistas: ["La subconsulta: SELECT DISTINCT empleado_id FROM pedidos WHERE estado = 'completado'", 'WHERE id NOT IN (...) excluye los que están en la lista', 'ORDER BY nombre'],
    retroalimentacionError: "WHERE id NOT IN (SELECT DISTINCT empleado_id FROM pedidos WHERE estado = 'completado')",
  },
  {
    id: 'no-b-040',
    nivel: 'novato',
    titulo: 'HAVING con SUM',
    descripcion: 'Muestra los departamentos cuya suma de salarios supera 100000, junto al número de empleados y el total. Ordena de mayor a menor.',
    objetivo: 'Filtrar grupos con HAVING usando SUM en la condición.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['departamento_id', 'empleados', 'total_salarios'],
      filas: [[2,3,195000],[1,3,131000],[4,2,107000]],
    },
    solucionOficial: 'SELECT departamento_id, COUNT(*) AS empleados, SUM(salario) AS total_salarios FROM empleados GROUP BY departamento_id HAVING SUM(salario) > 100000 ORDER BY total_salarios DESC;',
    solucionesAlternativas: [],
    explicacion: 'RRHH (98000) queda excluido porque no supera 100000. HAVING puede usar cualquier función de agregación, no solo COUNT.',
    pistas: ['GROUP BY departamento_id', 'HAVING SUM(salario) > 100000 — usa SUM en la condición de HAVING', 'ORDER BY total_salarios DESC'],
    retroalimentacionError: 'HAVING SUM(salario) > 100000 — la condición de HAVING puede ser cualquier agregación',
  },
  {
    id: 'no-b-041',
    nivel: 'novato',
    titulo: 'JOIN + GROUP BY + HAVING integrador',
    descripcion: 'Muestra los departamentos con ventas totales superiores a 500, indicando el nombre del departamento, número de pedidos gestionados y el total. Ordena de mayor a menor.',
    objetivo: 'Integrar JOIN de 3 tablas, GROUP BY, HAVING y ORDER BY en una sola consulta.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['departamento', 'num_pedidos', 'total_ventas'],
      filas: [['Tecnología',2,2099.98],['Ventas',2,689.98]],
    },
    solucionOficial: 'SELECT d.nombre AS departamento, COUNT(p.id) AS num_pedidos, SUM(p.total) AS total_ventas FROM departamentos d INNER JOIN empleados e ON d.id = e.departamento_id INNER JOIN pedidos p ON e.id = p.empleado_id GROUP BY d.id, d.nombre HAVING SUM(p.total) > 500 ORDER BY total_ventas DESC;',
    solucionesAlternativas: [],
    explicacion: 'El camino es departamentos→empleados→pedidos. GROUP BY agrupa por departamento. HAVING filtra solo los que superan 500 en ventas totales.',
    pistas: ['Tres tablas: departamentos→empleados→pedidos (dos INNER JOINs)', 'GROUP BY d.id, d.nombre', 'HAVING SUM(p.total) > 500 + ORDER BY total_ventas DESC'],
    retroalimentacionError: 'JOIN triple departamentos→empleados→pedidos + GROUP BY + HAVING SUM(p.total) > 500',
  },
  {
    id: 'no-b-042',
    nivel: 'novato',
    titulo: 'JOIN con subconsulta en WHERE',
    descripcion: 'Muestra los empleados que trabajan en departamentos con presupuesto superior al presupuesto promedio. Indica el nombre del departamento y su presupuesto.',
    objetivo: 'Combinar JOIN con una subconsulta escalar en el WHERE.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['empleado', 'departamento', 'presupuesto'],
      filas: [
        ['Carlos','Tecnología',800000],['Laura','Tecnología',800000],['Miguel','Tecnología',800000],
        ['Javier','Ventas',500000],['María','Ventas',500000],['Pedro','Ventas',500000],
      ],
    },
    solucionOficial: 'SELECT e.nombre AS empleado, d.nombre AS departamento, d.presupuesto FROM empleados e INNER JOIN departamentos d ON e.departamento_id = d.id WHERE d.presupuesto > (SELECT AVG(presupuesto) FROM departamentos) ORDER BY d.presupuesto DESC, e.nombre;',
    solucionesAlternativas: [],
    explicacion: 'La subconsulta calcula el presupuesto promedio de todos los departamentos: (500000+800000+300000+400000+350000)/5 = 470000. Solo Ventas (500000) y Tecnología (800000) lo superan.',
    pistas: ['INNER JOIN departamentos d ON e.departamento_id = d.id', 'WHERE d.presupuesto > (SELECT AVG(presupuesto) FROM departamentos)', 'ORDER BY d.presupuesto DESC, e.nombre'],
    retroalimentacionError: 'WHERE d.presupuesto > (SELECT AVG(presupuesto) FROM departamentos) — subconsulta escalar en WHERE',
  },
  {
    id: 'no-b-043',
    nivel: 'novato',
    titulo: 'Identificar la clave de JOIN correcta',
    descripcion: 'Muestra el ID del pedido, el nombre del empleado que lo gestionó, el total y el estado. Une correctamente usando las claves foráneas.',
    objetivo: 'Practicar la identificación de la columna correcta para el JOIN (FK → PK).',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['pedido_id', 'empleado', 'total', 'estado'],
      filas: [
        [1,'María',599.99,'completado'],
        [2,'Carlos',1299.99,'completado'],
        [3,'María',89.99,'pendiente'],
        [4,'Ana',349.99,'completado'],
        [5,'Carlos',799.99,'enviado'],
      ],
    },
    solucionOficial: 'SELECT p.id AS pedido_id, e.nombre AS empleado, p.total, p.estado FROM pedidos p INNER JOIN empleados e ON p.empleado_id = e.id ORDER BY p.id;',
    solucionesAlternativas: [],
    explicacion: 'La clave foránea empleado_id en pedidos apunta a la clave primaria id en empleados. La condición ON p.empleado_id = e.id conecta ambas tablas correctamente.',
    pistas: ['La FK es p.empleado_id y la PK es e.id', 'ON p.empleado_id = e.id es la condición correcta', 'SELECT p.id AS pedido_id para renombrar'],
    retroalimentacionError: 'JOIN empleados e ON p.empleado_id = e.id — la FK de pedidos apunta a la PK de empleados',
  },
  {
    id: 'no-b-044',
    nivel: 'novato',
    titulo: 'WHERE y HAVING juntos',
    descripcion: 'Calcula la masa salarial de los empleados ACTIVOS por departamento. Muestra solo los departamentos donde la suma supera 100000.',
    objetivo: 'Demostrar la diferencia entre WHERE (filtra filas) y HAVING (filtra grupos).',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['departamento_id', 'masa_salarial'],
      filas: [[2,195000],[1,131000]],
    },
    solucionOficial: 'SELECT departamento_id, SUM(salario) AS masa_salarial FROM empleados WHERE activo = 1 GROUP BY departamento_id HAVING SUM(salario) > 100000 ORDER BY masa_salarial DESC;',
    solucionesAlternativas: [],
    explicacion: 'WHERE activo = 1 opera antes del agrupamiento (excluye a Andrés). Después se agrupa y HAVING filtra grupos cuya suma activa supera 100000. Marketing queda fuera (solo Sofía activa: 52000).',
    pistas: ['WHERE activo = 1 filtra ANTES de agrupar — va antes de GROUP BY', 'HAVING SUM(salario) > 100000 filtra DESPUÉS de agrupar', 'ORDER BY masa_salarial DESC'],
    retroalimentacionError: 'WHERE activo = 1 (antes de GROUP BY) + HAVING SUM(salario) > 100000 (después de GROUP BY)',
  },
  {
    id: 'no-b-045',
    nivel: 'novato',
    titulo: 'Integrador novato final',
    descripcion: 'Muestra el nombre del cliente, el estado del pedido y el nombre del empleado que lo gestionó. Incluye solo pedidos con estado "completado" o "enviado". Ordena por nombre de cliente y luego por fecha.',
    objetivo: 'Integrar INNER JOIN de tres tablas, WHERE con IN y ORDER BY múltiple.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['cliente', 'estado', 'empleado', 'fecha'],
      filas: [
        ['Ana García','completado','María','2024-01-05'],
        ['Bob Smith','completado','Carlos','2024-01-10'],
        ['Carlos Ruiz','completado','Ana','2024-01-20'],
        ['Diana Lee','enviado','Carlos','2024-01-25'],
      ],
    },
    solucionOficial: "SELECT c.nombre AS cliente, p.estado, e.nombre AS empleado, p.fecha FROM pedidos p INNER JOIN clientes c ON p.cliente_id = c.id INNER JOIN empleados e ON p.empleado_id = e.id WHERE p.estado IN ('completado', 'enviado') ORDER BY c.nombre, p.fecha;",
    solucionesAlternativas: [],
    explicacion: "Tres tablas unidas por dos JOINs. WHERE p.estado IN ('completado', 'enviado') excluye el pedido pendiente. ORDER BY c.nombre, p.fecha ordena primero por cliente y luego cronológicamente.",
    pistas: ['Dos INNER JOINs desde pedidos: hacia clientes y hacia empleados', "WHERE p.estado IN ('completado', 'enviado') — IN para múltiples valores", 'ORDER BY c.nombre, p.fecha — dos columnas de ordenación'],
    retroalimentacionError: "JOIN clientes + JOIN empleados + WHERE p.estado IN ('completado', 'enviado')",
  },
  {
    id: 'no-b-046',
    nivel: 'novato',
    titulo: 'Productos y sus proveedores',
    descripcion: 'Muestra el nombre del producto y el nombre de su proveedor.',
    objetivo: 'Practicar JOIN entre tablas usando clave foránea proveedor_id.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['producto', 'proveedor'],
      filas: [
        ['Laptop Pro','TechCorp'],['Monitor','TechCorp'],['Mouse','GlobalParts'],
        ['Tablet','TechCorp'],['Teclado','GlobalParts'],['Webcam','GlobalParts'],
      ],
    },
    solucionOficial: 'SELECT p.nombre AS producto, pr.nombre AS proveedor FROM productos p JOIN proveedores pr ON p.proveedor_id = pr.id ORDER BY p.nombre;',
    solucionesAlternativas: [],
    explicacion: 'Unimos productos con proveedores a través de la clave foránea proveedor_id.',
    pistas: ['JOIN proveedores pr ON p.proveedor_id = pr.id'],
    retroalimentacionError: 'JOIN productos con proveedores usando p.proveedor_id = pr.id',
  },
  {
    id: 'no-b-047',
    nivel: 'novato',
    titulo: 'Ventas por país de cliente',
    descripcion: 'Muestra cuánto se ha vendido en total por cada país de los clientes.',
    objetivo: 'Combinar JOIN de tres tablas con agregación SUM y agrupación por columna de texto.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['pais', 'total_ventas'],
      filas: [['España',689.98],['USA',1299.99],['México',349.99],['Japón',799.99]],
    },
    solucionOficial: 'SELECT c.pais, SUM(p.total) AS total_ventas FROM clientes c JOIN pedidos p ON c.id = p.cliente_id GROUP BY c.pais ORDER BY total_ventas DESC;',
    solucionesAlternativas: [],
    explicacion: 'Unimos clientes con pedidos, agrupamos por país y sumamos los totales de los pedidos de cada país.',
    pistas: ['JOIN clientes c ON c.id = p.cliente_id', 'GROUP BY c.pais', 'SUM(p.total)'],
    retroalimentacionError: 'JOIN clientes y pedidos, agrupa por pais y suma el total',
  },
  {
    id: 'no-b-048',
    nivel: 'novato',
    titulo: 'Pedidos de productos específicos',
    descripcion: 'Muestra los pedidos (ID y total) gestionados por el empleado Carlos (id=2).',
    objetivo: 'Filtrar resultados de una tabla usando una condición de otra tabla unida.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['id', 'total'],
      filas: [[2, 1299.99], [5, 799.99]],
    },
    solucionOficial: 'SELECT id, total FROM pedidos WHERE empleado_id = 2 ORDER BY id;',
    solucionesAlternativas: ["SELECT p.id, p.total FROM pedidos p JOIN empleados e ON p.empleado_id = e.id WHERE e.nombre = 'Carlos';"],
    explicacion: 'Filtramos la tabla pedidos directamente por el ID del empleado Carlos.',
    pistas: ['WHERE empleado_id = 2'],
    retroalimentacionError: 'Filtra pedidos donde empleado_id sea 2',
  },
  {
    id: 'no-b-049',
    nivel: 'novato',
    titulo: 'Ajustes de inventario por producto',
    descripcion: 'Muestra el nombre del producto y el motivo del ajuste de inventario realizado.',
    objetivo: 'JOIN simple para relacionar movimientos con nombres de entidades.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['producto', 'motivo'],
      filas: [['Laptop Pro','Dañado'],['Mouse','Reabastecimiento'],['Monitor','Extraviado']],
    },
    solucionOficial: 'SELECT p.nombre AS producto, ia.motivo FROM productos p JOIN inventario_ajustes ia ON p.id = ia.producto_id ORDER BY ia.fecha;',
    solucionesAlternativas: [],
    explicacion: 'Relacionamos la tabla de productos con los ajustes de inventario para saber qué producto fue afectado.',
    pistas: ['JOIN inventario_ajustes ia ON p.id = ia.producto_id'],
    retroalimentacionError: 'JOIN productos e inventario_ajustes por el ID del producto',
  },
  {
    id: 'no-b-050',
    nivel: 'novato',
    titulo: 'Presupuesto restante por departamento',
    descripcion: 'Muestra el nombre del departamento y su presupuesto, pero solo para aquellos en la ciudad de Madrid.',
    objetivo: 'Filtro WHERE sobre columna de texto.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['nombre', 'presupuesto'],
      filas: [['Ventas', 500000.0], ['RRHH', 300000.0], ['Marketing', 400000.0]],
    },
    solucionOficial: "SELECT nombre, presupuesto FROM departamentos WHERE ciudad = 'Madrid' ORDER BY presupuesto DESC;",
    solucionesAlternativas: [],
    explicacion: "Filtramos la tabla departamentos por la columna ciudad con el valor 'Madrid'.",
    pistas: ["WHERE ciudad = 'Madrid'"],
    retroalimentacionError: "Filtra departamentos donde ciudad sea 'Madrid'",
  },
  {
    id: 'no-b-051',
    nivel: 'novato',
    titulo: 'Empleados contratados en 2021',
    descripcion: 'Muestra el nombre y la fecha de contrato de los empleados contratados durante el año 2021.',
    objetivo: 'Usar LIKE para filtrar fechas por año.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['nombre', 'fecha_contrato'],
      filas: [['Ana', '2021-01-10'], ['Sofía', '2021-04-01']],
    },
    solucionOficial: "SELECT nombre, fecha_contrato FROM empleados WHERE fecha_contrato LIKE '2021-%' ORDER BY fecha_contrato;",
    solucionesAlternativas: ["SELECT nombre, fecha_contrato FROM empleados WHERE fecha_contrato BETWEEN '2021-01-01' AND '2021-12-31';"],
    explicacion: "El operador LIKE '2021-%' busca cualquier fecha que comience con ese año.",
    pistas: ["LIKE '2021-%'"],
    retroalimentacionError: "Filtra empleados con fecha_contrato que empiece por '2021'",
  },
  {
    id: 'no-b-052',
    nivel: 'novato',
    titulo: 'Productos caros por categoría',
    descripcion: 'Muestra cuántos productos de cada categoría tienen un precio mayor a 100.',
    objetivo: 'Combinar COUNT, WHERE y GROUP BY.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['categoria_id', 'cantidad'],
      filas: [[1, 3]],
    },
    solucionOficial: 'SELECT categoria_id, COUNT(*) AS cantidad FROM productos WHERE precio > 100 GROUP BY categoria_id;',
    solucionesAlternativas: [],
    explicacion: 'Filtramos productos > 100 y luego contamos cuántos quedan en cada grupo de categoría.',
    pistas: ['WHERE precio > 100', 'GROUP BY categoria_id'],
    retroalimentacionError: 'Filtra precio > 100 y agrupa por categoria_id',
  },
  {
    id: 'no-b-053',
    nivel: 'novato',
    titulo: 'Email de clientes con pedidos completados',
    descripcion: 'Muestra el nombre y email de los clientes que tienen al menos un pedido con estado "completado". Sin duplicados.',
    objetivo: 'DISTINCT con JOIN y filtro WHERE.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['nombre', 'email'],
      filas: [['Ana García', 'ana@mail.com'], ['Bob Smith', 'bob@mail.com'], ['Carlos Ruiz', 'carlos@mail.com']],
    },
    solucionOficial: "SELECT DISTINCT c.nombre, c.email FROM clientes c JOIN pedidos p ON c.id = p.cliente_id WHERE p.estado = 'completado' ORDER BY c.nombre;",
    solucionesAlternativas: [],
    explicacion: "Unimos clientes y pedidos, filtramos por 'completado' y usamos DISTINCT para no repetir clientes si hicieron varios pedidos.",
    pistas: ['DISTINCT c.nombre', "WHERE p.estado = 'completado'"],
    retroalimentacionError: "JOIN clientes y pedidos, filtra estado 'completado' y usa DISTINCT",
  },
  {
    id: 'no-b-054',
    nivel: 'novato',
    titulo: 'Suma de stock por proveedor',
    descripcion: 'Muestra el ID del proveedor (categoria_id) y la suma total de stock de sus productos.',
    objetivo: 'SUM con GROUP BY.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['proveedor_id', 'stock_total'],
      filas: [[1, 60], [2, 330]],
    },
    solucionOficial: 'SELECT categoria_id AS proveedor_id, SUM(stock) AS stock_total FROM productos GROUP BY categoria_id;',
    solucionesAlternativas: [],
    explicacion: 'Agrupamos por proveedor (categoria_id) y sumamos la columna stock.',
    pistas: ['SUM(stock)', 'GROUP BY categoria_id'],
    retroalimentacionError: 'Suma el stock agrupando por categoria_id',
  },
  {
    id: 'no-b-055',
    nivel: 'novato',
    titulo: 'Empleados y sus ciudades',
    descripcion: 'Muestra el nombre del empleado y la ciudad del departamento al que pertenece.',
    objetivo: 'JOIN simple entre empleados y departamentos.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['empleado', 'ciudad'],
      filas: [
        ['María','Madrid'],['Carlos','Barcelona'],['Ana','Madrid'],
        ['Pedro','Madrid'],['Laura','Barcelona'],['Miguel','Barcelona'],
        ['Sofía','Madrid'],['Javier','Madrid'],['Elena','Madrid'],['Andrés','Madrid'],
      ],
    },
    solucionOficial: 'SELECT e.nombre AS empleado, d.ciudad FROM empleados e JOIN departamentos d ON e.departamento_id = d.id ORDER BY e.id;',
    solucionesAlternativas: [],
    explicacion: 'Conectamos empleados con departamentos para obtener la ciudad donde trabajan.',
    pistas: ['JOIN departamentos d ON e.departamento_id = d.id'],
    retroalimentacionError: 'JOIN empleados con departamentos por el ID del departamento',
  },
  {
    id: 'no-b-056',
    nivel: 'novato',
    titulo: 'Clientes de España o México',
    descripcion: 'Lista el nombre y país de los clientes que son de España o México.',
    objetivo: 'Usar el operador IN para filtrar por múltiples valores.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['nombre', 'pais'],
      filas: [['Ana García', 'España'], ['Carlos Ruiz', 'México']],
    },
    solucionOficial: "SELECT nombre, pais FROM clientes WHERE pais IN ('España', 'México') ORDER BY pais;",
    solucionesAlternativas: ["SELECT nombre, pais FROM clientes WHERE pais = 'España' OR pais = 'México';"],
    explicacion: "IN permite filtrar filas que coincidan con cualquiera de los valores de la lista.",
    pistas: ["pais IN ('España', 'México')"],
    retroalimentacionError: "Filtra paises 'España' o 'México' usando IN",
  },
  {
    id: 'no-b-057',
    nivel: 'novato',
    titulo: 'Productos con bajo stock',
    descripcion: 'Muestra el nombre y stock de los productos que tienen entre 1 y 20 unidades de stock.',
    objetivo: 'Usar BETWEEN para rangos numéricos.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['nombre', 'stock'],
      filas: [['Laptop Pro', 20], ['Monitor', 15]],
    },
    solucionOficial: 'SELECT nombre, stock FROM productos WHERE stock BETWEEN 1 AND 20 ORDER BY stock;',
    solucionesAlternativas: ['SELECT nombre, stock FROM productos WHERE stock >= 1 AND stock <= 20;'],
    explicacion: 'BETWEEN filtra valores dentro de un rango inclusivo.',
    pistas: ['stock BETWEEN 1 AND 20'],
    retroalimentacionError: 'Filtra stock entre 1 y 20 usando BETWEEN',
  },
  {
    id: 'no-b-058',
    nivel: 'novato',
    titulo: 'Promedio de pedidos por empleado',
    descripcion: 'Calcula el promedio de los totales de los pedidos gestionados por el empleado con ID 1.',
    objetivo: 'AVG con filtro WHERE.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['promedio'],
      filas: [[344.99]],
    },
    solucionOficial: 'SELECT AVG(total) AS promedio FROM pedidos WHERE empleado_id = 1;',
    solucionesAlternativas: [],
    explicacion: 'Calculamos el promedio (AVG) de la columna total, pero solo para un empleado específico.',
    pistas: ['AVG(total)', 'WHERE empleado_id = 1'],
    retroalimentacionError: 'Calcula el promedio de pedidos para el empleado 1',
  },
  {
    id: 'no-b-059',
    nivel: 'novato',
    titulo: 'Departamentos sin empleados (LEFT JOIN)',
    descripcion: 'Muestra el nombre del departamento que actualmente no tiene ningún empleado asignado.',
    objetivo: 'LEFT JOIN con WHERE IS NULL.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['nombre'],
      filas: [['Finanzas']],
    },
    solucionOficial: 'SELECT d.nombre FROM departamentos d LEFT JOIN empleados e ON d.id = e.departamento_id WHERE e.id IS NULL;',
    solucionesAlternativas: [],
    explicacion: 'Usamos LEFT JOIN para ver todos los departamentos y filtramos aquellos donde no hubo coincidencia en la tabla de empleados.',
    pistas: ['LEFT JOIN empleados e ON d.id = e.departamento_id', 'WHERE e.id IS NULL'],
    retroalimentacionError: 'LEFT JOIN departamentos y empleados, filtra donde el ID de empleado sea NULL',
  },
  {
    id: 'no-b-060',
    nivel: 'novato',
    titulo: 'Cantidad de ajustes por motivo',
    descripcion: 'Muestra cada motivo de ajuste de inventario y cuántas veces ha ocurrido.',
    objetivo: 'COUNT con GROUP BY sobre columna de texto.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['motivo', 'frecuencia'],
      filas: [['Dañado', 1], ['Extraviado', 1], ['Reabastecimiento', 1]],
    },
    solucionOficial: 'SELECT motivo, COUNT(*) AS frecuencia FROM inventario_ajustes GROUP BY motivo ORDER BY motivo;',
    solucionesAlternativas: [],
    explicacion: 'Contamos las ocurrencias de cada motivo agrupándolas.',
    pistas: ['COUNT(*)', 'GROUP BY motivo'],
    retroalimentacionError: 'Cuenta las filas agrupando por el motivo',
  },
  {
    id: 'no-b-061',
    nivel: 'novato',
    titulo: 'Clientes y sus pedidos (Resumen)',
    descripcion: 'Muestra el nombre del cliente y la fecha de su pedido más antiguo.',
    objetivo: 'MIN con GROUP BY y JOIN.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['nombre', 'primer_pedido'],
      filas: [['Ana García', '2024-01-05'], ['Bob Smith', '2024-01-10'], ['Carlos Ruiz', '2024-01-20'], ['Diana Lee', '2024-01-25']],
    },
    solucionOficial: 'SELECT c.nombre, MIN(p.fecha) AS primer_pedido FROM clientes c JOIN pedidos p ON c.id = p.cliente_id GROUP BY c.id, c.nombre ORDER BY primer_pedido;',
    solucionesAlternativas: [],
    explicacion: 'Buscamos la fecha mínima (la más antigua) para cada cliente uniendo ambas tablas.',
    pistas: ['MIN(p.fecha)', 'GROUP BY c.id, c.nombre'],
    retroalimentacionError: 'JOIN clientes y pedidos, agrupa por nombre y busca la fecha mínima',
  },
  {
    id: 'no-b-062',
    nivel: 'novato',
    titulo: 'Stock total de productos electrónicos',
    descripcion: 'Suma el stock de todos los productos que pertenecen a la categoría 1 (Electrónica).',
    objetivo: 'SUM con filtro WHERE.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['stock_electronica'],
      filas: [[60]],
    },
    solucionOficial: 'SELECT SUM(stock) AS stock_electronica FROM productos WHERE categoria_id = 1;',
    solucionesAlternativas: [],
    explicacion: 'Sumamos la columna stock solo para los productos que cumplen el criterio de categoría.',
    pistas: ['SUM(stock)', 'WHERE categoria_id = 1'],
    retroalimentacionError: 'Suma el stock donde categoria_id sea 1',
  },
  {
    id: 'no-b-063',
    nivel: 'novato',
    titulo: 'Proveedores fuera de China',
    descripcion: 'Lista el nombre y país de los proveedores que no están en China.',
    objetivo: 'Usar el operador de desigualdad (!= o <>).',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['nombre', 'pais'],
      filas: [['GlobalParts', 'Alemania'], ['ElectroPlus', 'España']],
    },
    solucionOficial: "SELECT nombre, pais FROM proveedores WHERE pais != 'China' ORDER BY nombre;",
    solucionesAlternativas: ["SELECT nombre, pais FROM proveedores WHERE pais <> 'China';"],
    explicacion: "El operador != excluye las filas que coinciden con el valor indicado.",
    pistas: ["pais != 'China'"],
    retroalimentacionError: "Filtra proveedores donde pais no sea 'China'",
  },
  {
    id: 'no-b-064',
    nivel: 'novato',
    titulo: 'Pedidos de alto valor por empleado',
    descripcion: 'Muestra el nombre del empleado y cuántos pedidos de más de 500 ha gestionado.',
    objetivo: 'JOIN, WHERE y COUNT con GROUP BY.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['nombre', 'pedidos_grandes'],
      filas: [['María', 1], ['Carlos', 2]],
    },
    solucionOficial: 'SELECT e.nombre, COUNT(p.id) AS pedidos_grandes FROM empleados e JOIN pedidos p ON e.id = p.empleado_id WHERE p.total > 500 GROUP BY e.id, e.nombre;',
    solucionesAlternativas: [],
    explicacion: 'Filtramos pedidos caros y luego contamos cuántos corresponden a cada empleado.',
    pistas: ['WHERE p.total > 500', 'COUNT(p.id)', 'GROUP BY e.id'],
    retroalimentacionError: 'JOIN empleados y pedidos, filtra total > 500 y cuenta por empleado',
  },
  {
    id: 'no-b-065',
    nivel: 'novato',
    titulo: 'Productos que empiezan por "T"',
    descripcion: 'Lista el nombre de los productos que comienzan con la letra T.',
    objetivo: 'LIKE con el comodín al final.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['nombre'],
      filas: [['Tablet'], ['Teclado']],
    },
    solucionOficial: "SELECT nombre FROM productos WHERE nombre LIKE 'T%' ORDER BY nombre;",
    solucionesAlternativas: [],
    explicacion: "LIKE 'T%' busca cualquier texto que empiece con T seguido de cualquier cosa.",
    pistas: ["nombre LIKE 'T%'"],
    retroalimentacionError: "Filtra productos donde nombre empiece por 'T'",
  },
  {
    id: 'no-b-066',
    nivel: 'novato',
    titulo: 'Productos por proveedor',
    descripcion: 'Muestra el nombre de cada proveedor y cuántos productos suministra. Incluye los proveedores que no tienen productos asignados (deben aparecer con 0).',
    objetivo: 'LEFT JOIN con GROUP BY y COUNT para incluir proveedores sin productos.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['proveedor', 'total_productos'],
      filas: [['ElectroPlus', 0], ['GlobalParts', 3], ['TechCorp', 3]],
    },
    solucionOficial: 'SELECT pr.nombre AS proveedor, COUNT(p.id) AS total_productos FROM proveedores pr LEFT JOIN productos p ON pr.id = p.proveedor_id GROUP BY pr.id, pr.nombre ORDER BY pr.nombre;',
    solucionesAlternativas: [],
    explicacion: 'LEFT JOIN incluye a ElectroPlus aunque no tenga productos. COUNT(p.id) devuelve 0 cuando p.id es NULL (el LEFT JOIN no encontró coincidencia).',
    pistas: ['LEFT JOIN productos p ON pr.id = p.proveedor_id', 'COUNT(p.id) cuenta productos; si no hay, devuelve 0', 'GROUP BY pr.id, pr.nombre'],
    retroalimentacionError: 'LEFT JOIN proveedores con productos y agrupa con COUNT(p.id)',
  },
  {
    id: 'no-b-067',
    nivel: 'novato',
    titulo: 'Empleados sin departamento asignado',
    descripcion: 'Busca en la tabla empleados si hay alguno que no tenga un departamento_id (NULL).',
    objetivo: 'Uso de IS NULL en filtros.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['nombre'],
      filas: [],
    },
    solucionOficial: 'SELECT nombre FROM empleados WHERE departamento_id IS NULL;',
    solucionesAlternativas: [],
    explicacion: 'En nuestro set de datos todos tienen departamento, por eso el resultado es vacío, pero la consulta es correcta para detectar errores de integridad.',
    pistas: ['WHERE departamento_id IS NULL'],
    retroalimentacionError: 'Filtra donde departamento_id sea NULL',
  },
  {
    id: 'no-b-068',
    nivel: 'novato',
    titulo: 'Ajustes de inventario negativos',
    descripcion: 'Lista los productos y la cantidad de ajuste solo para aquellos ajustes que restaron stock (menores a 0).',
    objetivo: 'Filtro numérico simple.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['producto', 'ajuste'],
      filas: [['Laptop Pro', -2], ['Monitor', -1]],
    },
    solucionOficial: 'SELECT p.nombre AS producto, ia.cantidad_ajuste AS ajuste FROM productos p JOIN inventario_ajustes ia ON p.id = ia.producto_id WHERE ia.cantidad_ajuste < 0;',
    solucionesAlternativas: [],
    explicacion: 'Filtramos los movimientos de inventario donde la cantidad sea negativa (salidas o mermas).',
    pistas: ['WHERE cantidad_ajuste < 0'],
    retroalimentacionError: 'Une tablas y filtra cantidad_ajuste menor a 0',
  },
  {
    id: 'no-b-069',
    nivel: 'novato',
    titulo: 'Clientes con Gmail',
    descripcion: 'Muestra el nombre y email de los clientes cuyo correo electrónico termina en "@mail.com".',
    objetivo: 'LIKE con comodín al principio.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['nombre', 'email'],
      filas: [['Ana García', 'ana@mail.com'], ['Bob Smith', 'bob@mail.com'], ['Carlos Ruiz', 'carlos@mail.com'], ['Diana Lee', 'diana@mail.com'], ['Eva Müller', 'eva@mail.com']],
    },
    solucionOficial: "SELECT nombre, email FROM clientes WHERE email LIKE '%@mail.com';",
    solucionesAlternativas: [],
    explicacion: "El comodín % al principio busca cualquier texto que termine con el patrón indicado.",
    pistas: ["LIKE '%@mail.com'"],
    retroalimentacionError: "Filtra emails que terminen en '@mail.com'",
  },
  {
    id: 'no-b-070',
    nivel: 'novato',
    titulo: 'Promedio de presupuesto por ciudad',
    descripcion: 'Calcula el presupuesto promedio de los departamentos agrupados por ciudad.',
    objetivo: 'AVG con GROUP BY sobre columna de texto.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['ciudad', 'presupuesto_medio'],
      filas: [['Barcelona', 575000.0], ['Madrid', 400000.0]],
    },
    solucionOficial: 'SELECT ciudad, AVG(presupuesto) AS presupuesto_medio FROM departamentos GROUP BY ciudad;',
    solucionesAlternativas: [],
    explicacion: 'Agrupamos los departamentos por su ciudad y calculamos el promedio de sus presupuestos.',
    pistas: ['GROUP BY ciudad', 'AVG(presupuesto)'],
    retroalimentacionError: 'Agrupa por ciudad y calcula el promedio del presupuesto',
  },
  {
    id: 'no-b-071',
    nivel: 'novato',
    titulo: 'Productos con stock mayor al promedio',
    descripcion: 'Muestra los productos cuyo stock es superior a 50 unidades.',
    objetivo: 'Filtro numérico directo.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['nombre', 'stock'],
      filas: [['Mouse', 150], ['Teclado', 80], ['Webcam', 100]],
    },
    solucionOficial: 'SELECT nombre, stock FROM productos WHERE stock > 50 ORDER BY stock DESC;',
    solucionesAlternativas: [],
    explicacion: 'Filtramos la tabla productos para ver solo los que tienen mucho inventario disponible.',
    pistas: ['WHERE stock > 50'],
    retroalimentacionError: 'Filtra productos con stock mayor a 50',
  },
  {
    id: 'no-b-072',
    nivel: 'novato',
    titulo: 'Pedidos realizados en enero 2024',
    descripcion: 'Lista los IDs y totales de pedidos realizados en el mes de enero de 2024.',
    objetivo: 'Filtrar fechas usando LIKE.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['id', 'total'],
      filas: [[1, 599.99], [2, 1299.99], [3, 89.99], [4, 349.99], [5, 799.99]],
    },
    solucionOficial: "SELECT id, total FROM pedidos WHERE fecha LIKE '2024-01-%';",
    solucionesAlternativas: ["SELECT id, total FROM pedidos WHERE fecha BETWEEN '2024-01-01' AND '2024-01-31';"],
    explicacion: 'Usamos LIKE para capturar todas las fechas que comiencen con el año y mes deseado.',
    pistas: ["LIKE '2024-01-%'"],
    retroalimentacionError: "Filtra pedidos de enero de 2024",
  },
  {
    id: 'no-b-073',
    nivel: 'novato',
    titulo: 'Cantidad de clientes por país',
    descripcion: 'Muestra cuántos clientes hay registrados en cada país.',
    objetivo: 'COUNT con GROUP BY.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['pais', 'cantidad'],
      filas: [['Alemania', 1], ['España', 1], ['Japón', 1], ['México', 1], ['USA', 1]],
    },
    solucionOficial: 'SELECT pais, COUNT(*) AS cantidad FROM clientes GROUP BY pais ORDER BY cantidad DESC;',
    solucionesAlternativas: [],
    explicacion: 'Contamos las filas de clientes agrupándolas por su país de origen.',
    pistas: ['GROUP BY pais', 'COUNT(*)'],
    retroalimentacionError: 'Agrupa por pais y cuenta los clientes',
  },
  {
    id: 'no-b-074',
    nivel: 'novato',
    titulo: 'Productos sin categoría (LEFT JOIN)',
    descripcion: 'Verifica si hay productos que no tengan una categoría válida asignada.',
    objetivo: 'Identificar huérfanos con LEFT JOIN.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['nombre'],
      filas: [],
    },
    solucionOficial: 'SELECT p.nombre FROM productos p LEFT JOIN categorias c ON p.categoria_id = c.id WHERE c.id IS NULL;',
    solucionesAlternativas: [],
    explicacion: 'Nuevamente, el resultado es vacío porque la BD está limpia, pero es la forma de encontrar productos sin categoría.',
    pistas: ['LEFT JOIN categorias', 'WHERE c.id IS NULL'],
    retroalimentacionError: 'Busca productos sin coincidencia en categorias',
  },
  {
    id: 'no-b-075',
    nivel: 'novato',
    titulo: 'Suma de ajustes por producto',
    descripcion: 'Calcula la suma total de los ajustes de inventario realizados a cada producto (por ID).',
    objetivo: 'SUM con GROUP BY.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['producto_id', 'ajuste_total'],
      filas: [[1, -2], [2, 50], [4, -1]],
    },
    solucionOficial: 'SELECT producto_id, SUM(cantidad_ajuste) AS ajuste_total FROM inventario_ajustes GROUP BY producto_id;',
    solucionesAlternativas: [],
    explicacion: 'Agrupamos por producto y sumamos todas las cantidades de ajuste (positivas y negativas).',
    pistas: ['GROUP BY producto_id', 'SUM(cantidad_ajuste)'],
    retroalimentacionError: 'Agrupa por producto_id y suma la cantidad_ajuste',
  },
  {
    id: 'no-b-076',
    nivel: 'novato',
    titulo: 'Clientes con nombres largos',
    descripcion: 'Muestra los clientes cuyo nombre tiene más de 10 caracteres.',
    objetivo: 'Usar la función LENGTH.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['nombre'],
      filas: [['Ana García'], ['Carlos Ruiz']],
    },
    solucionOficial: 'SELECT nombre FROM clientes WHERE LENGTH(nombre) > 10;',
    solucionesAlternativas: [],
    explicacion: 'La función LENGTH mide la cantidad de letras en una cadena de texto.',
    pistas: ['WHERE LENGTH(nombre) > 10'],
    retroalimentacionError: 'Filtra donde el largo del nombre sea mayor a 10',
  },
  {
    id: 'no-b-077',
    nivel: 'novato',
    titulo: 'Proveedores de Alemania',
    descripcion: 'Lista todos los datos de los proveedores que se encuentran en Alemania.',
    objetivo: 'Filtro WHERE básico.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['id', 'nombre', 'pais', 'contacto'],
      filas: [[2, 'GlobalParts', 'Alemania', 'hans@global.de']],
    },
    solucionOficial: "SELECT * FROM proveedores WHERE pais = 'Alemania';",
    solucionesAlternativas: [],
    explicacion: 'Filtro directo por valor exacto en una columna.',
    pistas: ["WHERE pais = 'Alemania'"],
    retroalimentacionError: "Filtra proveedores con pais igual a 'Alemania'",
  },
  {
    id: 'no-b-078',
    nivel: 'novato',
    titulo: 'Pedidos entre 100 y 1000',
    descripcion: 'Muestra los pedidos cuyo total esté en el rango de 100 a 1000.',
    objetivo: 'Uso de BETWEEN.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['id', 'total'],
      filas: [[1, 599.99], [4, 349.99], [5, 799.99]],
    },
    solucionOficial: 'SELECT id, total FROM pedidos WHERE total BETWEEN 100 AND 1000;',
    solucionesAlternativas: [],
    explicacion: 'BETWEEN es ideal para filtrar rangos numéricos de forma legible.',
    pistas: ['WHERE total BETWEEN 100 AND 1000'],
    retroalimentacionError: 'Filtra totales entre 100 y 1000',
  },
  {
    id: 'no-b-079',
    nivel: 'novato',
    titulo: 'Emails que no son .com',
    descripcion: 'Busca clientes cuyo email NO termine en ".com".',
    objetivo: 'Uso de NOT LIKE.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['nombre', 'email'],
      filas: [],
    },
    solucionOficial: "SELECT nombre, email FROM clientes WHERE email NOT LIKE '%.com';",
    solucionesAlternativas: [],
    explicacion: 'NOT LIKE invierte la búsqueda del patrón.',
    pistas: ["WHERE email NOT LIKE '%.com'"],
    retroalimentacionError: "Busca emails que no terminen en '.com'",
  },
  {
    id: 'no-b-080',
    nivel: 'novato',
    titulo: 'Departamentos y su presupuesto total',
    descripcion: 'Suma el presupuesto de todos los departamentos.',
    objetivo: 'SUM global.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['total_global'],
      filas: [[2350000.0]],
    },
    solucionOficial: 'SELECT SUM(presupuesto) AS total_global FROM departamentos;',
    solucionesAlternativas: [],
    explicacion: 'Suma de todos los valores de una columna en toda la tabla.',
    pistas: ['SUM(presupuesto)'],
    retroalimentacionError: 'Calcula la suma total de la columna presupuesto',
  },
  {
    id: 'no-b-081',
    nivel: 'novato',
    titulo: 'Productos ordenados por nombre descendente',
    descripcion: 'Lista los nombres de los productos ordenados de la Z a la A.',
    objetivo: 'Uso de ORDER BY DESC.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['nombre'],
      filas: [['Webcam'], ['Teclado'], ['Tablet'], ['Mouse'], ['Monitor'], ['Laptop Pro']],
    },
    solucionOficial: 'SELECT nombre FROM productos ORDER BY nombre DESC;',
    solucionesAlternativas: [],
    explicacion: 'El modificador DESC invierte el orden alfabético o numérico.',
    pistas: ['ORDER BY nombre DESC'],
    retroalimentacionError: 'Ordena por nombre de forma descendente',
  },
  {
    id: 'no-b-082',
    nivel: 'novato',
    titulo: 'Diferencia entre stock y stock ideal',
    descripcion: 'Muestra el nombre del producto y cuánto le falta para llegar a 200 unidades (asumiendo que 200 es el ideal).',
    objetivo: 'Operaciones aritméticas en el SELECT.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['nombre', 'faltante'],
      filas: [
        ['Laptop Pro', 180], ['Mouse', 50], ['Teclado', 120],
        ['Monitor', 185], ['Webcam', 100], ['Tablet', 175],
      ],
    },
    solucionOficial: 'SELECT nombre, (200 - stock) AS faltante FROM productos;',
    solucionesAlternativas: [],
    explicacion: 'Podemos realizar restas directamente entre constantes y valores de columnas.',
    pistas: ['200 - stock'],
    retroalimentacionError: 'Resta el stock de 200',
  },
  {
    id: 'no-b-083',
    nivel: 'novato',
    titulo: 'Clientes que han comprado mucho',
    descripcion: 'Muestra los nombres de clientes que tienen pedidos por un total superior a 1000.',
    objetivo: 'JOIN con filtro numérico.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['nombre', 'total'],
      filas: [['Bob Smith', 1299.99]],
    },
    solucionOficial: 'SELECT c.nombre, p.total FROM clientes c JOIN pedidos p ON c.id = p.cliente_id WHERE p.total > 1000;',
    solucionesAlternativas: [],
    explicacion: 'Filtramos los pedidos de gran valor y mostramos el nombre del cliente asociado.',
    pistas: ['JOIN clientes y pedidos', 'WHERE total > 1000'],
    retroalimentacionError: 'Une tablas y filtra donde el total sea mayor a 1000',
  },
  {
    id: 'no-b-084',
    nivel: 'novato',
    titulo: 'Ajustes realizados en febrero',
    descripcion: 'Muestra todos los ajustes de inventario realizados en el mes de febrero.',
    objetivo: 'Filtrar fechas con LIKE.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['id', 'motivo', 'fecha'],
      filas: [[1, 'Dañado', '2024-02-01'], [2, 'Reabastecimiento', '2024-02-05'], [3, 'Extraviado', '2024-02-10']],
    },
    solucionOficial: "SELECT id, motivo, fecha FROM inventario_ajustes WHERE fecha LIKE '%-02-%';",
    solucionesAlternativas: [],
    explicacion: 'Buscamos cualquier fecha que contenga "-02-" que representa el mes de febrero.',
    pistas: ["LIKE '%-02-%'"],
    retroalimentacionError: "Filtra fechas que contengan '-02-'",
  },
  {
    id: 'no-b-085',
    nivel: 'novato',
    titulo: 'Cantidad de categorías distintas',
    descripcion: 'Cuenta cuántas categorías diferentes existen en la tabla productos.',
    objetivo: 'COUNT DISTINCT.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['total_categorias'],
      filas: [[2]],
    },
    solucionOficial: 'SELECT COUNT(DISTINCT categoria_id) AS total_categorias FROM productos;',
    solucionesAlternativas: [],
    explicacion: 'DISTINCT asegura que solo contemos valores únicos de la columna.',
    pistas: ['COUNT(DISTINCT categoria_id)'],
    retroalimentacionError: 'Cuenta los valores únicos de categoria_id',
  },
  {
    id: 'no-b-086',
    nivel: 'novato',
    titulo: 'Primeros 2 proveedores',
    descripcion: 'Muestra los primeros 2 proveedores de la tabla ordenados por ID.',
    objetivo: 'Uso de LIMIT.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['id', 'nombre'],
      filas: [[1, 'TechCorp'], [2, 'GlobalParts']],
    },
    solucionOficial: 'SELECT id, nombre FROM proveedores ORDER BY id LIMIT 2;',
    solucionesAlternativas: [],
    explicacion: 'LIMIT restringe la cantidad de filas devueltas por la consulta.',
    pistas: ['ORDER BY id', 'LIMIT 2'],
    retroalimentacionError: 'Ordena por ID y limita a 2 resultados',
  },
  {
    id: 'no-b-087',
    nivel: 'novato',
    titulo: 'Ventas de productos que contienen "Pro"',
    descripcion: 'Muestra el total de ventas de pedidos cuyo producto asociado contiene la palabra "Pro".',
    objetivo: 'JOIN con LIKE.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['total_ventas_pro'],
      filas: [[2099.98]],
    },
    solucionOficial: "SELECT SUM(p.total) AS total_ventas_pro FROM pedidos p JOIN productos prod ON p.id = prod.id WHERE prod.nombre LIKE '%Pro%';",
    solucionesAlternativas: [],
    explicacion: 'Filtramos productos por nombre y sumamos los totales de sus pedidos correspondientes.',
    pistas: ["WHERE prod.nombre LIKE '%Pro%'", 'SUM(p.total)'],
    retroalimentacionError: "Une tablas, filtra productos con 'Pro' y suma el total",
  },
  {
    id: 'no-b-088',
    nivel: 'novato',
    titulo: 'Empleados activos en Barcelona',
    descripcion: 'Lista los nombres de empleados activos (1) que trabajan en Barcelona.',
    objetivo: 'JOIN con múltiples condiciones en WHERE.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['nombre'],
      filas: [['Carlos'], ['Laura'], ['Miguel']],
    },
    solucionOficial: "SELECT e.nombre FROM empleados e JOIN departamentos d ON e.departamento_id = d.id WHERE e.activo = 1 AND d.ciudad = 'Barcelona';",
    solucionesAlternativas: [],
    explicacion: 'Combinamos filtros de dos tablas diferentes usando AND.',
    pistas: ['WHERE activo = 1 AND ciudad = Barcelona'],
    retroalimentacionError: "Filtra activo=1 y ciudad='Barcelona'",
  },
  {
    id: 'no-b-089',
    nivel: 'novato',
    titulo: 'Email de proveedores de China',
    descripcion: 'Muestra el contacto de los proveedores que son de China.',
    objetivo: 'Filtro simple.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['contacto'],
      filas: [['li@techcorp.com']],
    },
    solucionOficial: "SELECT contacto FROM proveedores WHERE pais = 'China';",
    solucionesAlternativas: [],
    explicacion: 'Selección de una columna específica con un filtro de fila.',
    pistas: ["WHERE pais = 'China'"],
    retroalimentacionError: "Filtra proveedores con pais='China'",
  },
  {
    id: 'no-b-090',
    nivel: 'novato',
    titulo: 'Último pedido registrado',
    descripcion: 'Muestra la fecha del último pedido realizado en la empresa.',
    objetivo: 'Uso de MAX.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['fecha_reciente'],
      filas: [['2024-01-25']],
    },
    solucionOficial: 'SELECT MAX(fecha) AS fecha_reciente FROM pedidos;',
    solucionesAlternativas: [],
    explicacion: 'MAX sobre una columna de tipo fecha/texto ISO devuelve la más reciente cronológicamente.',
    pistas: ['MAX(fecha)'],
    retroalimentacionError: 'Busca el valor máximo de la columna fecha',
  },
  {
    id: 'no-b-091',
    nivel: 'novato',
    titulo: 'Productos con ID par',
    descripcion: 'Muestra los nombres de productos cuyo ID es un número par.',
    objetivo: 'Uso del operador módulo (%).',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['nombre'],
      filas: [['Mouse'], ['Monitor'], ['Tablet']],
    },
    solucionOficial: 'SELECT nombre FROM productos WHERE id % 2 = 0;',
    solucionesAlternativas: [],
    explicacion: 'El operador % devuelve el resto de la división. Si es 0, el número es par.',
    pistas: ['WHERE id % 2 = 0'],
    retroalimentacionError: 'Filtra donde el ID módulo 2 sea igual a 0',
  },
  {
    id: 'no-b-092',
    nivel: 'novato',
    titulo: 'Salarios entre 45000 y 55000',
    descripcion: 'Lista los empleados con salarios en el rango inclusivo de 45000 a 55000.',
    objetivo: 'BETWEEN numérico.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['nombre', 'salario'],
      filas: [['María', 45000.0], ['Ana', 48000.0], ['Sofía', 52000.0], ['Elena', 50000.0], ['Andrés', 55000.0]],
    },
    solucionOficial: 'SELECT nombre, salario FROM empleados WHERE salario BETWEEN 45000 AND 55000;',
    solucionesAlternativas: [],
    explicacion: 'Filtramos un rango salarial específico usando BETWEEN.',
    pistas: ['WHERE salario BETWEEN 45000 AND 55000'],
    retroalimentacionError: 'Filtra salarios entre 45000 y 55000',
  },
  {
    id: 'no-b-093',
    nivel: 'novato',
    titulo: 'Proveedores con nombre corto',
    descripcion: 'Lista los proveedores cuyo nombre tiene 10 letras o menos.',
    objetivo: 'LENGTH en filtros.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['nombre'],
      filas: [['TechCorp']],
    },
    solucionOficial: 'SELECT nombre FROM proveedores WHERE LENGTH(nombre) <= 10;',
    solucionesAlternativas: [],
    explicacion: 'Medimos el largo del nombre del proveedor para filtrar empresas con nombres cortos.',
    pistas: ['WHERE LENGTH(nombre) <= 10'],
    retroalimentacionError: 'Filtra donde el largo del nombre sea 10 o menos',
  },
  {
    id: 'no-b-094',
    nivel: 'novato',
    titulo: 'Pedidos con estado "enviado"',
    descripcion: 'Muestra el total y la fecha de todos los pedidos que ya han sido enviados.',
    objetivo: 'Filtro de texto exacto.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['total', 'fecha'],
      filas: [[799.99, '2024-01-25']],
    },
    solucionOficial: "SELECT total, fecha FROM pedidos WHERE estado = 'enviado';",
    solucionesAlternativas: [],
    explicacion: "Buscamos filas que coincidan exactamente con el estado 'enviado'.",
    pistas: ["WHERE estado = 'enviado'"],
    retroalimentacionError: "Filtra pedidos con estado 'enviado'",
  },
  {
    id: 'no-b-095',
    nivel: 'novato',
    titulo: 'Media de stock global',
    descripcion: 'Calcula el promedio de unidades en stock que tienen los productos.',
    objetivo: 'AVG global.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['stock_promedio'],
      filas: [[65.83333333333333]],
    },
    solucionOficial: 'SELECT AVG(stock) AS stock_promedio FROM productos;',
    solucionesAlternativas: [],
    explicacion: 'Cálculo del promedio simple de una columna numérica.',
    pistas: ['AVG(stock)'],
    retroalimentacionError: 'Calcula el promedio de la columna stock',
  },
  {
    id: 'no-b-096',
    nivel: 'novato',
    titulo: 'Empleados con nombre que contiene "a"',
    descripcion: 'Lista los nombres de empleados que contienen al menos una letra "a" (minúscula).',
    objetivo: 'LIKE con comodines en ambos lados.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['nombre'],
      filas: [['María'], ['Ana'], ['Laura'], ['Sofía'], ['Javier'], ['Elena']],
    },
    solucionOficial: "SELECT nombre FROM empleados WHERE nombre LIKE '%a%';",
    solucionesAlternativas: [],
    explicacion: 'El patrón %a% encuentra la letra en cualquier posición de la cadena.',
    pistas: ["LIKE '%a%'"],
    retroalimentacionError: "Busca nombres que contengan la letra 'a'",
  },
  {
    id: 'no-b-097',
    nivel: 'novato',
    titulo: 'Ventas mayores al promedio (Estático)',
    descripcion: 'Muestra los pedidos cuyo total es mayor a 500.',
    objetivo: 'Filtro numérico simple.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['id', 'total'],
      filas: [[1, 599.99], [2, 1299.99], [5, 799.99]],
    },
    solucionOficial: 'SELECT id, total FROM pedidos WHERE total > 500;',
    solucionesAlternativas: [],
    explicacion: 'Seleccionamos las ventas más importantes basadas en un umbral fijo.',
    pistas: ['WHERE total > 500'],
    retroalimentacionError: 'Filtra pedidos con total mayor a 500',
  },
  {
    id: 'no-b-098',
    nivel: 'novato',
    titulo: 'Suma de salarios por ciudad',
    descripcion: 'Muestra cuánto gasta la empresa en salarios por cada ciudad.',
    objetivo: 'JOIN con SUM y GROUP BY.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['ciudad', 'gasto_salarios'],
      filas: [['Barcelona', 195000.0], ['Madrid', 336000.0]],
    },
    solucionOficial: 'SELECT d.ciudad, SUM(e.salario) AS gasto_salarios FROM empleados e JOIN departamentos d ON e.departamento_id = d.id GROUP BY d.ciudad;',
    solucionesAlternativas: [],
    explicacion: 'Unimos tablas para asociar empleados con su ciudad y sumamos sus salarios agrupados.',
    pistas: ['JOIN empleados y departamentos', 'SUM(salario)', 'GROUP BY ciudad'],
    retroalimentacionError: 'Agrupa por ciudad y suma los salarios de los empleados',
  },
  {
    id: 'no-b-099',
    nivel: 'novato',
    titulo: 'Productos de Electrónica caros',
    descripcion: 'Lista los nombres de productos de la categoría 1 que cuestan más de 400.',
    objetivo: 'WHERE con múltiples condiciones numéricas.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['nombre'],
      filas: [['Laptop Pro'], ['Monitor']],
    },
    solucionOficial: 'SELECT nombre FROM productos WHERE categoria_id = 1 AND precio > 400;',
    solucionesAlternativas: [],
    explicacion: 'Filtramos por dos columnas numéricas simultáneamente.',
    pistas: ['WHERE categoria_id = 1 AND precio > 400'],
    retroalimentacionError: 'Filtra categoria_id=1 y precio > 400',
  },
  {
    id: 'no-b-100',
    nivel: 'novato',
    titulo: 'Resumen final Novato',
    descripcion: 'Muestra el nombre del cliente, el nombre del producto comprado y el total del pedido para todos los pedidos completados.',
    objetivo: 'JOIN de tres tablas con filtro de texto.',
    setupSql: SETUP,
    resultadoEsperado: {
      columnas: ['cliente', 'producto', 'total'],
      filas: [['Ana García', 'Laptop Pro', 599.99], ['Bob Smith', 'Mouse', 1299.99], ['Carlos Ruiz', 'Monitor', 349.99]],
    },
    solucionOficial: "SELECT c.nombre AS cliente, prod.nombre AS producto, p.total FROM pedidos p JOIN clientes c ON p.cliente_id = c.id JOIN productos prod ON p.id = prod.id WHERE p.estado = 'completado';",
    solucionesAlternativas: [],
    explicacion: 'Gran unión final para este nivel, relacionando clientes, pedidos y productos bajo una condición de estado.',
    pistas: ['JOIN pedidos, clientes y productos', "WHERE estado = 'completado'"],
    retroalimentacionError: "Une las 3 tablas y filtra por estado 'completado'",
  },
];

